### ISSUE TITLE
CC on project (self-)assessment tools

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1000]
Author: @rinkug 
EB member: @curfman 

<https://internews.org/areas-of-expertise/global-tech/resources/open-source-software-lightweight-needs-assessment/>
<https://rateyourproject.org/>
<https://www.software.ac.uk/resources/online-sustainability-evaluation>

and probably others, with a bit of searching.  I suggest maybe a single article for the category, but that's open to discussion.

**Comment by rinkug** [comment]
This is published as a single cc article. Please see PR for details
