### ISSUE TITLE
Evidence supporting modern code review

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1025]
https://rethought.se/research/modern-code-reviews/

This site was mentioned in: https://neverworkintheory.org/2021/08/16/modern-code-review.html.  I think it would be great to have this site as a CC resource.  It is common for software teams to want evidence before adopting particular practices.

**Comment by bartlettroscoe** [comment]
I have read a few other online resources that give research and guidance derived from that research for doing effective code reviews.  If we add those, we can create a collection of links in one CC article.

**Comment by bartlettroscoe** [comment]
FYI: The link:

* https://rethought.se/research/modern-code-reviews/

seems to be broken.

**Comment by bernhold** [comment]
Hmmm, works for me. VPN problem? Sandia doesn't like Sweden or something? :-)

**Comment by bartlettroscoe** [comment]
> VPN problem?

Looks like that is the problem.   Off VPN I can get to the site. (Usually the SNL filters will say it is blocked or will display the site using a safe filter site.)

**Comment by bartlettroscoe** [comment]
My suggestion in https://github.com/betterscientificsoftware/bssw.io/issues/409#issuecomment-1079702025 is to create a more expansive short/original article that is a sort of summary/cliff notes for code peer review best practices based on current research on peer reviews.

**Comment by bernhold** [comment]
Closing this in favor of #409
