### ISSUE TITLE
Harvest unneeded branches

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1029]
We have O(70-80) branches in this repository.  I'm pretty sure that the vast majority of them are leftovers from old PRs which have been merged.  We should (a) get rid of old branches which have served their purpose and (b) instill a culture (maybe an automation) of immediately deleting branches on merge to keep things clean.

**Comment by rinkug** [comment]
Action:
* Everyone cleans their branches 
* Revisit this issue in 3 weeks

**Comment by bernhold** [comment]
I have turned on the option in repository settings to automatically delete the branch associated with a PR when the PR is merged.  This should help keep things cleaner going forward.

**Comment by bernhold** [comment]
I have removed all of the branches associated with MERGED PRs.

**Comment by bernhold** [comment]
@rinkug you have one branch for a closed PR.  Please review the content to see if it can be deleted.   https://github.com/betterscientificsoftware/bssw.io/tree/rinkug-perfport-tools

**Comment by bernhold** [comment]
@rinkug  you also have a branch not associated with a PR that you should take a look at: https://github.com/betterscientificsoftware/bssw.io/tree/rinkug-images-README

**Comment by bernhold** [comment]
We're now down to open PRs and a handful of cases I've asked specific individuals to look at.  This is a *lot* better than where we were!

**Comment by bernhold** [comment]
If we find that old branches start accumulating again in the future, this action might be useful: https://github.com/marketplace/actions/notify-unused-branches

There are other actions that delete branches over a certain age.  But that seems a bit draconian.  This looks like a safer way of at creating awareness of old branches.  Though in our setup, we'd really want to add a `scope: site-internal` label on creation to get it onto the right project board.  Otherwise, it might get lost and not be helpful.

**Comment by bernhold** [comment]
@rinkug you have one branch that is *not* associated with a PR: https://github.com/betterscientificsoftware/bssw.io/tree/rinkug-images-README. This branch is 5 months old.  It appears to have one commit that may not be in master, but is otherwise well behind master (794 commits).  Can you take a look and determine whether we can do something with it or get rid of it?

Thanks

**Comment by rinkug** [comment]
Are ready to close this?

**Possible actions before closing:**
* If we find that old branches start accumulating again in the future, this action might be useful: https://github.com/marketplace/actions/notify-unused-branches
* Though in our setup, we'd really want to add a scope: site-internal label on creation to get it onto the right project board

**Comment by rinkug** [comment]
Closing this for now without further action items.
