### ISSUE TITLE
Possible Blog Article

### ISSUE THREAD

**Issue by oamarques** [betterscientificsoftware/bssw.io#1074]
This is a draft related to https://github.com/betterscientificsoftware/bssw-blog-planning/issues/104, which I realize is overdue. Hopefully, this will be in a good shape by October 1. I acknowledge it is still rough and short but I would like to know if it is in the right direction before expanding it.

----------------------------------------------------

With the October 13 event we celebrate the 50th webinar in the HPC Best Practices series (HPC-BP), with funds from DOE’s Exascale Computing Project (ECP). In the ECP era, the series started on June 6, 2017, with a webinar on Python in HPC. In the 4+ years that followed, we have offered webinars on a variety of topics, always working with speakers to take into account a broad audience, the inclusion of pointers to both basic information and supplementary/advanced information and, also important, "big-picture takeaways." 

The first webinars in the series were offered in a somewhat ad hoc fashion, without much attention to action items or a specific timeline other than the webinar itself. However, we quickly realized that we needed a process, encompassing the selection of (potential) topics and speakers, advertisement, etc. We started with a checklist of 8 items, which then evolved to a checklist of 20+ items in a Trello board. The process has evolved further, into a (private) github project, in which potential topics became issues. Once a topic has been selected and a speaker has been confirmed, the issue is elevated and the checklist is incorporated in it. 

On average, 166 people have signed up for a webinar (including 48 affiliated with ECP) in the series, with an actual attendance of about 50%.

**Comment by pagrubel** [comment]
Wouldn't it be better to focus on/and perhaps highlight some of the webinars more than the evolution of procedures for a blog article?

**Comment by bernhold** [comment]
Osni and I are working in a Google doc.  We have a new draft that I think is more in line with your suggestion.  Though we have a bit of work to do yet. Maybe we'll ask you to review soon.

**Comment by bernhold** [comment]
This has been overtaken by events.  Blog article is here: https://bssw.io/blog_posts/best-practices-for-hpc-software-developers-the-first-five-years-of-the-webinar-series
