### ISSUE TITLE
Possible issue with wikize_refs.py -r 1 -i

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#1093]
CC: @markcmiller86 

There might be an issue with the `wikize_refs.py -r` option.  When I ran:

```
$ cd ~/Articles/ShortArticles/

$ ../../utils/wikize_refs.py -r 1 -i CodingConvensions.md
```

on the commit version of the file `CodingConvensions.md` in commit https://github.com/bartlettroscoe/bssw.io/commit/3015586c243dc58a9591829c0559c22688198388 on the branch [435-cc-coding-conventions](https://github.com/bartlettroscoe/bssw.io/blob/435-cc-coding-conventions/Articles/ShortArticles/CodingConvensions.md) which had the references stated at:

![image](https://user-images.githubusercontent.com/1959736/135504929-5659b2fc-6ee8-4f02-bad5-b9e439ed6a09.png)

it gave the commit https://github.com/bartlettroscoe/bssw.io/commit/6fc0950b237193739d2a37cdb17236a56ef2fbdb which I pushed to the branch [435-cc-coding-conventions-wikize_refs-r-issue](https://github.com/bartlettroscoe/bssw.io/blob/435-cc-coding-conventions-wikize_refs-r-issue/Articles/ShortArticles/CodingConvensions.md) which produced the references starting with '2' instead of '1' as:

![image](https://user-images.githubusercontent.com/1959736/135505016-923acca1-247f-4b07-89e7-75219d65127c.png)

Should this not start with '1' instead of '2'?

**Comment by rinkug** [comment]
@markcmiller86 and @bartlettroscoe need to discuss this.
