### ISSUE TITLE
Would a "what's new" perspective be useful to readers?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1094]
I think it might be useful to have a way of viewing BSSw articles by posting date.  This would allow occasional visitors to see what has been added/changed since they were last here.  Do others think this would be useful?

(Related, can we have a selector for search results to be sorted by date?)

This will clearly require changes to the front-end.  And Sandbox (our design consultants) may have opinions about the utility.  But the first question is what to *we* think?

**Comment by rinkug** [comment]
@bernhold : While search published results using publication date order (and shows the pub date), I am not sure if our navigation results do the same. Maybe the "Recent additions" link we told Parallactic to add might resolve this issue?

**Comment by bernhold** [comment]
We now have "Latest resources", based on publication dates in the articles.  I think that does what I suggested, do I'm going to close this.
