### ISSUE TITLE
OSPOCON Words Matter Panel

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#1137]
I participated in this panel on inclusive language at OSPOCON.

I can write a short CC for it if there is interest in hosing a CC on it.

https://www.youtube.com/watch?v=pO6m7xI7ia8

**Comment by bernhold** [comment]
Mark, I think you're the lead author of a cc resource on inclusive language. Why not put all of this in one place, unless it is in some way distinctive (besides you being a participant)?

**Comment by markcmiller86** [comment]
> unless it is in some way distinctive (besides you being a participant)?

I felt it was *distinct* from the list of textual resources for a couple of reasons. First, its not about offering guidance on specific terminology. Its more about personal experiences of panelists within their respective organizations as well as their organization's efforts. About whats involved in gaining adoption, etc. Second, its a video resource, not textual.

All that said, if you'd rather it just be glommed into that resource page, I am happy to put it there.

**Comment by bernhold** [comment]
To me, text vs video is not a reason to separate.  I haven't had time to actually review the recording, so I can't yet comment on the other aspect.
