### ISSUE TITLE
Related articles list has duplicated entries.

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#1138]
I was browsing on `bssw.io` [here](https://bssw.io/blog_posts/continuous-technology-refreshment-an-introduction-using-recent-tech-refresh-experiences-on-visit) and happened to scroll to bottom and noticed that the list of *related* articles includes a number of duplicates. And, those dups are the same article that the page is already showing. Here is a snapshot of the bottom...

![Screen Shot 2021-11-17 at 2 47 44 PM](https://user-images.githubusercontent.com/5720676/142294994-8fbb338d-be04-48c5-b07e-ed3b6d84b2dc.png)

**Comment by bernhold** [comment]
I hadn't even noticed this. I wonder how long it has been there?  It appears to be only for blog posts.

Anyway, if we're going to keep that feature, I agree it needs to be filtered to eliminate duplicates and to remove the article that you're viewing.  I've asked SBX/PC to look into it.

**Comment by markcmiller86** [comment]
My guess is that its doing a simple merge of three lists of articles tagged as `Revision Control`, `Issue Tracking` and `Documentation` (the three tags used in the article showing on the page) perhaps also weighted by most views or most recent or something. That explains 3 dups for the article its showing on the page.

**Comment by bernhold** [comment]
I came to the same conclusion.  I asked them to (a) eliminate dupes and (b) remove the "parent" article. No response yet.

**Comment by bernhold** [comment]
This has been fixed.  Still working to refine the algorithm that selects the articles to list.  Currently it is the most recent five blog posts with any topical overlap (as specified in the metadata).  The request is to go for a breadth-first approach that tries to cover *all* topics.  But I think we can close this particular issue as fixed.
