### ISSUE TITLE
Lost content

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#1145]
My article on [pull request size matters](https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/ShortArticles/PullRequestSizeConsiderations.md) has gone missing from the live site.

It was there recently because Google has [indexed it](https://www.google.com/search?q=%22Pull+Request+Size+Matters%22+site%3Abssw.io&client=safari&sxsrf=AOaemvJIraF5UpCb3-VToPejoPl02l-kmg%3A1638471912974&ei=6BipYZiCO8m8tAb7-o-gAQ&ved=0ahUKEwiYluPC58X0AhVJHs0KHXv9AxQQ4dUDCA4&uact=5&oq=%22Pull+Request+Size+Matters%22+site%3Abssw.io&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGABQAFj7MGDfOmgAcAB4AIABYogB8RKSAQIyN5gBAKABAcABAQ&sclient=gws-wiz).

But, if dig into [Google's Cache](https://webcache.googleusercontent.com/search?q=cache:CXRLv8KxvdcJ:https://bssw.io/items%3Ftopic%3Drevision-control+&cd=2&hl=en&ct=clnk&gl=us&client=safari) (this link may not be good for very long) and follow a link from there to it, I get to [`https://bssw.io/items/pull-request-size-matters`](https://bssw.io/items/pull-request-size-matters) which yields a `404 Not found` (which is linking to the article from bssw.io's `items` index). I dunno how to manually construct a path to content on bssw.io given I know the article type and markdown filename (we should be able to do that shouldn't we) so the article may still be there in some way and just not hooked up to the other things it should be hooked up to.

The metadata in the article is...

```
<!---
 Publish: yes
 Pinned: no
 Topics: revision control, development tools
 RSS update: 2021-02-18
 --->
```

**Comment by bernhold** [comment]
The URLs on bssw are based on the article title, "slugified".  Basically, the title is lowercased and the spaces are replaced with hyphens.  There are rules for special characters, but I don't know what the are off the top of my head.

**Comment by markcmiller86** [comment]
@bernhold ok, thanks. I think I recall you mentioning that in the past. However, that addresses *just* the last component in the path, the file name itself. Is `items` a flat namespace of all hosted files? Or, do glob articles go in some folder named `blog`, curated content in some folder named `curated_content`?

**Comment by bernhold** [comment]
I think *all* articles can be found in items.  Some will immediately redirect to other URLs (blog_posts, events), but you can get there through items.

**Comment by markcmiller86** [comment]
> I think _all_ articles can be found in items.

Ok, if that is true, I believe the article was (IT NOW LOOKS LIKE THE ARTICLE IS THERE) not actually on the live site because that is the link (https://bssw.io/items/pull-request-size-matters)

**Comment by markcmiller86** [comment]
@rinkug it looks like this is now resolved. But, do we know what/why it happened? Did it happen to any other articles. Are we sure we can avoid going forward?

**Comment by bernhold** [comment]
There was some issue with "extra" spaces somewhere in the metadata block causing problems processing it. It was not interpreting that it should be published. Clara fixed the front-end to eliminate this problem.

**Comment by markcmiller86** [comment]
Ok, sounds good. That said, can any of us think of a simple smoke-check we can perform here on the repo and then again on the live site to cross-check that what we believe is published content is really there on the live site? I suppose we could write a python script that iterates over all `publish: Yes` `.md` files and does google searches (and follows resulting links to confirm no `404 Not found`) or simply constructs the links using the slugification algorithm and attempts to access them. Would such a tool be of any use?

**Comment by bernhold** [comment]
I'm trying to think through how far we want to go with this.  From one standpoint, I can see some value in what you suggest.  But it is a non-trivial amount of work to implement and then we need to use it regularly.  And using it is also going to be kind of time-consuming (though it should be fire-and-forget until it completes).

What if we had a report from the front-end, from every rebuild, as to the unpublished content that it processed?  I haven't investigated, but I assume that's a relatively short list. We'd still need to check it periodically.  But it is probably not number that changes a lot, so maybe the rebuild page could include the *number* of unpublished files in the build and we could key on changes.  If it changes unexpectedly, we should investigate.

This assumes that if it correctly interprets the publish metadata tag that the rest works and it appears on the site.  Which would have been the case here, but perhaps not for other bugs.

The most common reason for things not appearing is title collisions, though I am not aware that this has been a problem lately.    In this situation, neither approach would catch the problem.  The script would happily retrieve the same URL for two articles.  And in the other case I don't *think* it will change the counts.

**Comment by bernhold** [comment]
I just realized that the counts are really only going to be useful to determine whether a new file is picked up properly or not.  In this case, I think a bug crept in (since the article definitely was visible initially) and on one build the article would have flipped from published to unpublished.  But it could have been someone else adding an unpublished article (for whatever reason).  If this prompted you to look at the list of unpublished files, I'm guessing you may or may not notice what's new or know whether it should be listed there or not.  You'd have to investigate any file that you didn't already "know" (somehow) the intended status.

**Comment by markcmiller86** [comment]
So, something like this gets close and takes approx 3-5 mins to complete. It needs a little more work to handle all slugification corner cases. Turns out not everything is in `items`. Some things are in `communities`. Worth going further?

While at top of repo...

```
find . -name utils -prune \
-o -name '*.md' \
-exec grep -q -i 'Publish: Yes' {} \; \
-exec grep -m 1 '^# ' {} \; | \
cut -d' ' -f2- | \
tr '[:upper:]' '[:lower:]' | \
tr -d ':?();,{}+=_[]!"”“' | \
tr "'" "-" | tr ' /’' '---' | \
xargs -n 1 -I'{}' sh -c \
"wget --no-check-certificate https://bssw.io/items/{} -o /dev/null || echo {} Not found"
```

Explanation...

* `-name utils -prune` prevents descending into `utils` dir
* `-o -name '*.md` restricts work to just markdown files
* `-exec grep -q -i 'Publish: Yes' {} \;` siltently (grep doesn't echo anything) restricts work to files that contain this critical metadata (case insensitive)
* `-exec grep -m 1 '^# ' {} \;` echo first match of level 1 markdown heading...probably the article title
* `cut -d' ' -f2-` take all text after the leading `# ` in what was echoed from grep (in line above)
* `tr '[:upper:]' '[:lower:]'` converts everything in string to lower case
* `tr -d ':?();,{}+=_[]!"”“'` part of the slugification algorithm to delete various chars (**note:** includes smart quote chars)
* `tr "'" "-" | tr ' /’' '---'` part of the slugification algorithm to replace various chars with dashes
* `xargs -n 1 -I'{}' sh -c` use the string produced from preceding everywhere `{}` appears in a command specified to shell via `-c` arg
* `"wget --no-check-certificate https://bssw.io/items/{} -o /dev/null || echo {} Not found"` the shell command to execute...attempt to wget the file from the `items` dir (see note above...not all articles are in `items`) and send it to `/dev/null` or echo `Not found` if `wget` failed for any reason (typically missing doc).

**Comment by markcmiller86** [comment]
The above command wasn't quite right...it would save all the downloaded files to the dir it was executed from. After running in a few times, I had 1,600+ files :wink:! The below command fixes that and some other corner cases.

It also looks like we have some non-standard characters in places too. We have smart double and single quotes in places and a funky long-dash character in [this title](https://raw.githubusercontent.com/betterscientificsoftware/bssw.io/c3819bb1934da4555a26544c50e717050ca5d851/CuratedContent/FellowshipProgrammeSoftwareSustainabilityInstituteUK.md). Should we clean these up? I mean, I don't think we should have these non-standard chars in our titles.

```
find . -name utils -prune \
-o -name '*.md' \
-exec grep -q -i 'Publish: Yes' {} \; \
-exec grep -m 1 '^# ' {} \; | \
cut -d' ' -f2- | \
tr '[:upper:]' '[:lower:]' | \
sed -e 's@](https\{0,1\}://.*)@@g' | \
tr '.&' '--' | \
tr -d ':?();,{}+=_[]"”“@%$#<>|*!' | \
tr "'" "-" | tr ' /’.—' '-----' | \
tr -s '-' | \
sed -e 's/^-//' -e 's/-$//' | \
xargs -n 1 -I'{}' sh -c \
"wget --no-check-certificate https://bssw.io/items/{} -O foo.html -o /dev/null || echo {} Not found"
```

or in all one line...

```
find . -name utils -prune -o -name '*.md' -exec grep -q -i 'Publish: Yes' {} \; -exec grep -m 1 '^# ' {} \; | cut -d' ' -f2- | tr '[:upper:]' '[:lower:]' | sed -e 's@](https\{0,1\}://.*)@@g' | tr '.&' '--' | tr -d ':?();,{}+=_[]"”“@%$#<>|*!' | tr "'" "-" | tr ' /’.—' '-----' | tr -s '-' | sed -e 's/^-//' -e 's/-$//' | xargs -n 1 -I'{}' sh -c "wget --no-check-certificate https://bssw.io/items/{} -O foo.html -o /dev/null || echo {} Not found"
```

It takes about 5 mins to run (which I think is heavily dependent on bssw.io response times) and yields the following list of *Not found* files....

```
instructions-delete-this-section Not found
environmental-system-science-community Not found
software-engineering-community Not found
computational-molecular-sciences-community Not found
scientific-libraries-community Not found
exascale-computing-community Not found
community-of-supercomputer-facilities-and-their-users Not found
resource-template-aggregate-base Not found
resource-template Not found
resource-template-aggregate-subresource Not found
{} Not found
webinar-basic-performance-analysis-and-optimization-–-an-ant-farm-approach Not found
webinar-automated-fortran–c-bindings-for-large-scale-scientific-applications Not found
webinar-sycl-–-introduction-and-best-practices Not found
{} Not found
```

The `community` ones are because the are not in `items`. I assume same is true for the `webinar` ones. The two empty cases I still need to investigate but its very close.

**Comment by markcmiller86** [comment]
One of the reasons I kinda like exercises like this is that they always wind up revealing what may be missing in our assumptions about how things work. Not all docs are in `items`. Not all titles are using just ascii characters. We have some "published" files that really seem more like they are templates for our internal docs (`resource-template-*` and friends in the above output).

**Comment by markcmiller86** [comment]
Ok, the cases where the above shell `find`+`xargs` command can fail are...

* if the `xargs` command exceeeds 255 characters. This happens in a couple of cases because of the very long document titles.
* if the article is not in `items` (some content is not but is in `webinars` or `communities`)
* if there are funky (unicode) characters in the `.md` files for the document titles. I think we should remove those anyways.

**Comment by markcmiller86** [comment]
Ok, @bernhold I have something I think works for this. I put most of the work into a small bash script...

```
#!/bin/sh

# slurp up all args but arg 0
title="${@:1}"

# slugify the title (beware...unicode chars in sed -e args, cut-n-paste may or may not capture them. For safety, the file is also attached here below)
slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed -e 's@](https\{0,1\}://.*)@@g' | tr '.&' '--' | tr -d ':?();,{}+=_[]"”“@%$#<>|*!' | tr "'" "-" | tr ' /’.' '----' | sed -e 's/-–-/-/g' | sed -e 's/-—-/-/g' | sed -e 's/–/-/g' | tr -s '-' | sed -e 's/^-//' -e 's/-$//')

# attempt to find it in items, then communities, then webinars
# use --spider to just check for existence but not download the file
# output computed slug for debugging if not found
wget --no-check-certificate -q --spider https://bssw.io/items/$slug -o /dev/null || \
wget --no-check-certificate -q --spider https://bssw.io/communities/$slug -o /dev/null || \
wget --no-check-certificate -q --spider https://bssw.io/webinars/$slug -o /dev/null || \
echo "$title" Not found [$slug]
```

Put the above shell code in a file named `confirm_content.sh` and `chmod 755`. Then, run the following `find`+`xargs` command...

```
find . -name utils -prune -o -name '*.md' -exec grep -q -i 'Publish: Yes' {} \; -exec grep -m 1 '^# ' {} \; | cut -d' ' -f2- | sed -e 's/ *$//' | tr "'" "-" | xargs -L 1 ./confirm_content.sh
```

Output I get now is...

```
Instructions (DELETE THIS SECTION) Not found [instructions-delete-this-section]
Resource Template: Aggregate Base Not found [resource-template-aggregate-base]
Resource Template Not found [resource-template]
Resource Template: Aggregate Subresource Not found [resource-template-aggregate-subresource]
```

[confirm_content.sh.gz](https://github.com/betterscientificsoftware/bssw.io/files/7654411/confirm_content.sh.gz)
