### ISSUE TITLE
Document new multi-date event capability

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1158]
See example: https://raw.githubusercontent.com/betterscientificsoftware/bssw.io/preview/Events/Test-Event.md

Notes from David's email...
1.	Anything that has a date in the initial YAML-style list of event information at the top of the file is treated like a date that is exposed when the article is published
2.	The key for each date entry in the list is used to label the “kind” of date in the listing of events (second link, above).  Clara provided a bunch.  More typical might be a “Submission Deadline” and “Date”, meaning the date(s) of the event itself.
3.	Multiple distinct dates can be separated by semicolons
4.	The event listing will include *all* of the dates in the article which are in the future.  So until the Submission deadline passes you will see the same event listed for both the Submission Deadline and the (Event) Date.

**Comment by rinkug** [comment]
Need clearer description of what needs to go into documentation.

**Comment by markcmiller86** [comment]
> See example: https://raw.githubusercontent.com/betterscientificsoftware/bssw.io/preview/Events/Test-Event.md

FYI, I get `404: Not Found`

**Comment by bernhold** [comment]
Yeah, I guess I'm not surprised that it is no longer in preview.  But unfortunately, I can't seem to find it anywhere else either.  Although it *is* a version control repository, and if it was there once, we really ought to be able to find it again.  Maybe someone with better git (or github) skills than I have can find a file named Test-Event.md that must have existed ~2021-12-21.

Also, there are examples scattered throughout some of the events posted since this change was made.  So basically anything in 2022 is a *candidate* for interesting date test cases, not many will not be interesting in this context.

**Comment by rinkug** [comment]
@rinkug to take a look

**Comment by rinkug** [comment]
Some examples:

Consider for example the source event.md file contains the following:

<img width="764" alt="Screenshot 2023-12-24 at 11 25 46 PM" src="https://github.com/betterscientificsoftware/bssw.io/assets/768870/23a02f35-c227-4b18-9791-818723871311">


**When I tested above on current date of Dec 24, the event listing displays the earliest date in the file which is Jan 1st 2024 with label LOCATION-DEADLINE4. See screenshot below** 

<img width="466" alt="Screenshot 2023-12-24 at 11 27 20 PM" src="https://github.com/betterscientificsoftware/bssw.io/assets/768870/448953b1-788b-413e-ac26-eef7f4d05746">

**Comment by rinkug** [comment]
* All labels are case insensitive
* The label "event date/event dates" have special meanings. They point to the main event and are usually (but not always) displayed as the first date in the full event post. A single date will display the label name "event date" and range of dates will display the label name "event dates".
* In the full event post, the labels and dates are displayed in ascending order, _usually_. Sometimes "event date/event dates"  is displayed first.
* In event listing, only the upcoming label and date are seen.
* if same date label is specified multiple time, only the earliest one is picked, considered and displayed. The duplicates are ignored
* Any new labels where value is not a date are ignored.

--------------------
```
- event Date: Sep 21-28, 2024; 
- event example date1: June 10-12, 2024
- event example date2: June 13-14, 2024
- event example date3: June 15-16, 2024
- event example date4: June 17-18, 2024
- event example date5: June 19-20, 2024
- event example date7: June 21-22, 2024
- event example date8: June 10-24, 2024
```
I am not sure why only the below date was displayed
```
EVENT DATES: SEP 21–28, 2024
```

---------
When the above was modified to below:
```
- event Date: Sep 21-28, 2024; 
- event example date1: June 10-12, 2024
- event example date2: June 13-14, 2024
- event example date3: June 15-16, 2024
- event example date4: June 18, 2024
```

The above only displayed
```
EVENT DATES: SEP 21–28, 2024
EVENT EXAMPLE DATE4: JUN 18, 2024
```
--------------------

**Comment by rinkug** [comment]
Testing: When "event date" is mentioned twice in the source, only the earliest date is considered and displayed. The later date is ignored. The testing was done on Dec 25, 2023.

<img width="726" alt="Screenshot 2023-12-25 at 8 04 25 AM" src="https://github.com/betterscientificsoftware/bssw.io/assets/768870/65df7137-c21f-4af6-ac5b-00f63e2815a8">
<img width="759" alt="Screenshot 2023-12-25 at 8 04 30 AM" src="https://github.com/betterscientificsoftware/bssw.io/assets/768870/471582bb-64c0-450a-9c55-442995293dd6">

**Comment by rinkug** [comment]
* Display all related dates in deck section of individual events.
* Allows specifying multiple dates related to any given event.
* Allows start/end dates but also multiple semicolon-separated dates.
* Applies a date parsing library for blog posts publish dates  https://github.com/mojombo/chronic
* For date spans - the duplicate month and year in display are removed where possible. If event spans months, the month is included for each date, but year is only mentioned once. If event spans years, then both months and years for seen.
* Allows flexibility in how to label the dates. All labels are case insensitive. 
* Label names with earlier start date are considered and if there is a duplicate label name with later start date, it is ignored.
* "Event date" label has special meanings. They point to the when the main event will happen and are usually (but not always) displayed as the first date in the  individual event post. 
* Author can specify "Event date"  or "Event dates". Both are considered the same. 
* If  label "Event date/Event dates" has a single date as value, then the site  will display the label name "event date" in the event listing and individual event post. If the date is a range, then the site  will display the label name "event dates" in the event listing and individual event post.
*  In the individual event post, the labels and dates are displayed in ascending order, _usually_. Sometimes "event date/event dates"  is displayed first.
* In event listing, only the upcoming label and date are seen.
* Any new labels where value is not a date are ignored.

**Comment by rinkug** [comment]
PR #1957 was created to test the above.

**Comment by rinkug** [comment]
Documentation completed in #1956
