### ISSUE TITLE
Reconcile use of "BSSw Community" and "BSSw.io Team" as contributors

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1159]
Looking at https://bssw.io/items/authors, both of these contributors appear.  They are arguably not identical, but is it confusing to have both?  Or, looking at it another way, is it *useful* to differentiate?  Should we combine both into one label and use it consistently? (If so, "BSSw Community" seems the more general label.)

**Comment by rinkug** [comment]
@bernhold I would recommend "bssw team" so that there is accountability of who published the article. "BSSw Community" , as you said, is a more general label.

**Comment by rinkug** [comment]
As of Feb 10, we decided to use BSSw community. @karbarz : Make this change for these events: https://bssw.io/items?author=team. Check if “bssw.io” team disappears from contributors page.

**Comment by karbarz** [comment]
This has been completed with Pr #1253
