### ISSUE TITLE
Should we enable branch protection on main?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1164]
**Parent Issues:**

* #1454

## Description

GitHub now offers a branch protection mode that will require the use of a PR (as opposed to direct commits), but allows reviews to be bypassed.  We have wanted for some time to discourage direct commits, but I think the ability to bypass reviews is important too.  While we say we aspire to have everything reviewed, there are many situations where maybe that's not realistic or absolutely necessary.

Exceptional situations that I frequently experience:
* Making a small correction to a published article
* Making time-sensitive changes (i.e., getting something published quickly for particular reasons)
* Publishing generated content that's already been adequately vetted (i.e., HPC-BP and SWR events and CC articles generated by my web sites)

Does this give us functionality we want?  Should we implement it? (We can always go back if we don't like it.)

**Comment by markcmiller86** [comment]
I made the mistake of direct commits to main on a handful of occasions. So, I would welcome a branch protection here.

**Comment by bartlettroscoe** [comment]
NOTE: This has been considered before in issues like #330 and #744.

As long as there are enough people on the project that can approve PRs, there does not need to be much of a time lag.  The PR author can just post a comment or email that says "hello, can someone please approve this trivial/urgent PR so it can be merged?" and usually it will happen pretty fast.  (That is my experience with Trilinos anyway.)

Just make our life simple and require PRs be approved, except for a small subset of Git experts that may need to fix urgent issues.  (If you know Git well, it is trivial to fix the rare conflicts that may occur in a project like this.)

**Comment by markcmiller86** [comment]
> We have wanted for some time to discourage direct commits, but I think the ability to bypass reviews is important too.

I think you can set it up so `owners` can always bypass branch protection rules. So, I think we should enable them and when you need what you describe above, you can always do it.

**Comment by bartlettroscoe** [comment]
> I think you can set it up so `owners` can always bypass branch protection rules. So, I think we should enable them and when you need what you describe above, you can always do it.

That is definingly true with GitHub.

**Comment by bernhold** [comment]
In addition to master, we should also protect preview.

**Comment by bernhold** [comment]
Can we protect without enforcing specific requirements on reviews?  I think this would alleviate the worst of the problems we experience.

**Comment by bartlettroscoe** [comment]
> In addition to master, we should also protect preview. 

@bernhold, because it is possible for there to be conflicts when merging topic branches from different PRs to preview, we need to allow a subset of people with the necessary Git knowledge to directly push to 'preview' to resolve some of these conflicts.  (The other option is to force people to create conflict resolution PRs and then merge those, but that is a more complex workflow.)

**Comment by bernhold** [comment]
@bartlettroscoe I think what you're talking about will primarily affect Matt Stone and maybe to a lesser extent Clara Raubertas.  Can we tell him more specifically what might change for them and what they'll need to do about it?  If it is merely a matter of using PRs instead of pushing directly, I think it will be fine. But if there are other impacts, I think it would be good for all of us to understand them ahead of time.  Who will be allowed to merge PRs?  Matt and Clara are part of the same bssw-io-team that all of the EB members and a few others are on, and that team has maintainer access to the repo.

**Comment by bartlettroscoe** [comment]
@davidbernholdt, the goal is to allow the contractors and a select few other people to continue to directly push to 'master'  (to be renamed 'main').  So the main impact is just the change in the name of the branch 'master' to 'main'.  (And if you have an existing git clone, some people may not know how to accommodate that for both the local branch and the remote tracking branch.)

**Comment by bernhold** [comment]
@bartlettroscoe you seem to be conflating two things: changing the name of the default branch (#674) and installing protections on the default branch (this issue).  Is that necessary?  I suggest we do one at a time.  If changing the branch name means we'd have to redo the branch protections, maybe we do that one first.

But before we do the branch rename, I think we need to better understand the implications for folks with outstanding forks, especially where those forks are the source of currently active PRs.  And probably further discussion of this aspect is probably better moved to #674 .

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe you seem to be conflating two things: changing the name of the default branch (https://github.com/betterscientificsoftware/bssw.io/issues/674) and installing protections on the default branch (this issue). I

@bernhold, my bad.  (That is what happens when you don't much sleep for 3 nights in a row.)

**Comment by bartlettroscoe** [comment]
FYI: All of the Git developers that are authors of first-parent commits merged to 'master' in the last 2 years are:

```
$ git shortlog -nse --first-parent --since "2 years ago" github/master
   195  David E. Bernholdt <bernholdtde@ornl.gov>
   187  Rinku Gupta <rgupta@mcs.anl.gov>
   160  Matthew Stone <junkmail@sandboxstudio.net>
    82  Lois Curfman McInnes <curfman@mcs.anl.gov>
    35  Hai Ah Nam <hnam101@acm.org>
    33  Mark (he/his) C. Miller <miller86@llnl.gov>
    30  Clara Raubertas <clara@clararaubertas.net>
     9  Roscoe A. Bartlett <rabartl@sandia.gov>
     8  Kasia Salim <65253296+karbarz@users.noreply.github.com>
     2  miller86 <miller86@llnl.gov>
     1  Patricia Grubel <pagrubel@lanl.gov>
```

All of the direct pushers not pushing merge commits directly to 'master' on the last 2 years are:

```
$ git shortlog -nse --first-parent --no-merges --since "2 years ago" github/master
    58  Lois Curfman McInnes <curfman@mcs.anl.gov>
    32  Matthew Stone <junkmail@sandboxstudio.net>
    32  Rinku Gupta <rgupta@mcs.anl.gov>
    30  Clara Raubertas <clara@clararaubertas.net>
    24  David E. Bernholdt <bernholdtde@ornl.gov>
    22  Mark (he/his) C. Miller <miller86@llnl.gov>
    17  Hai Ah Nam <hnam101@acm.org>
     8  Kasia Salim <65253296+karbarz@users.noreply.github.com>
     2  Roscoe A. Bartlett <rabartl@sandia.gov>
     2  miller86 <miller86@llnl.gov>
     1  Patricia Grubel <pagrubel@lanl.gov>
```

So the question is, what fraction of those people really need direct push access and who could go through PRs?

For now, I will set up a team `bssw-io-direct-pushers` and put in the parallactic GitHub members:

* `32  Matthew Stone <junkmail@sandboxstudio.net>`: @sbxchicago
* `30  Clara Raubertas <clara@clararaubertas.net>`: @clararaubertas

They should be able to directly push 'master' still.

**Comment by bartlettroscoe** [comment]
I have enabled "Require a pull request before merging" for the 'master' branch but I did **not** check "Require approvals".  And with that, I can see that I can still merge the open PR #1781 without and approved review showing:

----

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/5d47c34f-f4ff-4cc8-b08a-076f85d3f040)

----

However, it is still allowing direct pushes:

```
[bartl@BartlettLeno23 bssw.io (master)]$ git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 459 bytes | 459.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: Bypassed rule violations for refs/heads/master:
remote: 
remote: - Changes must be made through a pull request.
remote: 
To github.com:betterscientificsoftware/bssw.io.git
   a8effb7e..77d6a090  master -> master
```

I think I need to turn on requiring reviewers to stop this from happening.

**Comment by markcmiller86** [comment]
I certainly don't *need* it. I think I found it convenient in a handful of situations where something needed to change on the live site somewhat quickly.

**Comment by bartlettroscoe** [comment]
Darn, I set "Require approvals" and it still allows me to direct push to 'master':

```
[bartl@BartlettLeno23 bssw.io (master)]$ git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 421 bytes | 421.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: Bypassed rule violations for refs/heads/master:
remote: 
remote: - Changes must be made through a pull request.
remote: 
To github.com:betterscientificsoftware/bssw.io.git
   77d6a090..d02d8ebf  master -> master
```

Let me do some research and see how to stop this from happening.

**Comment by markcmiller86** [comment]
Yeah, I think thats true for anyone who is an *owner*...I think

**Comment by bartlettroscoe** [comment]
I have set the option "Do not allow bypassing the above settings".  Trying this again:

```
[bartl@BartlettLeno23 bssw.io (master)]$ git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 418 bytes | 418.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request.
To github.com:betterscientificsoftware/bssw.io.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:betterscientificsoftware/bssw.io.git'
```

Bingo, that did it!

Now let me unset the option "Require approvals" and try again:

```
$ git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 418 bytes | 418.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request.
To github.com:betterscientificsoftware/bssw.io.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:betterscientificsoftware/bssw.io.git'
```

Bingo!

So the min options needed to stop direct pushes to 'master' are:

* [x] Require a pull request before merging
* [x] Do not allow bypassing the above settings

and with this, I can still merge my own PR without approvals as shown in PR #1781 showing:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/b570c4bd-177f-42f0-b268-acb1d815db89)

Next, I need to figure out how to allow direct pushes from a group of GitHub members (i.e. the parallatic developers).

**Comment by bartlettroscoe** [comment]
I tried creating the new team [bssw-io-direct-pushers](https://github.com/orgs/betterscientificsoftware/teams/bssw-io-direct-pushers).  But for some reason, the 'master' branch protection page:

* https://github.com/betterscientificsoftware/bssw.io/settings/branch_protection_rules/19973535

will not let me select that team under the option "Allow specified actors to bypass required pull requests".  But it will met me select the teams and people:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/563c3b99-608f-4aa1-bcca-8354e2632ca0)

I don't see how I can even maintain those teams?

I wonder if my GitHub account in this project is lacking the correct permissions to create such a team?

I am noticing that from the page https://github.com/betterscientificsoftware at the top it shows "Teams 8":

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/6e725d12-eac1-41df-995b-354c4804a5ca)

But when I click on "Teams" it goes to:

* https://github.com/orgs/betterscientificsoftware/teams

which only shows 3 teams:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/aebfb6c5-c4c9-41fe-9f4f-52824a135e40)

Where is the other 5 teams?  Why can't I see them?

**Comment by bartlettroscoe** [comment]
Currently, I don't think the Parallatic developers:

* `32  Matthew Stone <junkmail@sandboxstudio.net>`: @sbxchicago
* `30  Clara Raubertas <clara@clararaubertas.net>`: @clararaubertas

will be able to direct push to 'master' until we can figure out how to create a team that includes just them that can be added to the option "Allow specified actors to bypass required pull requests".

I will need to do some more research on that to see what the issue might be.

SIDENOTE: GitHub keeps changing their settings so when I get it figured out, it changes and I need to figure it out all over again  😊

**Comment by bernhold** [comment]
Hi @bartlettroscoe,

I'm a little surprised you were able to create a team of your own -- I thought that was limited to org owners.

I have always found the GH Teams interface poorly designed and counter-intuitive.  The other teams are nested under bssw-io-team.  There are two ways to see them.  
* One is in the top level list of teams.  Notice that there's a pull-down control next to "5 teams" in the able.  Click on it.
* The other is to click into bssw-io-teams and then click on "Teams 5" in the upper left.

If you let me know who you think should be in the team, I can help make it underneath bssw-io-team (if you need help -- it does seem like Mark was able to create a team there -- now removed).

**Comment by bartlettroscoe** [comment]
> If you let me know who you think should be in the team, I can help make it underneath bssw-io-team (if you need help -- it does seem like Mark was able to create a team there -- now removed).

@bernhold, initially, it should just be the Parallatic developers:

* `32  Matthew Stone <junkmail@sandboxstudio.net>`: @sbxchicago
* `30  Clara Raubertas <clara@clararaubertas.net>`: @clararaubertas

That is who is currently in the team:

* https://github.com/orgs/betterscientificsoftware/teams/bssw-io-direct-pushers

**Comment by bernhold** [comment]
Hi @bartlettroscoe I've created bssw-direct-pushers (note: no -io) as a child of bssw-io-team.

As I understand it, those who have the maintainers role on bssw-io-team (Rinku, Lois, Mike, me) should be able to manage all of the child teams too.  If we need to add you as a maintainer there, let me know.  Or ask any of the four of us for changes.

**Comment by bartlettroscoe** [comment]
@bernhold, I don't seem to be able to see the new team at any of the following locations:

* https://github.com/orgs/betterscientificsoftware/teams
* https://github.com/betterscientificsoftware/bssw.io/settings/access

Where can one see these hidden/private teams?

**Comment by bernhold** [comment]
@bartlettroscoe no idea what's going on.  I checked and every one of those teams is marked as visible.  I just added you at the top level (bssw-io-team) as a maintainer.  Hopefully that will give you visibility into everything.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe no idea what's going on. I checked and every one of those teams is marked as visible. I just added you at the top level (bssw-io-team) as a maintainer. Hopefully that will give you visibility into everything.

@bernhold, with adding me as a maintainer, I was able to add the team bssw-direct-pushers to the option "Allow specified actors to bypass required pull requests" for the 'master' branch as shown by:

![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/4cb9fab8-b913-408f-b815-97514a1a11a3)

Hopefully now the Parallatic developers listed in the team [bssw-io-direct-pushers](https://github.com/orgs/betterscientificsoftware/teams/bssw-io-direct-pushers) can now directly push to 'master'.

**Comment by rinkug** [comment]
@bartlettroscoe : Can we close this?

**Comment by bartlettroscoe** [comment]
I think this can be closed.  If there was a problem with this, we would have heard about it by now.
