### ISSUE TITLE
Preview branch: stacked PR issue

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1234]
Test case:
1.  I have PR #1225, which is a curated content and a PR created in bssw.io repo itself. As of monday, Jan 24, 10:30AM PT, it has preview label and metadata is publish:yes. All checks have passed.
2. I have a PR #1233 which is a follow-on to PR #1225 with editorial changes.  As of monday, Jan 24, 10:30AM PT, it has preview label and metadata is publish:yes. All checks have passed.
3. I rebuild preview website and see PR #1225 article but I dont see edits of PR #1233.

Debug:
CaseA:
1. Merged #1225 in master
2. Rebuilt review to  check if #1233 shows up on preview.
3. PR #1223 does not show up. 

CaseB:
1. Merged #1225 in master
2.Removed preview label from #1233. Re-added preview label to PR #1223. All checks passed
3. Rebuilt preview website and PR #1223 DOES show up.

**Comment by bartlettroscoe** [comment]
@rinkug, is the claim:

> 3. I rebuild preview website and see PR #1225 article but I dont see edits of PR #1233.

that the branch associated with PR #1233 which is https://github.com/betterscientificsoftware/bssw.io/tree/karbarz-ReproducibilityCC is (which no longer exists but it had the top commit https://github.com/betterscientificsoftware/bssw.io/pull/1233/commits/672186e187f3a371b7f217e1eb10a32bfdb7339d) not in the 'preview' branch?  My analysis below shows that it is and 'preview' is up-to-date with 'master'.  All seems okay.

<details>

<summary><b>Detailed Git Analysis</b> (click to expand)</summary>

.

One can see that 'preview' is currently up-to-date with 'master' as shown by:

```
$ cd bssw.io/

$ git remote -v | grep ^github
github  git@github.com:betterscientificsoftware/bssw.io.git (fetch)
github  git@github.com:betterscientificsoftware/bssw.io.git (push)

$ git fetch github

$ git log-short --name-status -1 github/master 
700a2615 "Merge pull request #1233 from betterscientificsoftware/karbarz-ReproducibilityCC"
Author: Rinku Gupta <rgupta@mcs.anl.gov>
Date:   Mon Jan 24 11:00:02 2022 -0800 (35 minutes ago)

$ git log-short --name-status -1 github/preview 
47587e9b "Merge 5a7c71ae58ab577db1015449ec3cd4fad5c60695 into preview"
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Mon Jan 24 19:10:24 2022 +0000 (24 minutes ago)

$ git log --oneline github/master --not github/preview
[empty]
```

The above git log command shows that there are no commits in the 'github/master' branch that are not also on the 'github/preview' branch.

You can check that commit 672186e187f3a371b7f217e1eb10a32bfdb7339d from PR #1233 is on 'preview' as:

```
$ cd bssw.io/

$ git fetch github

$ git log --oneline 672186e187f3a371b7f217e1eb10a32bfdb7339d --not github/preview
[empty]
```

You can also verify this visually by running:

```
$ git log --oneline --name-status --graph github/preview
*   47587e9b (HEAD -> preview, github/preview) Merge 5a7c71ae58ab577db1015449ec3cd4fad5c60695 into preview
|\  
| * 5a7c71ae Update publish date, grammar
| | M   CuratedContent/WhatEveryComputerScientistShouldKnowAboutFloatingPointArithmetic.md
* |   4ad8d5af Merge refs/heads/master into preview
|\ \  
| * \   700a2615 (github/master, github/HEAD) Merge pull request #1233 from betterscientificsoftware/karbarz-ReproducibilityCC
| |\ \  
* | \ \   218441eb Merge 672186e187f3a371b7f217e1eb10a32bfdb7339d into preview
|\ \ \ \  
| | |/ /  
| |/| |   
| * | | 672186e1 Update TenYearReproducibilityChallenge.md
| | | | M       CuratedContent/TenYearReproducibilityChallenge.md
* | | |   6618a619 Merge refs/heads/master into preview
```

What is strange about this history is that there are two merge commits 218441eb and 4ad8d5af (through 700a2615) that merge in this commit 672186e187f3a371b7f217e1eb10a32bfdb7339d  which I don't really understand how that happened.

If we look at the commit 672186e187f3a371b7f217e1eb10a32bfdb7339d  we see it just changed the one file:

```
$ git log-short --name-status -1 672186e1
672186e1 "Update TenYearReproducibilityChallenge.md"
Author: Kasia Salim <65253296+karbarz@users.noreply.github.com>
Date:   Thu Jan 20 13:58:53 2022 -0600 (4 days ago)

M       CuratedContent/TenYearReproducibilityChallenge.md
```

If we then diff that file between the that commit and the tip of 'preview', we see:

```
$ git log-short --name-status -1 github/preview 
47587e9b "Merge 5a7c71ae58ab577db1015449ec3cd4fad5c60695 into preview"
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   Mon Jan 24 19:10:24 2022 +0000 (21 minutes ago)

$  git diff --name-status 672186e1 --not github/preview -- CuratedContent/TenYearReproducibilityChallenge.md
[empty]
```

That shows the version of the file `CuratedContent/TenYearReproducibilityChallenge.md` in commit 672186e1 is currently exactly what is being represented on the 'preview' branch and therefore should be displayed on the preview.bssw.io site.

</details>

**Comment by rinkug** [comment]
@bartlettroscoe: I eventually had to merge the original PR into master before I could see the updated PR.

The problem was that when we have 2 PRs in preview branch and one of the PRs is updating the other, only the original is visible on preview website.

**Comment by bartlettroscoe** [comment]
> The problem was that when we have 2 PRs in preview branch and one of the PRs is updating the other, only the original is visible on preview website.

@rinkug, there are tricks you can play with PRs if you just want to view the follow-on PR before the upstream PR is merged.  It depends on what you are trying to achieve but this setup should have all the dials you need to get things done (without needing to merge to 'master' before the work is completely 100% ready to publish).

**Comment by bartlettroscoe** [comment]
@rinkug, can we close this?

**Comment by rinkug** [comment]
This issue of stacked PRs are rare. So, we have not decided to not pursue with a solution targeting preview branch for this issue, for now. We are closing this issue.
