### ISSUE TITLE
Review Personal Productivity and Sustainability subtopic under Skills

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#1248]
We ought to review items in the [Personal Productivity and Sustainability](https://bssw.io/items?topic=personal-productivity-and-sustainability) topic. This was created as a catch-all bin.

It includes stuff that might have originated as having focused use in software but also found use outside of software for more general personal productivity. Example is Personal Kanban. Kanban originated as productivity tool for managing work on software but it can be applied to manage one's daily schedule of activity as well.

But, this subtopic also includes [RSE in HPC](https://bssw.io/events/research-software-engineers-in-hpc-workshop-rse-hpc-2020) as well.

That said, we do need some kind of a *catch-all* to handle anything we have that doesn't fall into one of the existing categores. For example, where should the articles on the Apollo Guidance Computer go?

As an aside, they are all currently under [*Better Performance*](https://bssw.io/items?category=better-performance) whereas the first might have rightly been under *Better Reliability*, the second under *Better Development* and the third (which is all about experiences in actual *use* of the AGC)...I am not sure where that would fit best. In fact, where do we have space for *user* type content, the user's experience, providing good user support, managing constrained resources whilest providing user support, etc.

**Comment by bernhold** [comment]
Maybe instead we should think about expanding the list of topics under Better Skills?

This needs more consideration.

**Comment by rinkug** [comment]
@rinkug  will take a look at the articles under [Personal Productivity and Sustainability](https://bssw.io/items?topic=personal-productivity-and-sustainability)
