### ISSUE TITLE
CC: CMake tutorial and reference resources

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#1259]
I my recent work with a major CMake refactoring effort, I have found the book "Professional CMake":

* https://crascit.com/professional-cmake/

to be incredibly valuable.  I highlighted this book in my SIAM PP22 talk last week:

* https://doi.org/10.6084/m9.figshare.19241715

From slide 5:

* Self-published book:
  * https://crascit.com/professional-cmake/
  * Downloadable PDF
  * 500+ pages
  * Publishes new edition with every major release of CMake (currently 11th edition covering CMake 3.22)
  * Cost: $30 (which includes 10 future editions)
* Covers:
  * Basic CMake features in great detail
  * Modern CMake idioms and best practices
  * Tips and critical behavior (sometimes) missing in official CMake reference documentation.
  * Practices to avoid and why

**Fills a critical gap in CMake tutorial and “why” documentation**

Anyone doing anything with CMake should own this book.

Also, we are pretty thin on [CMake material on bssw.io](https://bssw.io/items/search?search_string=cmake) and ECP surveys have listed CMake help at the top of the list for the last few years.

**Comment by bartlettroscoe** [comment]
@betterscientificsoftware/bssw-editorial-board, can I get some up-votes for this? 

I wish there was a free alternative to this book but there just is not.  Kitware put their book "Mastering CMake" online for free:

* https://cmake.org/cmake/help/book/mastering-cmake/

but it is just not in the same league as "Professional CMake", IMHO.

**Comment by bernhold** [comment]
@bartlettroscoe I advise you to just go ahead.  CC for CMake resources is clearly in scope.

I wonder if it could/should be a single article with a *collection* of resources for CMake (as we have a collection of inclusive language resources)?  Anything that you think is worth recommending.  I know they've done an ECP tutorial or two.  Are the recordings for those available? (Or other people's tutorials), etc.

**Comment by bartlettroscoe** [comment]
> I wonder if it could/should be a single article with a collection of resources for CMake (as we have a collection of inclusive language resources)?

@bernhold, perhaps, but for me, the only two main sources for CMake documentation worth directly consulting and searching are:

* The book "Professional CMake"
* The online CMake reference documentation for your minimum version of CMake (i.e.  https://cmake.org/cmake/help/v3.17/ for TriBITS and Trilinos currently)

and to consult those in that order. For example, I have found several really important details about using CMake in the book "Professional CMake" that are not even mentioned in the detailed online CMake reference documentation.  (But as I find cases like this I ask Kitware fix them.)

And if you can't find what you need to know in those two collections, then:

* Do Google searches for specific topics and error messages and hope you get lucky that someone has covered this somewhere (but take what you find with a grain of salt unless it is an explanation from Brad King).

We could/should also mention Kitware's online CMake book:

* https://cmake.org/cmake/help/book/mastering-cmake

and we should say that it may also be useful if one can't find the topic covered in "Professional CMake".

> I know they've done an ECP tutorial or two. Are the recordings for those available? (Or other people's tutorials), etc.

For this CC article, I would stick with written documentation and not presentations.  (You can find a bunch of presentations for CMake online if you look and the ones by non-Kitware people are likely just as good.)

Actually, I think the above comments is just about the extent of CC article.

**Comment by bartlettroscoe** [comment]
@betterscientificsoftware/bssw-editorial-board 

FYI: I should have a PR for this by next week so it can go out in the March 2022 digest.

**Comment by bartlettroscoe** [comment]
@bernhold or one of the @betterscientificsoftware/bssw-editorial-board members,

Can you please sign up to be the EB board member for PR #1276 for this CC article?

**Comment by bartlettroscoe** [comment]
This was completed with the publishing of PR #1276
