### ISSUE TITLE
Update and transtion "Git Tutorial and Reference Collection" to bssw.io site article

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#1283]
@betterscientificsoftware/bssw-editorial-board,

I would like to upgrade and transition the "Git Tutorial and Reference Collection" page that I wrote years ago for the old IDEAS project at:

* https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/

to an original article on bssw.io.  Some of the links are stale and this really should be on bssw.io.

NOTE: I already transitioned the "Critical Beginner Git Usage Tips" page:

* http://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/beginner-tips/

to

* https://bssw.io/items/critical-beginner-git-usage-tips

that is linked to on that the  ["Git Tutorial and Reference Collection" page](https://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/) so this is just finishing that off.

**Comment by bartlettroscoe** [comment]
NOTE: I am giving an internal talk at SNL on Git Workflows on April 26, 2022 and I would like to have this article completed and published to bssw.io so I can reference it in my presentation.

Any objections?

**Comment by bartlettroscoe** [comment]
Note, this is related to #560.

**Comment by pagrubel** [comment]
Sounds like a great suggestion. I moved this out of backlog

**Comment by bartlettroscoe** [comment]
I posted PR #1296.
