### ISSUE TITLE
Document house style preferences for interview-format blog articles

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1293]
Based on David's discussions with Matt.

For articles in which the whole piece is an interview...
* Use **bold** to mark up question and answer markers
* Where reasonable, consider structuring the piece as if "BSSw" were doing the interview instead of a named individual
  - This eliminates the need to name a contributor who's identity isn't really relevant
  - Reduces the number of names for readers to keep track of
* For questions use **Question:** or **Full Name:** initially, then **Q:** or **Firstname:** following
* Use **Full Name:** initially, then **Firstname:** following

Alternative guidelines for articles in which there is an interview component within a larger piece (for example <https://bssw.io/blog_posts/experiences-replacing-master-slave-terminology-in-ale3d-and-sierra>)
* Use *italics* to mark up question and answer markers

**Comment by bernhold** [comment]
This is one that maintains the interviewer's name throughout: https://bssw.io/blog_posts/working-remotely-the-spack-team

We could revisit it if we want to. But to me there is neither necessity nor urgency.

**Comment by rinkug** [comment]
Does this have to be a part of EB docs?

**Comment by rinkug** [comment]
Done
