### ISSUE TITLE
Fellowship redirect

### ISSUE THREAD

**Issue by gonsie** [betterscientificsoftware/bssw.io#1294]
Would it be possible to get a top-level redirect of `https://bssw.io/fellowship` to the current fellowship page `https://bssw.io/pages/bssw-fellowship-program`? Similar to the `bssw.io/psip` redirect.

Thanks!

**Comment by bernhold** [comment]
This should be doable.  Right now such things are one-off requests that require our front-end developers to implement.  We're supposed to be defining a specification that will allow us to manage them from the "content side" of the system.  

Is there are target date/event for which you'd like to have this in place?

**Comment by rinkug** [comment]
@bernhold  and @gonsie : Looks like the content https://bssw.io/fellowship  and  https://bssw.io/pages/bssw-fellowship-program is the same? Are the different pages with same content? If yes, then we can eliminate duplication and redirect.

**Comment by rinkug** [comment]
This particular issue is close but the overall behaviour is captured in issue #704
