### ISSUE TITLE
https://scicodes.net/

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1299]
https://scicodes.net/

The SciCodes Consortium is for editors and maintainers of academic discipline and institutional software registries and repositories. 

This should be under software publication and perhaps other topics.

**Comment by bernhold** [comment]
We now have a blog article on this: https://bssw.io/blog_posts/the-scicodes-consortium-coordinating-research-software-registries-and-repositories

Does that obviate the interest in a CC?  Opinions sought.

**Comment by markcmiller86** [comment]
I had to look up what `obviate` means. I thought I knew but given your usage, it was `obv`ious I didn't 😉.

Yes, I agree. We don't need a CC now too. Is it bad form to CC our own content 😆

**Comment by rinkug** [comment]
Closing this issue since we have a blog on this topic.
