### ISSUE TITLE
Should the monthly digest highlight recurring events?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1303]
Now that we have the ability to specify a series of dates for an event, we have several articles for events that take place on a regular monthly cadence, but they don't provide any detail about each month's events, e.g., 
* https://bssw.io/events/leadership-scientific-software-town-hall-meetings-series
* https://bssw.io/events/webinar-best-practices-for-computational-and-data-intensive-cdi-research-series

(These are distinct from the HPC-BP webinar events, for example, which are unique to each month.)

The question is whether such "simple" recurring events should be highlighted each month in the digest?  And if so, what form should that highlight take?

The current norm is that each event gets a short section that includes title, date, location, one-sentence description, and a link.

To me there seem to be three basic options for simple recurring events:
1. treat them like any other event, every month
2. include them only when something changes about the event (i.e. schedule)
3. create a sub-section for "Recurring Events" with a one-line listing of title (with link) and date.  Heading is open to discussion.

**Comment by rinkug** [comment]
Publishing the events: some background
- Currently we dont have an automatic way to specify recurring events in the md fil, at this at this moment.
- Currently, we can do this by putting a list of dates in the event (ex: LSSw) in the md file  and run it for a finite amount of time. 

Now coming to this actual github issue, should these events be a part of BSSw digest periodically/should we highlight recurring events?
- Right now, we notice that we don't have too many recurring events. Some recurring events are: NSF Cyberinfrastuctre folks have something similar to ideas webinars, LSSw series.
- We  decided today that we can continue highlighting these recurring events **until end of 2023**. And then we will revisit. So we go with the option1, that david proposed in the original issue.

ACTION for all of us: Revisit this at the start of 2024.

**Comment by rinkug** [comment]
I think we judge and decide if we want to highlight a recurring event in that month. If we have enough new events, then we dont highlight. If we dont, then lets highlight. We have operated well without having a stringent rule in place. I vote for closing this in favor of decluttering the board

**Comment by rinkug** [comment]
If we get too many recurring events, we will discuss this. For now, editor's judgement is fine.
