### ISSUE TITLE
Use of heading levels in content is surprising

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1327]
Since its inception, the site has had norms for the use of headings of different levels within articles which I think are hard to remember (I have problems with this), quirky and hard to remember (I have problems with this too), and inexplicable.

Can we move to a model that uses the heading levels in strict hierarchy?  H1 for the title, H2 for the main headings of the article, H3 next, etc., with the expectation that levels won't be skipped. (We still need to have conventions for things like Contributed by, but it seems logical that they should be H2, rather than H4 as they are now.)

Unfortunately, this would be extraordinarily disruptive, in that either all existing content would have to change, or we'd have to implement multiple versions of the styles and provide a clear way within the document of designating which style is appropriate.  The latter approach *might* be coupled with moving metadata from HTML comment format to YAML format (#1318).  In other words, any article with YAML metadata would use the new heading rules and the associated style files.

**Comment by bartlettroscoe** [comment]
I think you could write a Python script to update the existing articles

**Comment by rinkug** [comment]
> I think you could write a Python script to update the existing articles

Two tasks based on discussion today.

1.  check with vendor on how is tied to aesthetics
2.  How to update and verify our articles easily

**Comment by bartlettroscoe** [comment]
FYI: I think we are seeing this problem in https://github.com/betterscientificsoftware/bssw.io/pull/1367#issuecomment-1169797762.

**Comment by rinkug** [comment]
We are closing this as it is not high on priority list
