### ISSUE TITLE
Numerical recipe books on line

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#1340]
http://numerical.recipes/oldverswitcher.html

**Comment by bernhold** [comment]
Hmmm, I'm of two minds about this as CC material.  With the caveat that I haven't looked at the new (2007) C++ book, I think it would be safe to say that the earlier books in the series were widely viewed as both the most useful and the most harmful books for developers in their day. The algorithms were often simplistic, and as time goes on, less and less likely to be what you'd actually want to implement on today's hardware. And the code that came with them was almost certainly the most widely pirated code in scientific software, back in the day.  Even now, it doesn't look like they've opened up the code.

**Comment by markcmiller86** [comment]
> it would be safe to say that the earlier books in the series were widely viewed as both the most useful and the most harmful books for developers in their day.

Is this *two-truths* perspective somehow unique to this material? I don't think so. I think the same can be said of a great number of resources and practices.

> as time goes on, less and less likely to be what you'd actually want to implement on today's hardware.

Isn't this material good *introductory* material for people just learning about numerical algorithms?

> And the code that came with them was almost certainly the most widely pirated code in scientific software, back in the day. Even now, it doesn't look like they've opened up the code.

😕

**Comment by markcmiller86** [comment]
So, I would like to resurrect this issue. I got some confused faces on it and I honestly do not know why.

> Hmmm, I'm of two minds about this as CC material. With the caveat that I haven't looked at the new (2007) C++ book, I think it would be safe to say that the earlier books in the series were widely viewed as both the most useful and the most harmful books for developers in their day.

Harmful...how? I used material I learned from it with great success in my [Master's thesis](https://babel.hathitrust.org/cgi/pt?id=uc1.x33493&seq=9)

> The algorithms were often simplistic, and as time goes on, less and less likely to be what you'd actually want to implement on today's hardware.

Speaking as one who often develops "simplistic" material (e.g. hello-numerical-world), especially for the purposes of introducing others to new concepts in the discipline, I am bemused why we would cite simplicity as a criteria for declining to curate. 

> And the code that came with them was almost certainly the most widely pirated code in scientific software

Hmnmm...wide pirating is a) not really our concern or b) an acknowledgement that the code was found to be highly useful.

> back in the day. Even now, it doesn't look like they've opened up the code.

The article would be about the books, not the code.

**Comment by markcmiller86** [comment]
I am happy to do this one for November.
