### ISSUE TITLE
Have back-end create a "content inventory" page with sortable columns

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#1346]
@bartlettroscoe suggested this in meeting yesterday and it would potential work as a nice fallback if other things fail or don't work very well.

We should have the back-end generate a content inventory which would simply be a very long table with sortable columns like so...

**content title** | **publication date** | **author(s)** | **topics** | **other metadata** |
 :--- | :--- | :--- | :--- | :---
My worst bug | Jan 1, 1970 | Mark C. Miller | Productivity
CTR: What is it? | Jan 1, 2020 | David Rogers | Best practices
Why CMake Rocks | Apr 1, 2022 | Ross Bartlet | Tools

By making the table sortable on columns, it should be somewhat easy to find things...this is a stopgap against any issues with search. But, it could be useful for other things too.

**Comment by bernhold** [comment]
I don't know about search issues (sorry, I had to take a call which took far longer than expected).   But there are other reasons why I think it might be useful to be able to access data like this from time to time.  For example, looking at the distribution of content across topics to check for topics that may be worth a particular effort to fortify.  Also, having a way to identify articles with publish=no (I have occasionally screwed up in this way, and thought it was a bug in the front-end or in my content and wasted people's time raising alarms. Also, it is worth keeping an eye on what's out there with publish=no and why.  Maybe we should just completely remove it.)

What if this were available as a CSV file which could be downloaded from the rebuild page?  Then you could use Excel or your other favorite tools to explore/analyze.  We could even script things like the topic analysis I mentioned.

**Comment by markcmiller86** [comment]
> What if this were available as a CSV file which could be downloaded from the rebuild page?

That works. I think there is web infrastructure that could be included on the site to render the csv as a page on the live site in some place convenient too. But, the CSV alone would be just fine too.

**Comment by bartlettroscoe** [comment]
What is really useful is to allow multi-column search where you old down the "Shift" key and click the column headers.  You can see this with CDash, for example, [here](https://testing.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2022-05-19&filtercount=10&showfilters=1&filtercombine=and&field1=groupname&compare1=62&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-&field3=status&compare3=62&value3=passed&field4=testoutput&compare4=94&value4=Error%20initializing%20RM%20connection.%20Exiting&field5=testoutput&compare5=96&value5=srun%3A%20error%3A%20s_p_parse_file%3A%20unable%20to%20read%20.%2Fetc%2Fslurm%2Fslurm.conf.%3A%20Permission%20denied&field6=testoutput&compare6=96&value6=cudaGetDeviceCount.*cudaErrorUnknown.*unknown%20error.*Kokkos_Cuda_Instance.cpp&field7=testoutput&compare7=96&value7=cudaMallocManaged.*cudaErrorUnknown.*unknown%20error.*Sacado_DynamicArrayTraits.hpp&field8=testoutput&compare8=96&value8=srun%3A%20error.*launch%20failed%3A%20Error%20configuring%20interconnect&field9=testoutput&compare9=94&value9=An%20ORTE%20daemon%20has%20unexpectedly%20failed%20after%20launch&field10=testoutput&compare10=94&value10=It%20looks%20like%20orte_init%20failed%20for%20some%20reason%3B%20your%20parallel%20process%20is).  If you hold down "Shift" and click "Test Name" and then "Build Name" on that page, you will see:

![image](https://user-images.githubusercontent.com/1959736/169591265-1ad4a0d1-5388-41d4-8c97-0fea48972eea.png)

I use that feature all the time with CDash to help see associations in the data.

**Comment by bernhold** [comment]
I don't want to rehash a whole conversation, but what's the use case of this table in the context of *search*?

**Comment by markcmiller86** [comment]
> I don't want to rehash a whole conversation, but what's the use case of this table in the context of _search_?

I don't think it is so much about general *search* per-se. Its more about providing a way for someone like @rinkug to easily and reliably find things she needs in her routine workflows. But, a sufficientialy constructed google search (with sort params as well) URL I have high confidence will address @rinkug's needs as well.

**Comment by markcmiller86** [comment]
BTW...the upshot of the search discussion is that @bartlettroscoe and I (and @pagrubel if she is still interested) will research and create some  example URLs of searching (and sorting results) bssw.io using google and use that as a starting point to help decide if we really need to ask our backend developer team to invest a lot of effort in some custom search features for the site.

**Comment by bernhold** [comment]
I'd really like to *discourage* that approach.  While google search may be very effective, as I understand it, there is no chance to filter or in any way control the results returned when used in this way.  Our colleagues at Sandbox and Parallactic have advised against going in this direction.

It would be much more useful to figure out the specs for how we want search to work and let Sandbox and Parallactic implement it.

**Comment by bartlettroscoe** [comment]
> Our colleagues at Sandbox and Parallactic have advised against going in this direction.

Then I would just suggest that we remove the search feature from bssw.io and just them a sortable table of articles (as per this issue).  If anyone asks about search, tell them to use their favorite search engine with `site:bssw.io`.

**Comment by markcmiller86** [comment]
> I'd really like to _discourage_ that approach.

I feel entirely the opposite. I don't see value in expending my time or others in reinventing the wheel here. Who could know more about search than something like Google?

I am interested in [learning enough about google search and its customization](https://support.google.com/programmable-search/answer/4513751?hl=en&ref_topic=4513742) that we could a) demonstrate how we can make it work and b) inform our web backend team on most fruitful directions but otherwise save a lot of time and expense.

Sans that, I am far less interested in this topic.

**Comment by rinkug** [comment]
> @bartlettroscoe suggested this in meeting yesterday and it would potential work as a nice fallback if other things fail or don't work very well.
> 
> We should have the back-end generate a content inventory which would simply be a very long table with sortable columns like so...
> 
> **content title**	**publication date**	**author(s)**	**topics**	**other metadata**
> My worst bug	Jan 1, 1970	Mark C. Miller	Productivity	
> CTR: What is it?	Jan 1, 2020	David Rogers	Best practices	
> Why CMake Rocks	Apr 1, 2022	Ross Bartlet	Tools	
> By making the table sortable on columns, it should be somewhat easy to find things...this is a stopgap against any issues with search. But, it could be useful for other things too.

I dont think we want a search table output. We just want readers to be able to use searchbox and get the result they want, sort the results (we need to narrow down the criteria/options we want to provide to the reader for this) or filter results (we need to narrow down the criteria/options we want to provide to the reader for this) and do all this within the visual aesthetics of the site.

**Comment by rinkug** [comment]
>  don't think it is so much about general _search_ per-se. Its more about providing a way for someone like @rinkug to easily and reliably find things she needs in her routine workflows. But, a sufficientialy constructed google search (with sort params as well) URL I have high confidence will address @rinkug's needs as well.

My apologies if my communication was misconstrued yesterday.  We are dealing with this topic for general search experience for the end reader and not the bssw.io/ideas team.

**Comment by markcmiller86** [comment]
> this is a stopgap against any issues with search.

Ok, apologies...I think my remark above is misleading. I was thinking in the context of bssw-editorial activities and not users/site-visiters. And, this issue was submitted as a wholly orthogonal one to search which can have various uses (for editors) so I wanted to capture it in an issue ticket.

That said, if such a page existed, it would address the one search example @rinkug repeats in conversations about search...it would be nice to get a list of the most recent articles.

**Comment by bernhold** [comment]
> it would be nice to get a list of the most recent articles.

Actually, I think it would be nice if the main site could return search results in order of publication.  I don't know if that would satisfy Mark's use case, but I think any regular visitor to the site would find a "what's new" view very useful.

But then this issue is not about search per se, and there's probably another issue where this point should be added (and maybe I've already found it and done it in a past life).  Oh yeah, looks like it is #1094 .  And also #996. And #446.

**Comment by bartlettroscoe** [comment]
Note, most of this discussion should have likely been done in #996.

**Comment by bartlettroscoe** [comment]
CC: @rinkug 

We skipped over this because @markcmiller86 and @davidbernholdt were not at the operations meeting today.

**Comment by markcmiller86** [comment]
FYI...I asked ChatGPT...

```
I would like to write some liquid code to list all markdown files in a directory tree and output
a table with sortable columns such as title, date added, content type.
```

and it produced...

```
Sure, here is an example of how you can use Liquid to list all Markdown files in a directory tree and output a table with sortable columns:

```
{% assign markdown_files = "" | split: "" %}
{% assign sort_by = "title" %}

{% comment %}
    Get all Markdown files in the directory tree
{% endcomment %}
{% assign source_dir = "/path/to/directory" %}
{% assign markdown_files = site.pages | where: "path", "/path/to/directory/" | where: "extname", ".md" %}

{% comment %}
    Sort the Markdown files by the chosen column
{% endcomment %}
{% assign sorted_files = markdown_files | sort: sort_by %}

{% comment %}
    Output the table with sortable columns
{% endcomment %}
<table>
  <thead>
    <tr>
      <th><a href="?sort_by=title">Title</a></th>
      <th><a href="?sort_by=date_added">Date Added</a></th>
      <th><a href="?sort_by=content_type">Content Type</a></th>
    </tr>
  </thead>
  <tbody>
    {% for file in sorted_files %}
    <tr>
      <td>{{ file.title }}</td>
      <td>{{ file.date | date: "%Y-%m-%d" }}</td>
      <td>{{ file.content_type }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
```

In this example, we first create an empty array called `markdown_files`.
We also define a `sort_by` variable to indicate the initial column to sort by.
We then get all Markdown files in the directory tree by using the `site.pages`
variable and filtering it to only include files in the specified directory and with a `.md` extension.

We then sort the Markdown files by the chosen column, using the `sort` filter.
Finally, we output a table with sortable columns, using the `thead` and `tbody`
tags to structure the table. The column headers are links that can be clicked
to change the sorting column, and the rows are populated with the data from
the sorted Markdown files.

Note that this example assumes that you are using Liquid within a web framework or CMS
that provides access to the `site.pages` variable. If you are using Liquid in a different
context, you may need to modify this example to access the Markdown files in a different way.
```

**Comment by markcmiller86** [comment]
The above code could be added (I think with just a bit of modification) to our Jekyll bssw-docs site pages I think pretty easily.

**Comment by markcmiller86** [comment]
Ok, one issue with the code is that it assumes every `.md` file has frontmatter variables defining the title, date and content type of the file. We don't have that. What we have is content type in directories with associated names (e.g. *events* in the `Event` folder, *blogs* in the `Articles/Blog` folder, etc.) and date is in XML comment metadata *in* the files. So, there is some more work to get this to work.

**Comment by rinkug** [comment]
We dont have the resources for it. And we probably dont have a great need for it now anyways
