### ISSUE TITLE
Event Notice

### ISSUE THREAD

**Issue by cferenba** [betterscientificsoftware/bssw.io#1383]
Enter details here by replacing *italicized text* with actual event information and without adding or removing lines.  You are encouraged to look at some [published events](https://bssw.io/events) in order to get a feel for how the requested information will appear on the site.

* **What:** *Call for Papers:  Research Software Engineers in HPC Workshop at SC22*

The title should be concise (more complete information can be included in the Description, if necessary).  If your event is a call for papers, posters, or other contributions, put that at the beginning of the title (for example, *Call for Papers: My Little Workshop*) and provide the deadline date for submissions below.  Once the deadline has passed, you can submit a new event for the event itself (sometimes refered to as a "call for participation", but we discourage including that in the event title).

* **When:** *August 5, 2022*

In the published event, the date appears immediately below the **title**, as well as further down, along side the **location** and **organizers**.  The date information is also used to control the visibility of the event on the <https://bssw.io/events> page.  Anything entered in this field that is not regoznied as a date or date range is *ignored* and will not appear in the published event.

* **Where:** *Dallas, TX and Online*

Events may include, for example, surveys, where the target audience is focused on a geographical region, such as "United States" or "European Union".

* **Organizers:** *The organizers of the event (text only).  Optional*

* **Website:** *https://us-rse.org/rse-hpc-2022/*

The URL will be linked under the text "Event Website", which appears in two places in the published event: immediately after the **summary** and immediately after the **description**.

* **Summary:** *This will be a half-day workshop held as part of the [SC22](https://sc22.supercomputing.org) conference (hybrid event, in Dallas, TX and virtually).*

In the published event, this will appear between the **title** and **date** and the **date**, **location**, and **organizers** block, which is above the **description**.  It is styled in a font that is in between the **title** and the **description** in size (which makes long **summary** text take up a lot of space, which generally looks bad).

* **Description:** *The remainder of this issue will be treated as the body of the event.*

This workshop will bring together RSEs and allies involved in HPC, from all over the world, to grow the RSE community by establishing and strengthening professional networks of current RSEs and RSE leaders.  We’ll discuss the current activities and plans of national RSE organizations, discuss the needs of RSEs and RSE groups, and brainstorm ways RSE organizations can help address these.

We encourage prospective participants to submit position papers (limit of 2 pages, not counting references; no format prescribed) on topics related to RSE issues. Papers and discussion topics should be submitted using the [submission website](https://submissions.supercomputing.org/?page=Submit&id=SC22WorkshopRSEHPC2022Submission&site=sc22). The deadline for submissions is Friday, August 5, 2022, at 11:59 PM AoE (UTC-12).

Important Dates:
* **Submissions open:** *Wednesday, June 15, 2022*
* **Submissions due:** *Friday, August 5, 2022*
* **Notifications sent:** *Friday, September 2, 2022*
* **Program finalized:** *Friday, September 16, 2022*
* **Workshop date:** *Sunday, November 13, 2022*

For more information, [see the workshop website](https://us-rse.org/rse-hpc-2022/) or [contact the organizers](mailto:sc-ws-rse-hpc@info.supercomputing.org).

**Comment by cferenba** [comment]
Edited original to fix formatting of date list.

**Comment by rinkug** [comment]
Created PR and added some more details to the event from the CFP page of event source.

**Comment by rinkug** [comment]
Please continue discussion on PR #1384
