### ISSUE TITLE
Handling of bounces from BSSw digest mailings

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1420]
The BSSw monthly digest uses info@bssw.io as the sender address.  Replies and bounces (mostly out of office notifications) will to back to that address.  From time to time, the messages that bounce back indicate that someone's left the job (and therefore he email) that we're sending to.  Sometimes they give a new email, sometimes not.  When we get such messages, we need to update the entries in our Mailchimp audience listing accordingly (new email or remove the record).

We should have someone designated to handle these, train them, and make sure they're on the list to receive info@bssw.io traffic.

**Comment by bernhold** [comment]
I had to handle some more bounce messages from the January digest.  I think this is something that Kasia could do.  We just need to understand whether she's already seeing the bounce messages and walk through the responses together a few times.

**Comment by rinkug** [comment]
Sending digest on Tue-Wed-Thus to reduce likelihood of messages. Rinku to take this over short term till end of 2023.
