### ISSUE TITLE
Maintainer skills guides from Sumana Harihareswara

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1421]
Author: @haikudeb 
EB member: @curfman

BSSwF Honorable Mention Sumana Harihareswara has a newsletter.  The latest issue points to some "maintainer skills guides" she's developed, which seem likely to be useful curated content.  Note: I have not read them yet.

https://buttondown.email/Changeset/archive/maintainer-guides-spending-succession-more/

**Comment by rinkug** [comment]
I looked at the maintainer skills guide and they look good to me.  I can draft a cc on it, if we have enough votes?
