### ISSUE TITLE
Content: How does running a job at an LCF differ than on your laptop or cluster?

### ISSUE THREAD

**Issue by monkeystate** [betterscientificsoftware/bssw.io#143]
Placeholder for Lisa to write (in the future, not in time for site launch):
Create draft “How does running a job at a LCF differ than on your laptop or cluster?” (overview text with ALCF subtopic; handoff to other facilities to flesh out their subtopics)

**Comment by bernhold** [comment]
Lisa, you probably know/remember this, but Katherine has a talk on this 
that she gave in the first series of webinars.

A writeup could draw on that, and/or link to the webinar.

**Comment by monkeystate** [comment]
Yes that was my plan exactly :)

Lisa


________________________________

**Comment by rinkug** [comment]
This can be a blog or a curated content to a webinar

**Comment by rinkug** [comment]
Rinku can write this, if it gets enough thumbs up

**Comment by bernhold** [comment]
The webinar that Catherine Riley gave was targeted at helping computational researchers with little or no "HPC" experience understand why and how the setup and user experience on high-end systems is often so different from their individual machine or the group cluster.  From the LCF persepctive, it would be targeting prospective users.

**Comment by JeanShuler** [comment]
There are many people who would find this information useful.

**Comment by pagrubel** [comment]
So I had to look LCF up, sorry just not used to the acronym, so the title is probably not that good, but I think the topic may be for those who are trying to start using HPC facilities.

**Comment by bernhold** [comment]
I have mixed feelings about closing this.  Maybe a cc to the webinar with a little more text around it than usual would suffice.  I don't think we're going to get a blog article from Katherine, and Lisa has moved on to other things. But even after all this time, I think it would be good to have *something* in this line on the site.  The audience, as I think has been stated above, is folks who are wanting to get into larger scale and may indeed *not* be familiar with queing systems, parallel filesystems, etc.  If they haven't used a even a local cluster yet, they may not understand login/head nodes vs compute nodes either.

**Comment by bernhold** [comment]
I think we should do one of two things with this.

1) turn it into a cc.  In which case we need to change the labels appropriately
2) Close it

**Comment by markcmiller86** [comment]
Its very old and very vague. I vote to close.
