### ISSUE TITLE
Bssw.io broken links need fixing

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1458]
There are a bunch of broken links on bssw.io (can be found in gdrive), obtained from running a third-party scanning tool. We have a list of about 70 items which need to be fixed. 

* All broken zoom, registration links are to be ignored
* New updated links should be searched.
* If no new links for the broken link is found, then broken link should be removed (keeping anchor text possibly in place).

**Comment by markcmiller86** [comment]
@rinkug not sure if you were aware of #1431

**Comment by rinkug** [comment]
> @rinkug not sure if you were aware of #1431

Thanks for linking it
