### ISSUE TITLE
Possible Blog Article: Julia's value proposition for better scientific software

### ISSUE THREAD

**Issue by williamfgc** [betterscientificsoftware/bssw.io#1470]
Title: "The Julia programming language value proposition for better scientific software"

Short abstract:
Julia is a dynamic open-source language designed with scientific computing (Fortran-like) and data science (Python-like) friendly syntax. Julia code builds upon LLVM for performance on CPU and GPU heterogeneous hardware, prioritizes lightweight interoperability with existing C and Fortran frameworks, while providing a unified language ecosystem for data analysis, plotting, interactive computing, reproducibility, testing, instrumentation, and packaging. Julia is a one-stop-shop alternative to the N-language+ecosystem programming components used in the increasingly expensive and complex process of rapid prototyping going from ideas to performance portable and composable simulation+data workflows. In this article we describe the value proposition of Julia for the communities invested in the different angles of better scientific software.

**Comment by bernhold** [comment]
Hi @williamfgc, I'm wondering if you have thoughts about a hero image for your blog post.  The guidelines are below.  But I was thinking that maybe you had either a Julia-based science image to share, or a "people photo" from one of the recent Julia events that you've organized?  We work with a designer who can handle any cropping and other adjustments that might be necessary, so all we really need from you is a candidate image or two.  We can also go with a stock image or with no hero at all.

At the top of your article, we can include a "hero" image, which is also used as a background to highlight it as the newest article in the list of blog postings. This image is optional, but if you have ideas for an appropriate image please let us know. Many blog articles are published without hero images. Guidelines for "hero" image:
- wide rectangular shape; we can crop an image to the required size (1125 x 432 pixels)
- the design brief for our site focuses on three types of imagery for hero:
  - stock images (we have access to a number of stock photo libraries),
  - data visualizations, or
  - people in trainings, workshops, conferences, or other settings
- "hero" images should contain no bold text; incidental text (in diagrams, for instance) is OK.
