### ISSUE TITLE
Blog Crosspost: US-RSE / BSSw Article on Communities of Practice

### ISSUE THREAD

**Issue by mrmundt** [betterscientificsoftware/bssw.io#1482]
## Abstract

The explosion of Research Software Engineers (RSEs) in the United States created the opportunity to form communities of practice (CoP), groups which share a passion for an activity and learn how to do it better as they interact regularly, specifically to benefit their local organization or region. CoPs, however, only succeed insofar as their members feel heard, included, and valued. This blog post is based on the 2022 US-RSE Virtual Workshop breakout session “Encouraging and Enabling Mutual Ownership in a RSE Community of Practice.” Participants from industry, academia, and national laboratories and agencies across the country joined together to create actionable suggestions for how to get members involved in a community of practice and how to make them feel invested and included.

### Encouraging and Enabling Mutual Ownership in a RSE Community of Practice

_Authors: Miranda Mundt, Jonathan Bisila, Jon Guyer, Daniel Howard, Daniel S. Katz, Reed Milewicz, Henry Schreiner, Joshua Teves, Chris Wiswell_

#### Introduction

The explosion of Research Software Engineers (RSEs) in the United States created the opportunity to form communities of practice (CoP), groups which share a passion for an activity and learn how to do it better as they interact regularly, specifically to benefit their local organization or region. CoPs, however, only succeed insofar as their members feel heard, included, and valued.

As part of the [2022 US-RSE Virtual Workshop](https://us-rse.org/virtual-workshop-2022/), Jonathan Bisila, Reed Milewicz, and Miranda Mundt of Sandia National Laboratories moderated the breakout session “Encouraging and Enabling Mutual Ownership in a RSE Community of Practice.” In this session, participants from industry, academia, and national laboratories and agencies across the country joined together to create actionable suggestions for how to get members involved in a community of practice and how to make them feel invested and included.

#### Starting a community of practice

A CoP is a group of people who share some concern or passion for what they do and want to learn to do it better as they interact regularly. CoPs generally have 3 elements: (1) mutual engagement, (2) a joint enterprise, and (3) a shared repertoire. The three moderators recently took on the challenge of creating a formally-defined CoP at Sandia National Laboratories.

At their inaugural meeting, they started by asking the question, “Who is the intended audience?” Because RSE looks different across different organizations, to start a CoP off right it’s important to understand the intended audience. To determine this, they asked questions to the meeting attendees such as: What careers are representative within your organization? How can you cast a wide enough net to be inclusive without diluting the targeted community? Having an identity means that certain things are in scope and are part of that identity, and other things are not part of that identity. Poor scoping can stop a community before it even starts.

> Tip: You don’t want to exclude potentially interested community members, so don’t start too small or refined in your intended audience, or you won’t get enough interest!

Once the CoP has some initial interested participants, the next task is to define the goals of the CoP community. What is it trying to accomplish? What will it bring to and expect from the community members? For US-RSE, the mission comes in four parts: (1) community, (2) advocacy, (3) resources, and (4) diversity, equity, and inclusion. The founders of a new community can define the original mission – but should work with the community to refine it as time goes on. There should be a clear benefit for the community, whether that’s through access to information (e.g., providing resources on how to set up software infrastructure), a place for mutual commiseration, or a mechanism for finding collaborators.

> Tip: It is okay for your goals to evolve as your community matures. Start with identifying common problems and promoting dialogue around those problems.

#### Community infrastructure

Not everyone may have heard of the "Aesthetic-Usability Effect," but we have all experienced it. This effect refers to “users’ tendency to perceive attractive products as more usable. People tend to believe that things that look better will work better — even if they aren’t actually more effective or efficient.”[^1]

[^1]: Moran, Kate. "The aesthetic-usability effect." Nielsen Norman Group: https://www.nngroup.com/articles/aesthetic-usability-effect (2017).

Before beginning regular meetings and discussions, having a community infrastructure where members can sign up for notifications, find information, resources, etc., is essential to early success. To bolster this, the more usable and well-organized the initial material is, the more value potential members will experience from the onset.

It is also valuable to have a platform through which community members can contribute. The moderators, for example, host their content on an instance of Confluence, a wiki-style version-controlled collaborative tool[^2]. They created templates and guides for how to contribute, including what topics might be of interest, how to name pages, where to put them, etc.

[^2]: https://www.atlassian.com/software/confluence/guides/get-started/confluence-overview

> Tip: Have material or a website for potential members to visit or view in time for your first meeting. It doesn’t have to be perfect, but it will provide a sense of immediate value and confidence.

#### Promoting inclusion and participation

Many new communities will start off strong and then suffer from a loss of interest over time. Keeping a community continually engaged is a constant challenge, especially when it is geographically distributed - something most of us experienced as a result of the COVID-19 pandemic. It is essential to incentivize people to show up and to overcome those remote barriers.

> Tip: Chris Wiswell’s team utilized modern delivery services to do a coffee and treat delivery across team members. Use these to your advantage! Set up a coffee-delivery raffle for those who join your meeting.

Participation can also be bolstered through relevant content. The community should have a say in the topics that are being covered in the regular meetings. Providing an avenue for members to vote on topics or contribute their own (with minimal roadblocks to do so) can help build a feeling of empowerment and value.

It is also important to recognize that different members prefer different forms of communication. Some may like emails; some may prefer to submit an anonymous feedback form; others prefer to communicate face-to-face. Diversifying the ways in which community members can engage with the content and with one-another will broaden your inclusivity.

> Tip: Create various ways for community members to provide feedback. Make an email list, a webpage, a survey, etc., that is easy to find and use. The easier it is for people to provide feedback, the more likely it is that they will.

#### Conclusion

Creating a thriving, active community is a challenge. As part of the 2022 US-RSE Virtual Workshop, participants discussed the difficulties and posed helpful tips to make a community of practice more successful. They hope that the results of this discussion can assist other RSEs in the creation of their own local CoP.

**Comment by bernhold** [comment]
Hi @mrmundt thanks for your contribution.  Can you give us a little more info about exactly when and where you expect this to appear on the US-RSE side of things and your expectations of how we should handle it on BSSw.io? Do we need to coordinate publication?  Is it okay if we repost somewhat later than US-RSE?

Thanks

**Comment by mrmundt** [comment]
Hi @bernhold - On the US-RSE Side, it will show up in their [News Feed](https://us-rse.org/news), though "when" is very flexible. In terms of expectations, since we've never done this before, we have choices:

1. Figure out how to cross-post to both locations
2. Publish at different times (which is absolutely no problem)

**Comment by mrmundt** [comment]
@bernhold - I have opened a [PR with USRSE](https://github.com/USRSE/usrse.github.io/pull/998) to publish the blog post there.

**Comment by bernhold** [comment]
Published: https://bssw.io/blog_posts/recap-encouraging-and-enabling-mutual-ownership-in-a-rse-community-of-practice
