### ISSUE TITLE
Guide to Organizing Inclusive Scientific Meetings

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1526]
Author: @haikudeb 
EB member: @rinkug 

Possible CC target (or maybe add to appropriate existing resources): https://500womenscientists.org/inclusive-scientific-meetings

**Comment by markcmiller86** [comment]
I upvoted it. It did take quite a bit of reading (about DEIJA in general) to get to some concrete practices in the meat of the article.

That said, I took a quick look and my first reactions are...what about this topic has anything special to do with science? I mean, meetings are meetings aren't they? Does the fact that people are coming together to talk about science really alter the inclusivity competency needed?

**Comment by pagrubel** [comment]
What existing resource could this be added to. 
I guess we could say that improving scientific meetings improves software but I am hesitant to do an upvote because I'm wondering if it is a stretch for our site?

**Comment by markcmiller86** [comment]
If you're talking categories or tags, better collaboration -> inclusivity.

**Comment by haikudeb** [comment]
See also : 
https://diversityandinclusion.uchicago.edu/events/
