### ISSUE TITLE
Possible Other Article for BSSw

### ISSUE THREAD

**Issue by mrmundt** [betterscientificsoftware/bssw.io#1551]
## Title

US Research Software Engineer Association Conference (US-RSE’23): Software Enabled Discovery and Beyond - October 16-18, Chicago, IL

## Content

The first ever US-RSE Conference (US-RSE’23) is happening October 16-18, 2023, in Chicago, IL. The theme of this year’s conference will be “_Software Enabled Discovery and Beyond_.” Topics of interest include (but are not limited to):

- Discovery enabled by software
- Architectures, frameworks, libraries, and technology trends
- Research data management
- Support for scalability and data-driven methods
- Improving the reproducibility of research
- Usability, portals, workflows, and tools
- Sustainability, security, and stability
- Software engineering approaches supporting research
- Community engagement
- Diversity, Equity, and Inclusion for RSEs and in RSEng
- Training and workforce development
- Building an RSE profession

**Important Dates**

- **Submissions open**: Tuesday, February 14, 2023
- **Workshops, Tutorials, and BoF submissions due**: Monday, March 20, 2023
- **Papers / Notebooks due**: Monday, May 1, 2023
- **Registration opens**: Monday, May 1, 2023
- **Poster / Talk abstracts due**: Monday, June 19, 2023
- **Tutorials (VIRTUAL)**: October 2-13, 2023
- **Conference (IN-PERSON)**: October 16-28, 2023

See the website for more details: https://us-rse.org/usrse23.

**Comment by mrmundt** [comment]
@bernhold

**Comment by rinkug** [comment]
Similar to #1568 and #1569
