### ISSUE TITLE
Possible Blog Article on GO FAIR US and scientific software

### ISSUE THREAD

**Issue by keknight** [betterscientificsoftware/bssw.io#1557]
I'd like to write something for your community explaining how GO FAIR relates to scientific software and sustainability (esp. since FAIR was initially about data, and now has expanded to include software and workflows).

**Comment by bernhold** [comment]
I've had further communications with Katie about a blog article, but I think she's too busy. Whlie we'd still welcome her contribution, I suggest we close this issue for now and open a new one if Katie has time to pursue it.
