### ISSUE TITLE
Adding track meta to all relevant articles

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1558]
Related to #699.

Context: Blogs, original articles, howtos, what-is will now be distinguished using "tracks" and all these articles will be available under https://bssw.io/blog_posts. To achieve this, we need to add the "track" metadata in these articles. Since we are touching all these articles, we may as well remove old obsolete metadata.

- **We need to add new *Track* metadata to everything in [Articles directory]**(https://github.com/betterscientificsoftware/bssw.io/tree/master/Articles)
    Track: Deep Dive/How To/Community/Experience/Bright Spots

- **What meta should each file ideally have?** 
   Ideally each file should have the following metadata as listed in the [BSSw.io Editorial Guide](https://betterscientificsoftware.github.io/bssw.io/bssw_content_metadata.html): 
    Publish: yes
    Pinned: no
    RSS Update: 2023-01-11
    Topics: projects and organizations
    Track: 

  **We dont know how RSS feed behaved, so dont add RSS update if a file does not already have that.**

- **We need to remove old metadata**
   Please remove anything that is obsolete other than what is mentioned above.

- **Do articles need to move between folders?**
  Yes eventually, but lets leave that aside for now.

**Comment by bartlettroscoe** [comment]
@rinkug, please see:

* #1896 

for the articles assigned to me
