### ISSUE TITLE
Resources for Open Source Program Offices

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1582]
https://github.com/github/github-ospo

**Comment by bernhold** [comment]
The page itself also mentions
* https://todogroup.org/
* https://ospo.zone/
* https://opensource.guide/

**Comment by markcmiller86** [comment]
Would be worth mentioning in the CC that this effort is just in its infancy stages...which may incentivise some to get involved early and others to wait and see.
