### ISSUE TITLE
In which journals should I publish my software?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1586]
Author: @rinkug 
https://www.software.ac.uk/which-journals-should-i-publish-my-software is a resource we do not currently have.

I suggest we rework https://bssw.io/items/where-and-how-to-publish-cse-software to (mostly) reference the SSI page.  However we should check our list against SSI's and keep anything that is not on the SSI list.  We should also keep FigShare and Zenodo.

**Comment by rinkug** [comment]
@ibaned : Thank you for your original curated content contribution to bssw.io. Please note that we are updating your article with new minor information (please refer to PR).
