### ISSUE TITLE
Event Notice: Research Software Engineers in eScience Workshop 2023

### ISSUE THREAD

**Issue by mrmundt** [betterscientificsoftware/bssw.io#1591]
* **What:** Research Software Engineers in eScience Workshop 2023: Sustainable RSE Ecosystems

* **When:** October 9, 2023

* **Where:** Limassol, Cyprus

* **Organizers:** US Research Software Engineer Association

* **Website:** https://us-rse.org/rse-escience-2023

* **Summary:** Research Software Engineers (RSEs) combine professional software engineering expertise with an intimate understanding of research and are uniquely placed in the eScience ecosystem to ensure development of sustainable research environments and reproducible research outputs. The theme of this workshop is sustainable RSE ecosystems, encompassing both the role of RSEs in sustainable eScience and making the RSE ecosystem itself more sustainable.

* **Description:** *The remainder of this issue will be treated as the body of the event.*

Research Software Engineers (RSEs) combine professional software engineering expertise with
an intimate understanding of research. They are uniquely placed in the eScience
ecosystem to ensure development of sustainable research environments and reproducible
research outputs. However, the position of RSEs within eScience is still not fully established, with
many RSEs not gaining proper recognition for their contributions and struggling to find a way to
progress their careers. The theme of this workshop is sustainable RSE ecosystems, encompassing
both the role of RSEs in sustainable eScience and making the RSE ecosystem itself more
sustainable. We intend for this workshop to raise awareness of the concept of research
software engineers and research software engineering (RSEng), as well as to provide an
opportunity for RSEs and those interested in RSEng to talk about issues and solutions.
Anyone involved or interested in RSEng is welcome to attend. 

We encourage prospective participants to  submit talk abstracts (max 300 words)
on topics related to Sustainable RSE Ecosystems within eScience.

Possible topics include (but are not limited to):

- Experiences as an RSE in eScience
- Struggles between RSEs and domain scientists - how to find the common ground?
- Different roles in the development of research software
- How to make the eScience and RSE ecosystem more sustainable? 
- What can the eScience community do to support their RSEs? How can RSEs develop and progress their careers within the eScience community?
- How to argue for funding to develop and sustain scientific software, and support the RSEs doing the work?
- Examples of RSEs enabling sustainability within the eScience community

We will ask the authors of accepted abstracts and presentations to self-publish (after
revisions, if applicable) to an archival repository (e.g., Zenodo, arXiv). Our
website will then provide links to the self-published documents.

Accepted submitters will also be invited to present in-person at
the workshop, after which there will be a short panel discussion and then breakout
sessions with the larger group of attendees.

We particularly encourage submissions from first-time conference presenters
and from members of groups that have historically been underrepresented in the
eScience community.

Submission website:
[EasyChair](https://easychair.org/conferences/?conf=rseescience2023)

### Timeline

- Submissions open:  Monday, March 20, 2023
- Abstract submissions due: Friday, June 30, 2023
- Notifications sent:  Tuesday, August 1, 2023
- Program finalized:  Tuesday, August 15, 2023
- Workshop date:  Monday, October 9, 2023

### Questions?

Contact the organizers: [wg-outreach@us-rse.org](mailto:wg-outreach@us-rse.org)

**Comment by rinkug** [comment]
@mrmundt :Thanks for your submission. Your event is now online: https://bssw.io/events/research-software-engineers-in-escience-workshop-2023-sustainable-rse-ecosystems
