### ISSUE TITLE
Search: Tests and Results

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1613]
Experimenting with search feature:

**From RInku 07/18/22**
We discussed the search topic again recently. Here are some of the items from the discussion.
All results should be displayed with recent publish date first.

We should have a “Recent additions” link on the front webpage. This should take me to a time-ordered list (can be same as the “null” search result) ? 

We dont want to return author pages in our search.

We perhaps should display publish date against each search

Quoted strings search for exact matches, except for case (case insensitive). Multiple quoted strings are interpreted as AND rather than OR (i.e. all phrases should appear in the same document)

Search should be fast. 

Current search is very very slow and not very good.

For the rest of the search topic, we want Unquoted strings to be searched “intelligently”.  We basically want things to work similarly and efficiently to what Google search would do and we need guidance from Parallactic on how they would do this. Should this also include synonyms, spelling errors etc. -- these are topics on which we also need guidance from Parallactic/Sandbox.

**From Clara 07/27/22**
The concluded approach is that we will work on an integration with the third-party search tool Algolia, and set up a preview version of that to be available for testing. This should handle most of the basic features requested, such as:
Accents: https://react-instantsearch.netlify.app/examples/media/?query=garcia&page=1&configure%5BhitsPerPage%5D=10

Quoted strings: https://react-instantsearch.netlify.app/examples/media/?query=%22new%20hope%22&page=1&configure%5BhitsPerPage%5D=10

Unquoted strings: https://react-instantsearch.netlify.app/examples/media/?query=history%20game&page=1&configure%5BhitsPerPage%5D=10

Typo: https://react-instantsearch.netlify.app/examples/media/?query=hpoe&page=1&configure%5BhitsPerPage%5D=10

We will also add "pages" to what is indexed by search, and we will remove contributor pages from what is indexed. We will display results in order of publication date.

We will revisit the question of filters once a preview version of the redone search is available.

**Comment by rinkug** [comment]
Following updates to search feature, I see the following.

1. Basic words testing seems to return predictable results.

- I noticed that Hervé Ménager returns more than entries: https://bss.parallactic.com/items/search?search_string=Herv%C3%A9+M%C3%A9nager . And I dont know why.

2. Typos seems to get auto- corrected

- https://bss.parallactic.com/items/search?search_string=rniku
- https://bss.parallactic.com/items/search?search_string=rerodcible (typo for repdroducible)

4. Quotes matching seems to work

**Comment by bernhold** [comment]
Hervé Ménager (unquoted) returns 23 hits.  It is matching "here" and "manager". herve manager (unquoted) has the same.  It appears that it is "correcting" our spelling.  I got the same autocorrection when trying to type this comment.

This is just a single example where the results seem to be "looser" than I might expect. We will need to decide whether the "autocorrect" spelling support is beneficial or not.

**Comment by bernhold** [comment]
In a search for "best practices" "webinar series" one article didn't seem to have an excerpt like the others

![Capture](https://github.com/betterscientificsoftware/bssw.io/assets/426409/88da5e9c-f2c6-4470-9895-4aa643ff77e4)

**Comment by bernhold** [comment]
Here's another case of the excerpt being truncated.  The search was "best practices" "journal"

![Capture](https://github.com/betterscientificsoftware/bssw.io/assets/426409/fdb658e0-49c7-4115-a4c9-61a63ef8a18f)

**Comment by markcmiller86** [comment]
Some quick thoughts after playing a bit with search in bss.parallactic.com...

* Search should not match on any text in the "More on <topic list>..." followed by article titles at the bottom of the page. I am not saying it does do that. Google's search does match that text (at the bottom of every page)
* Exact matches for entered text should be displayed ahead of partial or approximate matches IMHO
* I don't think it makes sense to match *entered* words which appear in the middle of other words (e.g. "big" matches "Abigail", "data" matches "details")
* When search results are displayed but search alg. is suspect of an entered word's spelling, can it do the "google way" and warn user "show results for block", "search instead for blog"?

None of this is that important. So, I think its fine if we decide to ignore it. I just wanted to make a record of some of these thoughts somewhere.

**Comment by pagrubel** [comment]
I understand that the new search puts things in order, and I can see what it ended up searching for since it highlights it. But why does it do an autocorrect on a word that is spelled correctly. Here is a screenshot of searching for "what" without the quotes. 
![image](https://github.com/betterscientificsoftware/bssw.io/assets/2473171/cb0907a2-f4f8-4d1d-8ff2-4687bf430937)

**Comment by rinkug** [comment]
My general comments match those of [Mark Miller above](https://github.com/betterscientificsoftware/bssw.io/issues/1613#issuecomment-1624091734).

I have not found any new bugs to report as such so far

**Comment by pagrubel** [comment]
Also maybe there should be a note how finds are ordered. 
It is much nicer though. I suspect I would use quotes almost always now that I see what is happening.
If I put the word "what" in quotes there is no problem. If they are going to keep it how it is currently then add to the Note "Add quotes to search phrases or exact spellings." :)

Is there an ability to search a range of dates. What if I know something about an article that I know was done a few years ago, could I specify dates to search. I don't know if this is valuable or not but I thought it might be benificial.

**Comment by pagrubel** [comment]
Make the note: "Use quotes to search for phrases."
"Use quotes to search for phrases or for exact spellings."

**Comment by haikudeb** [comment]
I assisted with testing the search feature yesterday and I searched for the word refactor, without quotes. The 5th one deployed had the word reactor, and then it moved into blog articles that had the tag refactoring, but not the word refactor in the article. I'm wondering if there is a way to put the spelling changes as the last option with display order?

**Comment by rinkug** [comment]
Summary so far:
- BSSw.io member recommended having search ranges to narrow down articles
-BSSw.io member recommended that we replace "Use quotes to search for phrases." to “Use quotes to search for phrases or for exact spellings."

Some issues based on our requirement of publication dates and some other issues based on the settings of the algolia search tool:
* Exact matches for entered text should be displayed ahead of partial or approximate matches
* It does not make much sense to match entered words which appear in the middle of other words (e.g. "big" matches "Abigail", "data" matches "details")
* When search results are displayed but search alg. is suspect of an entered word's spelling, can it do the "google way" and warn user "showing results for block", "search instead for blog"?

**Comment by bartlettroscoe** [comment]
I will add my more detailed notes next but I just wanted to point out some oddities that I see with the updated search at:

* https://bss.parallactic.com

For example, the search [cmake git] (no quotes) at:

* https://bss.parallactic.com/items/search?search_string=cmake+git

selects articles with 'cmake' OR 'git' (and any word that has 'git' in it)

Also, the browser tab for a search like above is always spinning, even through the search results are already shown.

And the top-level search page is previewing 'make' like showing:

----
![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/89ca6684-6cfb-4ac5-a68b-c8096b71eadd)

----

But the search text is 'cmake' and 'git', not 'make'.  That is not helpful and looks confusing.  You see the same strange 'make' matching for:

----
![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/d3b81079-9812-40a0-b1b0-8a3057d05113)

----

and

----
![image](https://github.com/betterscientificsoftware/bssw.io/assets/1959736/70df8406-52c1-43d8-b6fa-3e361a85fcff)

----

There is more strange behavior I will post in the next comment.

**Comment by rinkug** [comment]
All above comments were shared with the vendors and addressed. The final results looked good and are now deployed on bssw.io

**Comment by bartlettroscoe** [comment]
> All above comments were shared with the vendors and addressed. The final results looked good and are now deployed on bssw.io

@rinkug, I am seeing the same strange behavior noted [above](https://github.com/betterscientificsoftware/bssw.io/issues/1613#issuecomment-1654786502).   It does not look like they fixed that confusing behavior.

Also, the word "cmake" is not even present in the article:

* https://bssw.io/blog_posts/busy-productive

selected by the query [cmake git]:

* https://bssw.io/items/search?search_string=cmake+git

The corresponding Google search [site:bssw.io cmake git] does not shown that article.

It looks like bssw.io search is using OR instead of AND for multiple words 'cmake' and 'git'.  That is strange.

FYI: It looks like putting quotes around "cmake" and "git" implements and "AND" search:

* https://bssw.io/items/search?search_string=%22cmake%22+%22git%22

Why does the bssw.io search behavior so differently than standard web search tools?

Is this non-standard behavior of the bssw.io search documented anywhere?  The only documentation I can find is "Use quotes to search phrases and exact spellings".  (But that does not mention the strange AND/OR behavior of quotes vs. no quotes.)

However, except for these things, the search performance does seem to be greatly improved over the previous implementation.  So in any case, this is an improvement.

**Comment by rinkug** [comment]
All issues which search seem be resolved at this point for phase 1, so I will go ahead and close this issue.
