### ISSUE TITLE
Additional topics on BSSw.io contact form

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1618]
Possible new topics for contact form drop down:
* I have a question about the BSSw Fellowship
* I want to contribute to the site

This doesn't seem urgent, but the first in particular might be useful.

**Comment by rinkug** [comment]
EB team agreed to these changes. @bernhold to communicate to vendors and mention that its lower priority.

**Comment by bernhold** [comment]
Added to Basecamp 2023-04-13

**Comment by rinkug** [comment]
<img width="1149" alt="Screenshot 2023-12-10 at 9 09 58 PM" src="https://github.com/betterscientificsoftware/bssw.io/assets/768870/bfa46de5-d17c-44e2-883c-4016ae60da47">

This is completed
