### ISSUE TITLE
Most developers think we should spend more time on documentation

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1627]
- From 2017, https://bids.berkeley.edu/news/most-developers-think-we-should-spend-more-time-documentation
- https://swimm.io/blog/developer-documenting-done-right/
- https://www.transposit.com/devops-blog/devops/2020.02.26-rewarding-documentation-in-devops/

**Comment by markcmiller86** [comment]
Reading just the subject line of this issue, my first though is that most developers think "other developers" should spend more time (e.g. do a better job) documenting their package(s) but do not think they need to spend more time documenting their own packages. In other words, we all think the documentation we've created for our own packages is way better than it actually is and that is because none of use documenting our packages are working from complete naivety when trying to learn to use them. We are blind to other's experiences trying to use the software we write.

**Comment by markcmiller86** [comment]
Something else I've learned on VisIt project is that it is possible to put too much time into documentation. That is, there is a sweet spot in documentation creation effort. Too little and users are unable to learn to use your software without a lot of questions and hand-holding. Too much effort and documentation becomes obsolete so quickly (e.g. code changes, features change, etc.) and the effort expended becomes a complete loss.

**Comment by pagrubel** [comment]
For me the 2nd two links are more what I would want to look at. I don't really care what most developers think as much as how can I make sure that our documentation is appropriate for the users and future developers. So the 2nd two articles are more what I would lack at. That also makes the title less inviting to me. I would like to see a CC however so I'm going to give an up vote.

**Comment by bartlettroscoe** [comment]
Right, but given a larger set of options like:

* User issues:
  * Add requested new features in a timely manner
  * More frequent releases
  * Less defects in new releases
  * Support of existing releases
  * Working and tested examples (which is similar to documentation but it is tested documentation)
* Developer issues
  * Cleaner code
  * Better code/feature test coverage
  * Faster tests

where would documentation rank?

**Comment by bartlettroscoe** [comment]
The article:

* https://bids.berkeley.edu/news/most-developers-think-we-should-spend-more-time-documentation

provides some convincing evidence most developers feel they should be spending more time writing documentation.

But if you asked them the same question on testing, what would they say?

**Comment by bartlettroscoe** [comment]
I think it is worth a CC article.

**Comment by rinkug** [comment]
This article has disappeared. But, I will write a cc on the remaining two
