### ISSUE TITLE
Event: https://diverse-rse.github.io/events/2023-05-16 (time sensitive)

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1670]
Looks like the DiveRSE program has another webinar scheduled: https://diverse-rse.github.io/events/2023-05-16

Do we want to include this on BSSw.io?  Should we hand it off to Suzanne?  Both?  Neither?

**Comment by rinkug** [comment]
While I dont know how much of this talk with focus on research environment settings and its correlation to mental health -  I think we can include this on BSSw.io, based on the authors profile and outlines of the previously similar talks that he has delivered.
