### ISSUE TITLE
use github open source guides when possible

### ISSUE THREAD

**Issue by danielskatz** [betterscientificsoftware/bssw.io#168]
Author: @rinkug 
EB member: @pagrubel 
Potentially link to some of the guides on https://opensource.guide

**Comment by bartlettroscoe** [comment]
Just did a quick browse but it looks very good.

**Comment by rinkug** [comment]
This has size votes and I will move it to in-progress.  I can write it and Lois can be the EB member

**Comment by pagrubel** [comment]
@rinkug Are you writing this?

**Comment by rinkug** [comment]
> @rinkug Are you writing this?

Yes! I will wrap this up soon

**Comment by bernhold** [comment]
@rinkug @pagrubel I wanted to check whether this was really "in progress" or not so that we can put it in the proper column of the  project board.  Thanks

**Comment by bernhold** [comment]
In email, Rinku says "Will work on this this week."

**Comment by rinkug** [comment]
Please follow PR for any discussion on this.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211
