### ISSUE TITLE
URL checker shows bad links for forms?

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1693]
The URL checker script from Sandbox gives the following errors

1. URL: https://bssw.io/contacts

- Anchor text: form/action(post)
- Linked from: https://bssw.io/contact

1. URL: https://bssw.io/contributes
- Anchor text: form/action(post)
- Linked from: https://bssw.io/pages/questions-about-contributing-to-better-scientific-software

**Comment by rinkug** [comment]
Find where these strings appear in the BSSw.io source tree: https://bssw.io/contacts and https://bssw.io/contributes 7:24 here is the basecamp thread. It's possible that these might be specified in the code as something other than the full address (e.g., as a filename, and in that case it might be just 'contributes')

**Comment by bernhold** [comment]
Since the forms work, I'm not too concerned.  I suggest we ignore them.  If you want, you can ask Matt/Clara to confirm that they're okay to ignore.

**Comment by rinkug** [comment]
> Since the forms work, I'm not too concerned. I suggest we ignore them. If you want, you can ask Matt/Clara to confirm that they're okay to ignore.

I agree. I am ignoring them for now.

**Comment by rinkug** [comment]
This can be closed.
