### ISSUE TITLE
Executable environments for software, data, publication

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/bssw.io#170]
EB member: @rinkug 

There are several environments that support collecting data, software and publication content for the purpose of providing a more complete context for generating a paper, reproducing its results and exploring its parameter space.  Examples include Popper, OCCAM, CodeOcean, Shablona

OCCAM source code:
https://bitbucket.org/occam/profile/repositories

OCCAM demo site:
https://occam.cs.pitt.edu

CodeOcean:
https://codeocean.com

Popper:
https://github.com/systemslab/popper/tree/master/popper

Shablona:
https://github.com/uwescience/shablona/blob/master/README.md

**Comment by rinkug** [comment]
Good idea. Need to review the links added by Mike and add new ones if we find

**Comment by JeanShuler** [comment]
New link for popper https://github.com/systemslab/popper

**Comment by JeanShuler** [comment]
The Shabola README file at  https://github.com/uwescience/shablona/blob/master/README.md document is a good example of a template project for small scientific python projects.

**Comment by JeanShuler** [comment]
The Occam website https://occam.cs.pitt.edu is also a good resource for data publication.  It is a toolset for the preservation of rebuildable software and a self-hostable, federated web portal for composing repeatable workflows.
Occam means the Open Curation of Computation And Metadata) is a project that serve as the catalyst for the tools, education, and community-building needed to bring openness, accountability, comparability, and repeatability to software distribution and scientific digital exploration.

**Comment by JeanShuler** [comment]
[collecting _data_170.docx](https://github.com/betterscientificsoftware/bssw.io/files/7069837/collecting._data_170.docx)

**Comment by karbarz** [comment]
PR #1039 Created for this issue.
