### ISSUE TITLE
The Turing Way

### ISSUE THREAD

**Issue by jedbrown** [betterscientificsoftware/bssw.io#1718]
[The Turing Way](https://the-turing-way.netlify.app/index.html) is a wonderful handbook to reproducible, ethical, and collaborative computational and data science. It has tons of overlap with BSSw resources and I was surprised to see it hasn't been linked previously. It contains lovely illustrations and is written in a consistent, approachable style. There are a few details specific to biomedical aspects and it doesn't have an HPC focus, but all the chapters (Reproducible Research, Project Design, Communication, Collaboration, and Ethical Research) are largely applicable to CS&E.

**Comment by markcmiller86** [comment]
Hey @jedbrown thanks for sharing this resource. Just curious...would you be interested/willing in writing a short intro to the resource for us to use here? You could opt, if you wanted, just to put some words here as a comment in this issue and we can take it from there. Maybe just adding a bit more to what you've already written above perhaps sharing a key takeaway or two and how it has influenced your thinking. No worries if you'd rather not but thought we should ask. Again, thanks for sharing.

**Comment by markcmiller86** [comment]
Here is what ChatGPT had to say...

"The Turing Way" is an open-source book that serves as a comprehensive guide to reproducible data science. It is an online collaborative project that brings together the expertise and experiences of various contributors in the field of data science and research.

The book takes its name from Alan Turing, a pioneering mathematician and computer scientist, and aims to embody his values of openness, inclusivity, and rigor. It provides practical advice and best practices for conducting data science projects in a reproducible manner, emphasizing the importance of transparency, openness, and accessibility.

"The Turing Way" covers a wide range of topics related to reproducible data science, including project organization and management, version control, documentation, licensing, data management, and analysis. It emphasizes the use of open-source tools and platforms to facilitate collaboration and sharing of research outputs.

The book also addresses challenges such as ethics, privacy, and bias in data science, and provides guidance on how to navigate these issues responsibly. It encourages researchers to consider the social and ethical implications of their work and promotes the adoption of inclusive and diverse practices.

Overall, "The Turing Way" aims to empower researchers, scientists, and data practitioners to adopt reproducibility as a core principle in their work. It provides practical guidance, resources, and case studies to help readers implement reproducible practices effectively and make their research more accessible, trustworthy, and impactful.
