### ISSUE TITLE
Event Notice: Call for Abstracts - Workshop on Correctness and Reproducibility for Climate and Weather Software

### ISSUE THREAD

**Issue by alperaltuntas** [betterscientificsoftware/bssw.io#1727]
* **What:** Call for Abstracts: Workshop on Correctness and Reproducibility for Climate and Weather Software

* **When:** November 9-10, 2023 

* **Where:** Boulder, Colorado and Online

* **Website:** [*URL for event web site*](https://ncar.github.io/correctness-workshop/)

* **Summary:** This workshop aims to provide a venue to discuss challenges, opportunities, and recent advances in ensuring software correctness and reproducibility for climate and weather modelers, HPC community members, and industry partners. 

* **Description:** 

Abstracts are being accepted now through August 1 for the Workshop on Correctness and Reproducibility for Climate and Weather Software.  This workshop will take place November 9 & 10 at the NCAR’s Mesa Lab and virtually.

**Scope:**

We are soliciting talks related (but not limited to) the following topics:

- Tools and approaches for software testing, debugging, quality assurance, and continuous integration.
- Statistical and ensemble-based approaches for evaluating model consistency and software correctness.
- Software design approaches and development practices for streamlining correctness and reproducibility efforts.
- Formal methods, abstraction, and logical proof techniques for rigorous verification.
- Verifying and validating large-scale applications running on HPC clusters, cloud computing systems, heterogeneous systems, GPUs, etc.
- Other software correctness and reproducibility approaches for facilitating verification and validation.

**Co-chairs:**
- Allison Baker,  National Center for Atmospheric Research
- Alper Altuntas,  National Center for Atmospheric Research

**Committee:**
- Ilene Carpenter, Hewlett Packard Enterprise
- Brian Dobbins, National Center for Atmospheric Research
- Michael Duda, National Center for Atmospheric Research
- Dorit Hammerling, Colorado School of Mines
- Thomas Hauser, National Center for Atmospheric Research
- Karsten Peters-von Gehlen, Deutsches Klimarechenzentrum GmbH (DKRZ)

**Keynote Speakers:**
- Peter Dueben, European Centre for Medium Range Weather Forecasts (ECMWF)
- Steve Easterbrook, University of Toronto
- Dorit Hammerling, Colorado School of Mines
- John Baugh, North Carolina State University

**Comment by markcmiller86** [comment]
Thanks @alperaltuntas. Started PR #1728
