### ISSUE TITLE
Should address community standards 

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#1757]
GitHub maintains a "community standards" report card for every repo. Our's is [here](https://github.com/betterscientificsoftware/bssw.io/community). There are a few items there I think we can address quickly and probably should before ECP sunsets.

**Comment by rinkug** [comment]
@markcmiller86 will try to get this completed.

**Comment by markcmiller86** [comment]
This was completed in #1817 and #1824.  We are all checked-off and in the green for our community standards.

Here is what the new **Community Standards** page looks like...

![Screen Shot 2023-09-26 at 5 37 19 PM](https://github.com/betterscientificsoftware/bssw.io/assets/5720676/348de7e7-5ede-40eb-98dd-ea583e550bf5)
