### ISSUE TITLE
"More" list at the bottom of the following articles

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1758]
(Reported by Ross) There is no "More" list at the bottom of the following articles (at the very least):

* https://bssw.io/items/unit-testing-c-with-catch
* https://bssw.io/items/training-materials-for-research-software-engineering-at-intersect
* https://bssw.io/items/persistent-identifiers-for-software-in-scientific-computing

**Comment by bernhold** [comment]
@rinkug I think the "more" lists are *only* on blogs.

**Comment by rinkug** [comment]
> @rinkug I think the "more" lists are _only_ on blogs.

Thats correct. This can be closed.
