### ISSUE TITLE
missing second contributor and publish date

### ISSUE THREAD

**Issue by clararaubertas** [betterscientificsoftware/bssw.io#176]
http://bss.parallactic.com/resources/keeping-your-vision-fit-for-years-of-software-development is missing publish date and second contributor

**Comment by clararaubertas** [comment]
update: this resource doesn't actually have a second contributor, but I added a second contributor to Kitchen Sink so that we can confirm that's working (seems to be).

Missing publish date fixed as well!

**Comment by sbxchicago** [comment]
Will this solution adjust accordingly to allow more than two names? Damon Macdougal, Clara Raubertas, and Clyde Drexler?

**Comment by clararaubertas** [comment]
It should! Is there an example of resource with > 2 contributors so we can confirm?
