### ISSUE TITLE
How to write a commit message

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1760]
A resource recommended by a participant in the NOAA BSSw tutorial.  Possibly there's other similar advice that could be combined in a single article.

https://cbea.ms/git-commit/

**Comment by markcmiller86** [comment]
Yeah. And, a key part of the trick here is to do micro-commits...that is, commit every little change you do.

**Comment by bartlettroscoe** [comment]
FYI: An identical article is references in an existing bssw.io article:

* https://bssw.io/items/critical-beginner-git-usage-tips#logical-commits

Everyone that uses git for anything needs to read through:

* https://bssw.io/items/critical-beginner-git-usage-tips

> Yeah. And, a key part of the trick here is to do micro-commits...that is, commit every little change you do.

And that is spelled out in:

* https://bssw.io/items/critical-beginner-git-usage-tips#small-commits-rebase-i

**Comment by rinkug** [comment]
@bernhold  and @bartlettroscoe: I thought this was a fun and easy read. Even thought commits are addressed in some of our git articles briefly, I think this would be a good cc article to add to our collection. I can take this up for october unless you object.

If you DONT object, then please vote a thumbs up

**Comment by bartlettroscoe** [comment]
Is there more info on the author here:

* https://cbea.ms/author/cbeams/

or here:

* https://menloservice.sandia.gov/https://twitter.com/cbeams

?

Otherwise, it almost looks like this person is trying to stay anonymous?
