### ISSUE TITLE
CC: Manual Work is a Bug

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#1805]
**Author:** @bartlettroscoe 
**EB Member:** @pagrubel 

From David Rogers (@frobnitzem)  ...

I just stumbled across this article that lays out a good explanation of the reproducibility, documentation, and automation mindset:
"Manual Work is a Bug"

https://queue.acm.org/detail.cfm?id=3197520

The same author has a few more good (and also some hilarious) articles in the automation/devops theme: 

https://www.researchgate.net/scientific-contributions/Thomas-A-Limoncelli-2139171841

**Comment by bartlettroscoe** [comment]
@frobnitzem, yes, automation is about the very definition of modern Lean/Agile DevOps.  But for every automated process, there is overhead to maintain the scripts and processes and do quality control to ensure they keep working.  There is an infliction point where the work to set up automation and maintain it does not justify the cost above the manual process it is replacing.  I am a big proponent of automation (e.g. see #1800, #1454, #711) but even I know there is an inflection point where it does not pay off.  (But you should error on the side of automation because at least it documents the exact process that used to work at one time, even if the process is currently broken.)

**Comment by bartlettroscoe** [comment]
@betterscientificsoftware/bssw-tutorial 

Given our discussions in #1633, I think this would be a good time to write the CC article on this.

**Comment by bartlettroscoe** [comment]
@pagrubel, did you just remove your thumbs up for this article?

**Comment by bartlettroscoe** [comment]
@pagrubel just agreed to review the CC article for March.

**Comment by pagrubel** [comment]
I guess I did; put it back

From: "Roscoe A. Bartlett" ***@***.***>
Reply-To: "betterscientificsoftware/bssw.io" ***@***.***>
Date: Thursday, February 8, 2024 at 11:19 AM
To: "betterscientificsoftware/bssw.io" ***@***.***>
Cc: "Grubel, Patricia A" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [betterscientificsoftware/bssw.io] CC: Manual Work is a Bug (Issue #1805)


@pagrubel<https://urldefense.com/v3/__https:/github.com/pagrubel__;!!Bt8fGhp8LhKGRg!GAt7DuCILlAt99RuOZfrp30u441M6Q--eiZw3awrZD7QYkLtYdcnuovhDc5Y3X-oZ4hzQ_Jzpk3EVEAwt_ScG5J0HQ$>, did you just remove your thumbs up for this article?

**Comment by rinkug** [comment]
@bartlettroscoe : Is this on track to be published soon this month?

**Comment by bartlettroscoe** [comment]
I will get a draft in this week.

**Comment by bartlettroscoe** [comment]
@pagrubel and @rinkug, this is implemented in PR #2089 which should be ready for final review and merging.
