### ISSUE TITLE
CC: SOLID Design Principles

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#1845]
* EB Member: @bernhold 

As mentioned in https://github.com/betterscientificsoftware/bssw.io/pull/1841#pullrequestreview-1680653095, we don't have a CC article about the SOLID Object-Oriented Design principles.  It would be great to have one that could be references, for starters, in the blog article #1841.

@bernhold asked for this in https://github.com/betterscientificsoftware/bssw.io/pull/1841#discussion_r1365913822.

**Comment by bernhold** [comment]
@bartlettroscoe I'd like to put in a vote for getting this article published sooner rather than later (maybe next?).  Thanks

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe I'd like to put in a vote for getting this article published sooner rather than later (maybe next?). Thanks

@bernhold, CC article for this is in:

* #1868 

Should not take too long to look over.
