### ISSUE TITLE
dead links in readme

### ISSUE THREAD

**Issue by gonsie** [betterscientificsoftware/bssw.io#1860]
"What to contribute" and "how to contribute" links in readme and dead.

**Comment by bartlettroscoe** [comment]
Where?  Just the base README.md file?

**Comment by markcmiller86** [comment]
@gonsie thanks for reporting. We'll fix shortly. @bartlettroscoe is the readme file at the top of the repo.

**Comment by bartlettroscoe** [comment]
With the merge of PR #1861 to 'main', the README.md file is updated and I verified that links work as they should starting with the file:

* https://github.com/betterscientificsoftware/bssw.io/blob/f73d0bd21a5cff4d282fb04202deb0545938a774/README.md

I also verified that the links did not work on the pervious version of the file:

* https://github.com/betterscientificsoftware/bssw.io/blob/9351b0095814291e1d04a60b13c1ac8a74e72312/README.md
