### ISSUE TITLE
Need content to replace old i-p.o HowTo articles

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#1877]
**[UPDATE by Rinku on Dec 12 2023] Team members have been assigned what articles they are responsible for  and its being tracked in this [excel tracking file](https://docs.google.com/spreadsheets/d/1DnR7EJ4RScRrnekxz4RQ8F9GBhy8BhvODiPq3JqPagU/edit#gid=842716675).**

A number of BSSw articles link to HowTo (and related) content that was hosted on the old ideas-productivity.org Wordpress site, which is no longer available since we put the Jekyll site into production.  We need to

1) Republish that material on BSSw
2) Change the BSSw articles to point to the new versions

As of 13 Oct, the following BSSw.io articles needed attention:

BSSw URL | Old i-p.o URL
-----------|----------------
https://bssw.io/items/what-is-software-configuration-673277bd-6df9-474a-86c5-7e9ee40d784e | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-ConfigurationWhatIsSoftwareConfiguration-V0.2.pdf
https://bssw.io/items/how-to-write-good-documentation-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationHowToWriteGoodDocumentation-V0.1.pdf
https://bssw.io/items/what-is-good-documentation-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationWhatIsGoodDocumentation-V0.1.pdf
https://bssw.io/items/how-to-enable-performance-portability-for-cse-applications | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-PerformanceHowToEnablePerformancePortability-V0.2.pdf
https://bssw.io/items/what-is-performance-portability-for-cse-applications-eccf9c55-c76a-42cc-81ec-a0d288a3eb0a | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-PerformanceWhatIsPerformancePortability-V0.2.pdf
https://bssw.io/items/how-to-improve-testing-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject-V0.2.pdf
https://bssw.io/items/how-to-improve-testing-for-cse-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject-V0.2.pdf
https://bssw.io/items/what-is-cse-software-testing | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingWhatAreSoftwareTestingPractices-V0.2.pdf
https://bssw.io/items/what-is-revision-control | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-VCWhatIsVersionControl-V0.1.pdf
https://bssw.io/items/how-to-configure-software | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-ConfigurationHowToConfigureSoftware-V0.2.pdf
https://bssw.io/items/what-are-interoperable-software-libraries-introducing-the-xsdk | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-InteroperabilityWhatAreInteroperableSoftwareLibraries-V0.2.pdf
https://bssw.io/items/how-to-do-version-control-with-git-in-your-cse-project | https://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-VCHowToVersionControlwithGit-V0.2.pdf

**Comment by rinkug** [comment]
Some tips to update how-tos and convert the into blogs

- Add deck, title, authors, publication date (you can put Nov XX 2019 as publication date if there is none in the file), meta data. Remove any statement at the bottom of the how-to article that says “This work is funded by DOE etc etc). As you move how-tos to markdown format, remember that most headings in the blog articles start with “###” as first level heading.
- Assign the correct track (Track: how to)
- Move the short article/how-to file it to blogs folder
- Update the links that point to the short article from the corresponding what-is article, if there is one. The way to update the link is “../Blog/short-article/howto.md”
- Update the [excel tracking file](https://docs.google.com/spreadsheets/d/1DnR7EJ4RScRrnekxz4RQ8F9GBhy8BhvODiPq3JqPagU/edit#gid=842716675)

**Comment by bartlettroscoe** [comment]
Re-opening because it was closed by accident because of the merge of #1905.

**Comment by bartlettroscoe** [comment]
> Some tips to update how-tos and convert the into blogs

@rinkug, I have not been able to start on my assigned articles yet.   How late are people working before the holiday break?  I will be working up to Friday 12/22/2023 so I should have some time to get this done next week if that is okay?
