### ISSUE TITLE
Remove commit message spell check

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1916]
We have a commit message spellcheck which is causing confusion. Changing spelling of commit message through github web interface is not document well. I suggest that we move spell check from commit message but retain it for the actual article.

**Comment by rinkug** [comment]
@bartlettroscoe : can you take a look into this?

**Comment by bartlettroscoe** [comment]
@rinkug, if others are okay with removing the spell checking of the commit messages, that is fine with me.  If you are using only GitHub to make changes, I don't know how to fix spelling errors in commit messages.  (Locally, that is easy to do using `git rebase -i <base-commit>`.)

**Comment by rinkug** [comment]
Thank you for your promptness
