### ISSUE TITLE
Update IDEAS ECP CC

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1919]
(From David B, dated Dec 4, 2023) 

1. It might be appropriate to update it with the webinar and the CiSE paper (maybe link to the arXiv version until it is published – or maybe just wait).  I don’t know whether it is actually worth keeping the reference to the old report – here and elsewhere (for the SC23 tutorial, I changed the reference on the lightbulb slide we use to introduce IDEAS-ECP to the arXiv paper from the report).
2. We should change “IDEAS Software Productivity project” to “IDEAS Productivity project”.  The latter is a phrase we use frequently.  The former, I don’t recall it ever intentionally being used in any project writing that I’ve been involved in.  Using the phrase consistently will help people actually find it when they search.

**Comment by pagrubel** [comment]
Here is the DOI: [10.1109/MCSE.2024.3383799](https://doi.ieeecomputersociety.org/10.1109/MCSE.2024.3383799)
