### ISSUE TITLE
Handlings “blog” vs. “original article”?

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#1975]
**Action items:** 

- [x] [What to contribute](https://bssw.io/pages/what-to-contribute-content-for-better-scientific-software) says original article (which blog mentioned under it). We need to clean this up 
- [ ] The [EB docs](https://betterscientificsoftware.github.io/bssw.io/bssw_content_overview.html) confirms to What to contribute.
- [x] We also use different labels in our github for this topic. @rinkug took care of this by (1) add word "-deprecated" to the "content: article" and "content:how-to" labels. Add "content:blog" to all open issues with such labels.

**Discussion:** We now have tracks feature enabled, so can we make things consistent between the word “blog”, “original article”? Everything is now list on the [blog page](https://bssw.io/blog_posts).

For ex: 
(1)	https://bssw.io/ says “Blog” in the menu bar
(2)	[What to contribute](https://bssw.io/pages/what-to-contribute-content-for-better-scientific-software) says original article (which blog mentioned under it)
(3)	The [EB docs](https://betterscientificsoftware.github.io/bssw.io/bssw_content_overview.html) confirms to What to contribute 
(4)	[Github directory](https://github.com/betterscientificsoftware/bssw.io/tree/main/Articles) says Articles/Blog
(5)  We also use different labels in our github for this topic
	

My recommendation is that we call blog as well as original articles as “blogs” and remove the original articles terminology.

**Comment by markcmiller86** [comment]
What about the GitHub labels `content: article` and `content: blog`?

**Comment by bernhold** [comment]
I suggest that we use the term blog generally.  When we're talking about what to contribute, we can explain the scope of blogs -- that they include most forms of original content.

For labels, I do not think `content: article` helps us.  I think we should continue to think in terms of blogs, curated, and events.  `content: what is` is also useful on rare occasions.  I think we should deprecate article, and how-to.

**Comment by markcmiller86** [comment]
I am in agreement with @rinkug and @bernhold
