### ISSUE TITLE
CC for "Getting an RSE org started" doc

### ISSUE THREAD

**Issue by ksbeattie** [betterscientificsoftware/bssw.io#1999]
Author: @ksbeattie 
EB member: @rinkug 

A first CC for me on: 
[Getting Started with the RSE Movement within your Organization: A Guide for Individuals](https://zenodo.org/records/10436166)

Targeted for March

**Comment by rinkug** [comment]
@ksbeattie : EB docs for this article: https://betterscientificsoftware.github.io/bssw.io/bssw_styling_curated.html
