### ISSUE TITLE
Possible new topic: User Experience Design

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#2010]
The LBNL STRUDEL project <https://strudel.science> is starting to do outreach and hold some events.  I want to post a cc for the project as well as events for their upcoming webinar and hackathon.  They focus on user experience design for scientific software.  We could put it under the Better Planning --> Design topic, but it seems like it might be worth opening a distinct topic for UX Design.

The topic could be "User Experience Design" or "User Experience" or "User Experience (UX)" or something like that.  I don't have strong feelings.

**Comment by markcmiller86** [comment]
> The topic could be "User Experience Design" or "User Experience" or "User Experience (UX)" or something like that. I don't have strong feelings.

UX has certainly been popularized a lot lately. Its different from other design considerations...often developers will do things one way to satisfy a UX need and a wholly different way to satisfy a developer need.

Is there any reason we should be *judicious* about starting new topic labels?

**Comment by bernhold** [comment]
Personally, I don't think we need to be that concerned about adding new topics as long as we have content for them.  Though if the number of topics becomes overwhelming it might be a problem to scan through them for people browsing that way.

**Comment by rinkug** [comment]
@bernhold  Its ok to add a new topic as long as we expect more articles for fall under it (or we recategorize some existing articles to fall under it).
