### ISSUE TITLE
Virtual workshop on multiproject CI/CD.

### ISSUE THREAD

**Issue by ryanmrichard** [betterscientificsoftware/bssw.io#2048]
* **What:** Virtual Workshop on Multiproject CI/CD
* **When:** June 14, 2024
* **Where:** Online
* **Organizers:** Ryan M. Richard
* **Website:** https://multiprojectdevops.github.io/workshop_reports/virtual_workshop1/
* **Summary:** A chance for the community to discuss problems and solutions pertaining to managing CI/CD for multiple projects.
* **Description:** 

With increasing focus on modular scientific software, many teams are finding themselves managing multiple projects. Following best practices, each project will rely on continuous integration/continuous deployment (CI/CD) for ensuring reliable software is available to users. Since these projects are managed by a common set of developers there is a tendency for the various CI/CD workflows to have common needs and therefore common solutions. While there are a number of best practices for managing CI/CD for a single project, resources for managing multiple projects are less widespread. The purpose of this virtual workshop is to solicit feedback from the community regarding managing multiproject CI/CD.

The organizers welcome contributions in two forms:

- Contributed presentation, or
- Request for Information

Contributed presentations should focus on existing multiproject CI/CD solutions and/or on lessons learned in managing CI/CD for multiple projects. Abstracts for contributed presentations can be submitted when registering. Please use [this](https://multiprojectdevops.github.io/workshop_reports/virtual_workshop1/rfi/) form for replying to the RFI. Abstracts should be submitted before May 30, 2024. RFIs will be accepted up to the day of the conference.

**Comment by bernhold** [comment]
@ryanmrichard thanks very much for passing this along.  Would it be possible for you to resubmit this in the form of a pull request?  An event like https://github.com/betterscientificsoftware/bssw.io/blob/main/Events/2024-04-cw24-workshop.md is going to be a pretty good template to follow.  We'll work with you to get it into final form and publish it.  Thanks
