### ISSUE TITLE
CC: Technical Debt in Practice: How to Find It and Fix It

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#2194]
I have been reading the book [Technical Debt in Practice: How to Find It and Fix It](https://www.amazon.com/Technical-Debt-Practice-How-Find/dp/0262542110/ref=asc_df_0262542110?mcid=85e6c3ae9fa838adb777ff20c2fb2cc6&hvocijid=15264663257703520049-0262542110-&hvexpln=73&tag=hyprod-20&linkCode=df0&hvadid=692875362841&hvpos=&hvnetw=g&hvrand=15264663257703520049&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9008023&hvtargid=pla-2281435177858&psc=1).  I have read enough to be able to recommend it.  I have actually learned more than I thought I would about the topic.  I will highlight that in my CC article.

**Comment by bartlettroscoe** [comment]
@rinkug, I would like to write this CC article for Dec.

**Comment by bartlettroscoe** [comment]
FYI: I ran the Google search [site:bssw.io "technical debt in practice"](https://www.google.com/search?q=site%3Abssw.io+%22technical+debt+in+practice%22&sca_esv=3f02ea0791642f05&rlz=1C1GCEA_enUS1072US1072&sxsrf=ADLYWILS3S147qImAxeiDzV94M_ico9ZWQ%3A1731610722990&ei=Ykg2Z8eNPOuDm9cPjtz_iAY&ved=0ahUKEwjHxqHQwNyJAxXrweYEHQ7uH2EQ4dUDCBA&uact=5&oq=site%3Abssw.io+%22technical+debt+in+practice%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiKXNpdGU6YnNzdy5pbyAidGVjaG5pY2FsIGRlYnQgaW4gcHJhY3RpY2UiSIgLUABYAHACeACQAQCYAQCgAQCqAQC4AQPIAQCYAgCgAgCYAwCIBgGSBwCgBwA&sclient=gws-wiz-serp) and nothing comes up.

There are 15 current pages on bssw.io that contain "technical debt" as shown [here](https://bssw.io/items/search?search_string=technical+debt).

**Comment by markcmiller86** [comment]
I think you want to search for [`"technical debt"`](https://bssw.io/items/search?search_string=%22technical+debt%22) (e.g. in quotes). The link above didn't include the quotes.

**Comment by bartlettroscoe** [comment]
> I think you want to search for [`"technical debt"`](https://bssw.io/items/search?search_string=%22technical+debt%22) (e.g. in quotes). The link above didn't include the quotes.

I must have pasted the wrong bssw.io URL.  If you don't use quotes in this query:

* https://bssw.io/items/search?search_string=technical+debt

you get 135 articles.

If you put in the quotes "technical debt" in this query:

* https://bssw.io/items/search?search_string=%22technical+debt%22

you get 15 articles.

**Comment by rinkug** [comment]
@bartlettroscoe : How is this cc coming along?

**Comment by bartlettroscoe** [comment]
@rinkug, the PR #2211 should be ready to review.

@markcmiller86, @ksbeattie, or @pagrubel, any of you have time to review?  (I am also asking people inside of SNL to review as well.)
