### ISSUE TITLE
Article idea: Curated links from Charles Ferenbaugh webinar

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#255]
Author: Rinku
EB member: Jean

In Charles's HPCBP webinar, he ended with a fair number of resources that he'd found useful.  We should add these to BSSw.

**Comment by bernhold** [comment]
https://ideas-productivity.org/wordpress/wp-content/uploads/2018/01/webinar014-slides.pdf slides 17-18

**Comment by pagrubel** [comment]
I was wondering if Charles might wanted to write a blog article about software engineering and mentioned it to him. He's rather busy so I thought I'd ask again after the close of the FY.

**Comment by bernhold** [comment]
Hi @pagrubel, just to make sure you know, Charles has done one blog post for us -- related to his webinar, actually.  That's not to say that we wouldn't welcome another.

And just to ensure that this particular ticket is clear, it is not about soliciting another blog article, but rather looking over the list of resources at the end of his webinar and producing curated content articles for most/all of those.

**Comment by bernhold** [comment]
@rinkug @JeanShuler I wanted to understand whether work on this article has actually started (i.e. it is "in progress") so that we can place it correctly on the project board.  Thanks

**Comment by rinkug** [comment]
Most of the relevant links are already independent articles. Hence closing this.
