### ISSUE TITLE
BSSw should have a social media presence

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#257]
Capturing an issue that @danielskatz raised in email: 
> Where are the social media links on this site?
> Where are the twitter and facebook accounts that should be posting updates to the site, and reposting relevant work? 

It would be nice to have someone who is a little savvy with social media volunteer to help with this.

**Comment by rinkug** [comment]
We should discuss this for FY20.

**Comment by bernhold** [comment]
As part of IDEAS Outreach strategic planning, @bernhold will be organizing a meeting with at least 1-2 communications teams to help us as a project overall figure out how to move forward with social media.  Anyone who wants to participate in that discussion should contact me ASAP.  Otherwise, we'll bring back a summary of those discussions to this group.

**Comment by danielskatz** [comment]
Do you want me to participate?  I'm fairly good at this stuff, in a technical context that might be different than the typical communications team.  I do feel like BSSw is not well-known outside DOE, and part of it is this lack of a social presence.

**Comment by gpieper** [comment]
I  am interested.
Gail

**Comment by bernhold** [comment]
@danielskatz thanks for offering to help.  No offense to you, but we were going to start by seeking advice from some communications professionals, who do this for a living, as a starting point.

Once we have their advice, then I thought we'd follow up with some internal discussions within the project, including trying to tap those (few) who are active in social media.  If you're willing, I'd like to try to include you at that point.

**Comment by danielskatz** [comment]
that's fine, but I would say that many of us see this as a key part of our work, we just do it in part for ourselves and for our volunteer organizations, but we don't get paid specifically for it :)

**Comment by rinkug** [comment]
We have same handle on threads/Mastadon now. Nothing has been posted on it.
@haikudeb to generate active twitter/X.

**Comment by danielskatz** [comment]
What is the mastodon handle - link to the mastodon home for the account?

**Comment by rinkug** [comment]
We did somewhat start on this but this will likely take a back seat for near future. Can we close this issue?
