### ISSUE TITLE
BLT - Build, Link, Triumph

### ISSUE THREAD

**Issue by white238** [betterscientificsoftware/bssw.io#259]
BLT is composition of CMake macros and several widely used open source tools assembled to simplify HPC software development.  It is aimed to reduce the common tasks that are required to get a full fledged CMake build system for HPC, Linux, OSX, and Windows.  It simplifies the setup of MPI, CUDA, OpenMP, and ROCm.  The tutorial has easy to follow examples that will get you from nothing to a workable build system that enables MPI and CUDA in under an hour.

Github: https://github.com/LLNL/blt
Tutorial: http://llnl-blt.readthedocs.io/en/latest/

**Comment by maherou** [comment]
We would be happy to receive this contribution.  Please follow the contribution guidelines found in the README.md page.  Thank you for your willingness to contribute.

**Comment by rinkug** [comment]
Is this still of interest?

**Comment by markcmiller86** [comment]
Yes, this would be a useful article but perhaps not in isolation. Maybe better to discuss BLT along with one or two other such systems (TriBits @ SNL and one other I am unaware of). I just gave my thumbs up.

**Comment by rinkug** [comment]
This is an interesting topic, but we may need an author for  this (and for the other systems that Mark mentions above)

**Comment by bernhold** [comment]
This is labeled as both a blog and curated content.  Can we decide?  Personally this looks more like cc to me.
