### ISSUE TITLE
Article(s): "HPC Carpentry" lessons

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#261]
Pointers to offerings of HPC-focued educational material in the Software Carpentry style.  This is meant to be distinct from other HPC-focused educational material, e.g., slideware.  Not sure what is the most effective (and least political) way to express this.

Sources so far:

- https://hpc-carpentry.github.io/
- http://coderefinery.org/lessons/

Others, please comment with other relevant sources.

From ticket #249, adding the following to be merged her
https://www.futurelearn.com/courses/supercomputing/
Mentioned in https://www.software.ac.uk/news/free-supercomputing-mooc-starting-15th-january-2018

**Comment by jarrah42** [comment]
Not quite sure what is being proposed here. Could you be more specific? Are you suggesting content on how to create educational material (which seems very general) or the actual material itself?

**Comment by bernhold** [comment]
@jarrah42 I am suggesting we point to content.  Though material on how to create educational content would also be a good thing.

I realize that some of the lessons in the hpc-carpentry space may not be quite in our real scope, but we could pick and choose and/or just reference the whole thing.  The former would require periodic review to update for new lessons.  The latter would require less maintenance.

**Comment by rinkug** [comment]
https://hpc-carpentry.github.io/
http://coderefinery.org/lessons/
These are good resources

https://www.futurelearn.com/courses/supercomputing/
For the above link, the archives for this particular course are not available on the website, correct? I could not find them easily enough.

**Comment by bernhold** [comment]
@rinkug, FutureLearn seems to be based on delivering content "on demand" rather than providing archives of their materials.  Maybe this puts it into a different category from the others?  I'm not sure.

**Comment by pagrubel** [comment]
"I am suggesting we point to content. Though material on how to create educational content would also be a good thing."
I think this is a good idea, would we want one article with pointers to content in the carpentries site?

**Comment by JeanShuler** [comment]
There is great content in the that is already being used by those who know about it.  I think we should have an article pointing to the content for python, and Git.  They are heavily used at most sites.

**Comment by pagrubel** [comment]
@gonsie Are you working on this?

**Comment by gonsie** [comment]
@pagrubel I was, but couldn't quite figure out how to best organize the information. Feel free to take it.

**Comment by markcmiller86** [comment]
I will work on this one for Sept

**Comment by markcmiller86** [comment]
Sorry, I think I mean October
