### ISSUE TITLE
Add online programming courses curated link.

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/bssw.io#29]
Author: Rinku (@rinkug)

The following link has a nice summary of free online courses in computer programming:

https://medium.freecodecamp.com/370-free-online-programming-computer-science-courses-you-can-start-this-month-fc5b9867769e#.ff8i6qd83

[Rinku] Updated article (aug 2020) on the same topic can be found at https://www.freecodecamp.org/news/free-online-programming-cs-courses/

**Comment by rinkug** [comment]
This is a good resource. We need a nice paragraph or two summarizing what the resource actually is. Thumbs up from  me

**Comment by rinkug** [comment]
We need an EB  member to shepherd this

**Comment by rinkug** [comment]
A new updated list as of Aug 2020, which is on the same domain topics but more recent course links: https://www.freecodecamp.org/news/free-online-programming-cs-courses/

Some courses on the original 370 courses links are not available, hence the new link is better.
