### ISSUE TITLE
Guide to improving reproducibility in scientific software

### ISSUE THREAD

**Issue by jarrah42** [betterscientificsoftware/bssw.io#31]
Author : @oamarques
EB member: Rinku
There a quite a few groups working on reproducibility in science, with a focus on scientific software. However, there doesn't seem to be much coordination between them, nor any obvious place to go for a guide on how to get started or what are best practices. This page could provide a starting point for scientists/developers interested in trying to improve this aspect of their work. It could provide links to the broader community, as well as a survey of the current best practices and links to get people started.

**Comment by maherou** [comment]
Greg,

This is a good idea.  Please go ahead.  I would like to review what you develop.  

Here are some thoughts:

I have had a lot of involvement in reproducibility efforts for the past 7 years.  I started the ACM Replicated Computational Results (RCR) initiative, am involved in the ACM advisory committee on reproducibility and am in charge of reproducibility efforts for SC 17 and SC 19, and have worked with AAAS efforts through the Arnold Workshop on Reproducibility and a subsequent Science Magazine article.  

Some other people who are heavily involved are: Michela Taufer, Lorena Barba, Victoria Stodden and Dan Katz.

Grigori Fursin has led efforts for conferences (CGO, PPoPP, PACT, RTSS).  He has a good page:
http://fursin.net/reproducibility.html

The ACM RCR effort (ACM TOMS, TOMACS) is described here:
http://toms.acm.org/replicated-computational-results.cfm 

ACM Badging efforts are described here:
https://www.acm.org/publications/policies/artifact-review-badging 

SC17 efforts:

http://sc17.supercomputing.org/submitters/technical-papers/reproducibility-initiatives-for-technical-papers

**Comment by curfman** [comment]
Also, last week at the CSE17 conference, Randy LeVeque mentioned
https://reproduciblescience.org

**Comment by rinkug** [comment]
I like the idea. It would be useful is the cc  article provides a good context rather than just links

**Comment by bernhold** [comment]
@jarrah42 @rinkug I wanted to understand if this article was really "in progress" or not, so that we can make sure it is in the correct column of the project board.  Thanks

**Comment by jarrah42** [comment]
I think this is in the "I'd like to do it time permitting but I have no time currently" category. I'm fine if you want to close it out and I can open a new one if I get some spare time.

**Comment by bernhold** [comment]
I don't want to close it, but I will move it back to Ready to Write as a more accurate reflection of the situation.  Thanks

**Comment by rinkug** [comment]
@jarrah42 : @oamarques would like to try this article if you have no issues.

**Comment by rinkug** [comment]
@oamarques: I am not sure if you still has interest in writing this? Please confirm a date. Or lets close this.

**Comment by jarrah42** [comment]
I'm fine with closing this. I don't have the cycles now to do this.
