### ISSUE TITLE
Add article with pointer to Pareto principle discussion

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/bssw.io#32]
https://medium.com/the-mission/extraordinary-results-are-disproportionately-created-by-fewer-actions-d0488a62aee3#.1alebqx03

**Comment by rinkug** [comment]
I did like this article. Its points to improving developer productivity by focussing on the correct things in your career. Might be useful if one would follow some of these principles.

**Comment by markcmiller86** [comment]
I read the article. I think its interesting/useful from a personal productivity perspective. I think I might title it "Make the 80/20 Rule Work For You" and then refer to Pareto by name in the CC article itself. The CC article could also mention that research demonstrates that this rule also applies to things like bugs in software (80% of the bugs come from 20% of the code), software development costs (20% of the features amount to 80% of the costs), etc.

**Comment by bartlettroscoe** [comment]
The 80/20 rule is a well-known principle in software development.  Don't know that an article focused on this is all that valuable.  Just read Code Complete, 2nd edition.

**Comment by bernhold** [comment]
@bartlettroscoe it is a lot to read a whole book.  I think a standalone article about Pareto Principle could be useful.

**Comment by pagrubel** [comment]
I agree with David, but I really need to read Code Complete

**Comment by pagrubel** [comment]
The article has been removed. Do we have another one for this or should we close the issue?
