### ISSUE TITLE
Video: Scaling Yourself as a Software Developer

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#327]
Author:   @pagrubel 
EB member: @markcmiller86 

http://blog.martinig.ch/videos/scaling-yourself-as-a-software-developer/

has received positive feedback from a number of IDEAS participants and perhaps should be a curated content item.
If we do that, we might want to find a more direct link to the video (I think it is on YouTube).  Nothing against the blog where I found it, but it is one more level of indirection that could disappear unexpectedly.

**Comment by markcmiller86** [comment]
Here's the direct YouTube link, https://youtu.be/IWPgUn8tL8s

**Comment by maherou** [comment]
I showed this video in my Agile and Efficient Software elective course.  Great content.  I enjoyed seeing it for a second time as it triggered new ideas to be effective and efficient.  The presenter also has some excellent speaking techniques.  Very good stuff.

If no one else wants first dibs, I am happy to write this up.

**Comment by bernhold** [comment]
Mike I think it would be great if you get a chance to write this up.  I'll assign it to you.

And if someone else gets motivated and wants to grab it before you do, I'm sure no one will object.

**Comment by rinkug** [comment]
@maherou - still interested in writing this article?

**Comment by bartlettroscoe** [comment]
I watched this as well and I think he made a lot of good points.  The big take-away for me was not letting email suck up all of your time.

**Comment by rinkug** [comment]
Might be good if article mentions the 2-3 takeaways from this 45 minute video. Mark might spend some time on this in early november. If someone has time earlier and interest, let us know

**Comment by pagrubel** [comment]
I discussed this with Mark and will take it on

**Comment by pagrubel** [comment]
Closing this issue see PR #721 Add Scaling Yourself as a Software Developer cc article

**Comment by pagrubel** [comment]
Closing this issue see PR #721 Add Scaling Yourself as a Software Developer cc article

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211
