### ISSUE TITLE
EPIC: Improve BSSw contribution process and stability of BSSw site using strict reviewed PRs

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#330]
CC: @markcmiller86, @curfman, @bernhold, @maherou 

## Child Issues

* #702
* #738

## Description

Picking up from the conversation in PR #329, this Issue is to consider and scope out a change to the contribution process for the BSSw site through this GitHub repo to achieve:

* Ensure that the 'master' in the BSSw github repo is always deployable 
* Ensure that all contributions are complete are carefully reviewed before being merged to 'master'
* Make it easy to review and provide specific targeted comments about contributions
* Avoid having to manually hack files generated by the `wikize_refs.py` script.
* Teach people the basic GitHub PR contribution workflow in a non-stressful way

The key to achieving by using the basic GitHub PR workflow where the 'master' branch is locked down and all PRs must have a least one other person sign off on them :-)

To allow for previewing articles, one can use an ["integration test branch"](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#heading=h.2r0g9kvx5b2a) called something like 'preview-content' (or using the standard name 'next').  The way this works is that you merge the topic branch for a PR that you want to preview on the website into the 'preview-content' branch and then the BSSw preview site is taken off of 'preview-content' instead of 'master'.  Then work in continued on the topic branch until all reviews are done, all tweaks are complete, etc.  When the topic branch is 100% ready to publish, then the topic branch is merged to 'master' by merging the PR.

Another thing that would improve this process is for the website to automatically not render pages that end with `-src.md`.  That way, all changes to the content could be made in the `<base-name>-src.md` file and used to generate the `<base-name>.md` file using the script `wikize_refs.py`.  (Or we could find another way to address this perhaps but it needs to be addressed if you look at the mess the process was, for example, #377).

The IDEAS-ECP level project board issue for this is:

* https://github.com/bernhold/ideas-ecp-overview/issues/59

# Tasks

* Create PR to modify `HowToContribute.md` with suggested PR process

* Submit one or more curated content submissions as PR to demonstrate the different processes

**Comment by bartlettroscoe** [comment]
FYI: I just created the PR #332 completely on the GitHub site.   That was created in my GitHub fork proving that other users can do this as well, even if they don't have push access to this main BSSw github repo.

I will document how I did that in a PR for an updated `HowToContribute.md` file.

I will next add another issue and PR by creating a branch directly in this main bssw github repo which IDEAS team members can use and can make their work a little easier (with a few less steps).

**Comment by bartlettroscoe** [comment]
Related to this is the more comprehensive process being outlined [here](https://docs.google.com/document/d/19PYkAKMunpJAzchfKEhdBrjtq0X_lf69cDNz3iTXfzU/edit?usp=sharing).

**Comment by markcmiller86** [comment]
Just some quick remarks...

- The `wikize_refs.py` script and associated part of the workflow was created primarily to deal with posts wanting to include a list of citations much like wiki pages do as in [this post](https://bssw.io/blog_posts/celebrating-apollo-s-50th-anniversary-when-100-flops-watt-was-a-giant-leap). IMHO, it is a useful *optional* capability to support some additional formalism in publication but is also not essential. When it is used, it should really the be *last* step just prior to going live instead of, for example, before publication metadata is added. In particular, the specialization of the `-src.md` filename should be eliminated.
- In the workflow proposed here, what happens when multiple EB members are working with different content on the `preview-content` branch? Neither can merge to master until both are ready, right? Or, do we maintain two parallel branches; `master` and `preview-content` and essentially duplicate the commits to `master` for a given bit of work once the commits to `preview-content` are deemed approved?
- What about the process of adding publication metadata; `categories`, `topics`, `tags`, `level`? Can't that be automated with some CI processes?

**Comment by bartlettroscoe** [comment]
>  In particular, the specialization of the -src.md filename should be eliminated.

I disagree.  The process to edit a file after publication should be identical to as it is before publication.  That is like telling people to edit the binary file after you release a library.

> In the workflow proposed here, what happens when multiple EB members are working with different content on the `preview-content` branch? 

This is all explained in [Addition of throwaway integration test branches](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#heading=h.2r0g9kvx5b2a) and the usage of the `next` branch in [gitworkflows(7)](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitworkflows.html) (the latter comes with git, try `man gitworkflows`).

> Neither can merge to master until both are ready, right?

Incorrect.  The PR branches can and should be independently merged to 'master'.  That process is called "graduation".

> Or, do we maintain two parallel branches; master and preview-content and essentially duplicate the commits to master for a given bit of work once the commits to preview-content are deemed approved?

It is critical that one understands the workflow described in [Addition of throwaway integration test branches](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#heading=h.2r0g9kvx5b2a).  It answers all of these questions.

Should I set up a short presentation to explain this workflow building block?  (Don't feel bad, I did not know about this workflow until Jed Brown told me about it and then I researched it myself.)

**Comment by markcmiller86** [comment]
> > In particular, the specialization of the -src.md filename should be eliminated.
> 
> I disagree. The process to edit a file after publication should be identical to as it is before publication. That is like telling people to edit the binary file after you release a library.

Here's what I am saying
- There really should **not** be a *process* for editing files **after** publication.
- We should improve the citation workflow to ensure it works without requiring special editing. What should exist in the repo should be the one and only *original* markdown file and what should get published to the live site is the wikized version and no humans should be in that loop.

**Comment by markcmiller86** [comment]
> To allow for previewing articles, one can use an ["integration test branch"](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#heading=h.2r0g9kvx5b2a)

I wonder if this might be overkill for a site wholly aimed at publishing content?

Do we really anticipate *incompatabilities* or other issues associated with *integration* that such a workflow is designed to accomodate?

Isn't the key issue whether or not new content gets published correctly and, if so, the main question is whether any given update is compatable (or not) with the live site publication stuff (steps that occur after something is merged on GitHub).

Wouldn't it be easier to simply maintain two parallel branches; `master` and `preview` and have authors and EB members do all the real work to get content ready with PRs and commis to `preview`, have the preview site then operate from the `preview` branch (as you already describe) and then just *replay* (via cherry-picking) the set of changes for a given bit of content onto `master` once that content is deemed good on `preview`?

**Comment by bartlettroscoe** [comment]
@markcmiller86 

> I wonder if this might be overkill for a site wholly aimed at publishing content?

I think you are imagining that this workflow is more complex that it is.  Let's just meet over WebEx and discuss this and is much simpler and less work that what you a suggesting at the end of your last comment.

**Comment by bartlettroscoe** [comment]
> There really should not be a process for editing files after publication.

Interesting.  Then how to we fix issues with them or improve them given feedback?  Can we version them?

> We should improve the citation workflow to ensure it works without requiring special editing. What should exist in the repo should be the one and only original markdown file and what should get published to the live site is the wikized version and no humans should be in that loop or after it.

That would be great.  But that wold require that SandBox automate the generation of the files running the `wikize_refs.py` tool on the `*.md` files that it detects that it needs to.  And of course, we need a way to generate those files ourselves to view what they look like when rendered and to work out bugs.

**Comment by bernhold** [comment]
As a practical matter, it is rare that we revise blogs after they're published.  I'm not saying we shouldn't, just that we haven't.

It is reasonable to think about CC and original articles being updated as things change.  Events probably not so much.

**Comment by bartlettroscoe** [comment]
> As a practical matter, it is rare that we revise blogs after they're published. I'm not saying we shouldn't, just that we haven't.

Don't want to get side-tracked on the generated file issue but we need to find a smoother process that what exists now.  This is harder than it should be and it does not respect the GitHub workflow.

**Comment by bartlettroscoe** [comment]
> Wouldn't it be easier to simply maintain two parallel branches; master and preview and have authors and EB members do all the real work to get content ready with PRs and commis to preview, have the preview site then operate from the preview branch (as you already describe) and then just replay (via cherry-picking) the set of changes for a given bit of content onto master once that content is deemed good on preview?

No, it is generally consider easier and better to use the merge workflow.  As stated in [gitworkflows(7)](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitworkflows.html):

> There are two main tools that can be used to include changes from one branch on another: git-merge(1) and git-cherry-pick(1).
>
> Merges have many advantages, so we try to solve as many problems as possible with merges alone. Cherry-picking is still occasionally useful; see "Merging upwards" below for an example.
> 
> Most importantly, merging works at the branch level, while cherry-picking works at the commit level. This means that a merge can carry over the changes from 1, 10, or 1000 commits with equal ease, which in turn means the workflow scales much better to a large number of contributors (and contributions). Merges are also easier to understand because a merge commit is a "promise" that all changes from all its parents are now included.

In general, project that are sloppy about their usage of branches almost have to use the cherry-pick workflow.  But given the nature of the BSSw site with everyone working on PRs, this should never be a problem.

**Comment by rinkug** [comment]
I think there are two types of users who use the master branch, right now.

1. Content contributors: Users submits a PR. EB member helps them commit the changes to the "preview" branch and then creates perfect content on the "preview" branch through multiple iterations. While  content is perfect, a PR with the entire new content is pushed tomaster branch.

Above can be captured in below Flow:
1. User merges PR to preview branch (does PR close automatically after merge?)
2. Preview done and modifications outlined based on preview.
3. User either reopens old PR and submits a new PR to preview branch
4. Repeat steps 2-3 until preview is perfect
5. User submits latest perfect PR to master

Questions:
When we try to periodically update the "preview" (which may have many many PRs) to be in sync with "master" (which may have completed PRs, other site modifications), we may have many conflicts to be resolved. How messy is this going to be?

2. Folks (like me, Lois, David) who need to "currently" update the  website at many place while we work with styling, formatting. If  we work on the preview, it would be too time consuming to create a 
PR for every spelling, typo we see. So, we continue working directly on master for the timebeing. Hopefully, eventually in the future,  we will be done with all formatting type modifications and we can just work using PRs

**Comment by bartlettroscoe** [comment]
@rinkug, I think there is some confusion about how the basic process described in  ["integration test branch"](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#heading=h.2r0g9kvx5b2a)  works.  Where should I document that workflow in terms of git commands to remove ambiguity?

**Comment by rinkug** [comment]
@bartlettroscoe Can you put this in comments in this issue discussion?

**Comment by bartlettroscoe** [comment]
> Can you put this in comments in this issue discussion? or you can attach a file in this issue discussion?

Can't edit things in a comment very well.  A PR allows you to have content that can be reviewed and commented on (and perhaps eventually merged and displayed).

**Comment by rinkug** [comment]
IMHO, an option other than creating md files in the project repo is feasible..because if we start using repo for discussion files than it may become difficult to manage..

**Comment by bartlettroscoe** [comment]
> IMHO, an option other than creating md files in the project repo is feasible..because if we start using repo for discussion files than it may become difficult to manage..

Why? Everyone would just edit the same *.md file on the PR branch to make changes.  There is no merging.  It is about the perfect mechanism for creating content like this I think.

**Comment by rinkug** [comment]
> > IMHO, an option other than creating md files in the project repo is feasible..because if we start using repo for discussion files than it may become difficult to manage..
> 
> Why? Everyone would just edit the same *.md file on the PR branch to make changes. There is no merging. It is about the perfect mechanism for creating content like this I think.

Ok, I misunderstood. Please create the PR and *.md file. Thank you so much.

**Comment by bartlettroscoe** [comment]
FYI: Documentation of the proposed 'preview' workflow are in PR #436 and the latest can be seen at:

* https://github.com/bartlettroscoe/betterscientificsoftware.github.io/blob/330-preview-pr-workflow/Site/PullRequestPreviewBranchWorkflow.md

Please provide comments and make edits in PR #436.

**Comment by bartlettroscoe** [comment]
@bernhold, should we copy and paste your recent emails on your progress on this Issue in this Issue?

**Comment by bartlettroscoe** [comment]
Assuming Sandbox is running a newer version of git (version 2.0+ should be new enough but I can check to be sure), the most robust commands to update the local ‘preview’ branch from the ‘preview’ branch on GitHub in order to update the ‘preview’ site are:

```
$ git fetch origin     # origin == git@github.com:betterscientificsoftware/bssw.io.git
$ git reset --hard HEAD  # Remove any local uncommitted changes that might exist
$ git checkout -B preview --track origin/preview   # Will checkout the ‘preview’ branch even if it already exists
```

The above commands will put the local repo on the ‘preview’ branch and will match the ‘preview’ branch on the bssw.io GitHub repo no matter the state of the local repo.  This will also allow the ‘preview’ branch to get rebuilt over and over again and hard pushed to the GitHub repo and allow for things to run smoothly to update the ‘preview’ site.

In addition, if the ‘preview’ site should get built from a clean source tree, you can also call ‘git clean -xdx’ just before the ‘git reset --hard HEAD’ command above.  That will result in a local ‘preview’ branch and the state of the local repo identical to if you deleted the local repo and cloned in from scratch on the ‘preview’ branch.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Comment by bartlettroscoe** [comment]
Note related issues #743, #744, #709, #711, #645, #643, #368

**Comment by bartlettroscoe** [comment]
> I also think it would be good to try locking down master.  I’ll put a ticket in for that too.

@bernhold, responding to your email here since this is the epic where I suggested this [above](https://github.com/betterscientificsoftware/bssw.io/issues/330#issue-426549057).  Should I create a new child Issue to track locking down 'master' and go ahead and do it?

**Comment by bernhold** [comment]
I have mixed feelings about requiring reviews.  I understand why this is a good idea in principle, however it would significantly slow down many things that I do and perhaps others.  I'm thinking of adding generated events (for HPC-BP webinars and SWR panels) and maintenance operations.  I think we need to discuss the idea before implementing.

**Comment by bartlettroscoe** [comment]
> I have mixed feelings about requiring reviews.

@bernhold, I think the issue is that it looks like GitHub does not have a way to enforce only allowing PRs to update 'master' unless you require at least one reviewer (who is not the author) to approve the PR.  Otherwise, there is very little difference between posting a PR and having the author immediately merging it themselves compared to directly pushing to 'master'.  Unless you require at least one reviewer approval, requiring all modifications through PRs is meaningless.  (That is why I am guessing GitHub has implemented the permissions this way.)

**Comment by bernhold** [comment]
I get it.  The question for me is cost vs benefit.

**Comment by bartlettroscoe** [comment]
> I get it. The question for me is cost vs benefit.

@bernhold, right.  So the question is, how important is it to stop direct pushes to 'master'?  Can we start by restricting who can directly push to 'master'?  Everyone else will have to go through a PR and them someone with push access will need to approve and merge the PR.

**Comment by bernhold** [comment]
As I looked at the settings, it seems like master is actually protected already.  Though the observed behavior (who is able to push) is not consistent with my reading of the docs for branch protection.  So it may warrant a little more scrutiny.

But what we have currently is not protecting against the folks who seem to have the biggest problems remembering to use PRs instead of direct pushes.  So if we decide this is important, something does need to change.

**Comment by bartlettroscoe** [comment]
> As I looked at the settings, it seems like master is actually protected already.

@bernhold, in that context "protected" just means that you can't "force push", that is all.  It does not stop direct fast-forward pushes to 'master'

**Comment by bartlettroscoe** [comment]
With #702 finally closed, I think we can close this epic!
