### ISSUE TITLE
Some questions and suggestions for markdown references and wikize-refs.py

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#363]
@markcmiller86,

I was not aware of the documentation in the file [ReferencesInMarkdownHybridApproach.md](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/ReferencesInMarkdownHybridApproach.md) and the script [wikize-refs.py](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Articles/Blog/wikize-refs.py).    Thanks for providing that.

My first question is if there are any automated test to define and protect the behavior of the script `wikize-refs.py`?  It looks like a non-trivial amount of code and logic.  Where did this code come from?  That amount of code with no automated tests makes me nervous.

My second comment is that this looks really useful.  This is a type of bibtex for markdown pages.  I am wondering if it might be good to name the original source file `<basename>.src.md` and then have the script generate the `<basename>.md` file.   Since this would be useful for any markdown site like a github.io site and not just for BSSw, it would seem like the better display name would be `<basename>.md` instead of `<basename>-wikized.md`.  Or, one could add options to the script to allow the user to decide on the naming conventions and/or explicitly name the input and output files.  It needs to be made clear to people which file should be manually modified by the user.  By making the output file read-only, that helps to make that point.  I see the script also puts in the warning at the top:

```
<!--- WARNING: Auto-generated with wikize-refs.py from ReferencesInMarkdownHybridApproach.md --->
```

so that might be good enough.  (It might be good to puth that warning at the bottom of the file too.)

What do you think?

**Comment by markcmiller86** [comment]
> My first question is if there are any automated test to define and protect the behavior of the script `wikize-refs.py`?

Right. I tested it mainly while developing the article on the apollo guidance computer and so used that as my test.

> Where did this code come from?

I wrote it a few weeks ago. I am not the best python coder. I don't generally think in terms of OO python and it all winds up looking procedural. 


> This is a type of bibtex for markdown pages. 

Right. And, I agree...In fact, I think it has merit as its own little self-contained GitHub project apart from BSSw.

> I am wondering if it might be good to name the original source file `<basename>.src.md` and then have the script generate the `<basename>.md` file.

Good idea. I didn't think too hard about this aspect. I am fine with changing it.

> Or, one could add options to the script to allow the user to decide on the naming conventions and/or explicitly name the input and output files.

I started down that path but didn't complete it due to other obligations.

> By making the output file read-only, that helps to make that point. 

I think that may make sense. But, in current usage that would create problems for **EB Members** who often need to adjust YAML base-matter before going to publication.

Maybe it would be better to make this a CI thing or maybe a hook thing and have it trigger automatically for certain kinds of content (e.g. YAML base matter has `process-refs: True`) or something.

**Comment by markcmiller86** [comment]
We could make defualt output read-only but add an option to override that for **EB Members** so @curfman or @bernhold can use it more easily as part of Blog/Article workflow (until and if it gets somehow automated later)

**Comment by bartlettroscoe** [comment]
@markcmiller86, I think writing some basic system-level tests for `wikize-refs.py` will be easy.  Just create a few simple dummy `<basename>.md` files and compare the generated `<basename>-wikized.md` to some  <basename>-wikized.expected.md` files with a simple diff.  Might test a few basic boundary cases that might trip people up.  For now we can create a subdir in this GitHub repo and put the script and some simple tests there.  I would just use the Python unit test harness to run the tests and run it locally manually whenever that script gets modified.  Nothing fancy.  But that will pin down the basic functionality of the script and then we can safely make changes to it knowing we will.

If that is okay with you, I can do that at some point here.

**Comment by markcmiller86** [comment]
> If that is okay with you, I can do that at some point here.

That would be wonderful!

**Comment by bartlettroscoe** [comment]
@markcmiller86 said:

> We could make defualt output read-only but add an option to override that for EB Members so @curfman or @bernhold can use it more easily as part of Blog/Article workflow (until and if it gets somehow automated later)

The problem with letting anyone directly edit the generated file is that if anyone changes the original and then regenerates the output, it will wipe out their changes.  So an article that is published would all of the sudden disappear from the BSSw site.

**Comment by bernhold** [comment]
How much of this is supported in other flavors of MarkDown?  I'm pretty certain that the BSSw frontend processing is not actually using GitHub-flavored MarkDown (GFM).  This is actually a modest complication in the production process -- occasionally, things that look fine in the GRM previews don't work at all on the site.  There may be larger considerations here.

**Comment by markcmiller86** [comment]
> How much of this is supported in other flavors of MarkDown? I'm pretty certain that the BSSw frontend processing is not actually using GitHub-flavored MarkDown (GFM).

I admit I haven't tested it but am pretty sure its supported by other flavors of markdown.

**Comment by markcmiller86** [comment]
> This is actually a modest complication in the production process -- occasionally, things that look fine in the GRM previews don't work at all on the site. There may be larger considerations here.

To be honest, I think this is more than a *modest complication*, especially if part of our workflow is to suggest authors craft content directly on GitHub or via PRs in which they are likely to then use local GFM compliant rendering tools to see the final result.

I suspect that [this article](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/mcm86-cc-teletools-4-remote-work/CuratedContent/TelecomToolsForRemoteWork.md#experiences-in-actual-use) will not render at all on BSSw and if not, we should post a short CC That simply references the correctly rendered markdown on GitHub.

**Comment by bartlettroscoe** [comment]
I think with the merge of PR #718 that gives `wikize_refs.py` and in-place update option, all of the issues related to managing a sperate source and generated file are gone.  For local development and debugging purposes, `wikize_refs.py foo.md` by default generates a separate `foo-wikizied.md` file so it super safe to use if the user does not know what they are doing.  But when we are ready to post a PR, we can run `wikize_refs.py -i foo.md` and commit that updated file.  This is about the perfect workflow.

Therefore, I will close this issue as we still have the related issues #702 and #695 open.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211
