### ISSUE TITLE
Add information about software coding conventions/standards

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#37]
Author: @rinkug 
EB member: @bartlettroscoe 

Provide resources on how to establish and follow coding conventions (or standards) in order to create maintainable code. This will be a series of how to's, curated links and other articles.

**Comment by rinkug** [comment]
Explore (to start with)
1. What is meant by software coding conventions? Why are they important?
2. Do  "software coding standards" exist?
3. What are the well known projects who provide exemplary samples of good software coding? (curated links)

**Comment by pagrubel** [comment]
@rinkug do you have another issue that covers this. 
Lois says you have a draft. Please either update this issue or close it and remove it from the project board.

**Comment by bartlettroscoe** [comment]
@rinkug, I can be the EB member for this one.

**Comment by markcmiller86** [comment]
Recommend closing this issue and replacing it with the (set of) issue(s) of specific content to develop

**Comment by bernhold** [comment]
Step 1 might be #435 which proposes a cc article linking to the Wikipedia page (which has a long list of conventions and exemplary projects).

**Comment by rinkug** [comment]
> Recommend closing this issue and replacing it with the (set of) issue(s) of specific content to develop

That might be a better idea. The article gets delayed since its a big piece and needs a big chunk of time.

**Comment by rinkug** [comment]
Create more tickets to break down this problem. But keep this issue open to track the creation of new tickets.

**Comment by bernhold** [comment]
How does this relate to #435?

**Comment by bartlettroscoe** [comment]
I actually did a bit of investigation into this topic years ago.  I know the motivation for doing it but I have not had the pleasure to work with any projects that took this seriously.

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Comment by bernhold** [comment]
@rinkug will #1076 satisfy this request?  If not, we probably need to refine this issue.

**Comment by bartlettroscoe** [comment]
This was done with the merge of PR #1076.
