### ISSUE TITLE
Variations in editorial review process for different content types

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#371]
The purpose of this issue is to discuss if/how the editorial workflow should differ for different types of content.

The reference document for this discussion is the recently-adopted **curated content** workflow: <https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/Site/CuratedContentEditorialWorkflow.md>

I believe that the key points of the workflow to be discussed are steps **4** (review of the idea) and **7** (review of the pull request/content). If you think any other aspect of the workflow needs to change based on content type, please comment.

I propose the following criteria:

| Content Type | Step 4: Idea Review Thumbs Up | Step 7: Pull Request Reviews |
|----------------|----------------------------|------------------------|
| Event* | 0 | 1 |
| Curated Content | 2 | 1 |
| Original Article | 2 | 2 |

*For **events**, I believe it would be acceptable to go straight to the pull request to production, or alternatively straight from the issue to production (assuming all the necessary information is provided).

Note that after the discussions on the 2019-05-30 telecon, I believe that we do not need to distinguish subtypes of **original articles** for purposes of defining the editorial process.  I include **blog articles** in **original articles**.

**Comment by markcmiller86** [comment]
I am not sure where to put this and this issue seemed as good as any other but I think we have some *mechanical* editorial-related activities that we haven't included in these discussions or the workflows we've been talking about...

* spell checking
* grammar, punctuation and syntax checking
* gender nuetrality checking
* link checking
* reference checking
* other *metrics* tools we might wanna use
* image copyright permissions
* licensing

Certainly, scripting can play a large role here. However, I think many of these aspects also involve some amount of human babysitting, especially when the checks reveal issues requiring action.

**Comment by bernhold** [comment]
Actually, I think @pagrubel has an action item to draft up the review criteria.  @markcmiller86's list looks to me like they should be considered for that list.

**Comment by markcmiller86** [comment]
I understood @pagrubel action item to be one of *acceptance* criteria such as topic, relevance, tone, applicability, etc.. I view most of the *mechanical* editorial aspects I listed above as stuff to be done in preparation for publicaton of some accepted content.

**Comment by bernhold** [comment]
Fair, but I still think they would bear on whether we consider an item to be ready for *publication*.

Maybe there are different criteria to be applied at different stages of the process
1. Judging whether an article idea is appropriate for BSSw
2. Judging the actual content of a contribution
   a. Whether the PR is acceptable
   b. Whether the content is ready for publication

Arguably, @markcmiller86's criteria would apply at the 2b stage.

A related question is whether 2a and 2b are separate steps in the process.  Do we accept the submitted content if there are "mechanical" issues that still need to be addressed, or do we ask the submitter to keep revising until they're all addressed?  If "BSSw staff" are going to handle it, what role do we assign it to?  Maybe technical editor or editorial assistant?

Looks to me like we've made @pagrubel's task more interesting :-)

**Comment by jarrah42** [comment]
What do the numbers in the step 7 column represent? The number of approvals? If so, it should probably read "Step 7: Pull Request Approvals".

**Comment by bernhold** [comment]
> What do the numbers in the step 7 column represent? The number of approvals? If so, it should probably read "Step 7: Pull Request Approvals".

I'm fine with that change.  Thanks.  I'll make it when we produce a summary document from these discussions.

I would like to encourage everyone to think about the *numbers* in the table.  To me, that is the primary thing we need to reach agreement on. Are the number of reviews/approvals I proposed consistent with the "level of review" we think is appropriate for each of these content types?

I think it would be great if everyone could at least comment with a :+1: (`:+1:`) or :-1: (`:-1:`) on the numbers. (That's how I envision voting on idea proposal issues as well.)

Thanks

**Comment by pagrubel** [comment]
👍

**Comment by pagrubel** [comment]
I have a pull request for the criteria, please move comments that apply to it to that pull request and we can decide what to add there. Thanks!

**Comment by markcmiller86** [comment]
> I have a pull request for the criteria, please move comments that apply to it to that pull request and we can decide what to add there. Thanks!

By *move*, I assume you mean continue this conversation there as opposed to actually physically moving the comments already here.

Also, lets link to that PR (#372) from here. And, lets link that PR with a comment to this issue there.

**Comment by pagrubel** [comment]
I added the conversation there. I hate looking through two pages. I commented on the wrong issue when I was doing that.

**Comment by bartlettroscoe** [comment]
Can we change the name of the column "Development Backlog" to "Approved for Development" and add a new column "Content in Development"?  That makes it clear if approved content is actively being worked on or not.

**Comment by curfman** [comment]
Sounds like a good idea to change the name of the column "Development Backlog" to "Approved for Development" and add a new column "Content in Development"? ... This will help to more clearly track what is happening.

**Comment by bernhold** [comment]
I would say "Ready for Development" and "Under Development" if we want to be slightly shorter. But I agree with the overall suggestion.

**Comment by bartlettroscoe** [comment]
@bernhold said:

> Can we change the name of the column "Development Backlog" to "Approved for Development" and add a new column "Content in Development"? That makes it clear if approved content is actively being worked on or not.

Sounds good to me.  Can we agree to this and I can pull the trigger?

**Comment by bartlettroscoe** [comment]
@bernhold said:

> I would say "Ready for Development" and "Under Development" if we want to be slightly shorter. But I agree with the overall suggestion.

Sounds good to me.  Can we agree to this and I can pull the trigger?

**Comment by markcmiller86** [comment]
> * gender nuetrality checking

Found this [awesome resource](http://www.writinghelp-central.com/gender-neutral.html) for help with gender neutrality. We should create CI checks for it ;)

**Comment by bartlettroscoe** [comment]
> Found this awesome resource for help with gender neutrality. We should create CI checks for it ;)

That is fine but what is conspicuously missing is what to do to replace "he"/"she", "his"/"her", etc.!  That is the real problem.  I have been told that "they" is incorrect English.  So that takes us back to third-person "one" which many people (including myself) hate.

**Comment by markcmiller86** [comment]
> That is the real problem.

So, I agree that is *a* problem...with the English language. But, for my writing anyways, it tends not to be the biggest problem. I do wind up using `s/he` more often than I'd like though. And, this resource really helps with those problems that are not inherent to English itself but rather to the (unconscious) biases in the mind(s) of the writers ;)

**Comment by markcmiller86** [comment]
Some tooling activities to be aware of...

* https://developer.ibm.com/tutorials/take-two/
* https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo

**Comment by bartlettroscoe** [comment]
Related to my epic SEPW-211

**Comment by rinkug** [comment]
Can we close this issues? I vote we do.

**Comment by rinkug** [comment]
The current workflow is sufficient. This is being closed as it is not needed
