### ISSUE TITLE
"Agile Software Development" by Robert Martin

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#383]
Authors: Ross B.
EB member: Mark M.

Write an curated content article for the book:
> Martin, Robert C. Agile Software Development (Principles, Patterns, and Practices). Prentice Hall, 2003

along the lines of:
* https://bartlettroscoe.github.io/reading-list/#agile_software_development_2003

I can do this at any time.  Just let me know.

**Comment by markcmiller86** [comment]
@bartlettroscoe you are on the hook to write this.

**Comment by bartlettroscoe** [comment]
With PR #580 created, this Issue is now closed.
