### ISSUE TITLE
Pointer to InfoQ technical leader article

### ISSUE THREAD

**Issue by maherou** [betterscientificsoftware/bssw.io#4]
This article has relevant advice for people who step into technical leadership roles on a software project.  Some points could be very relevant for our community.

https://www.infoq.com/news/2015/01/technical-leadership-agile

**Comment by prwolfe** [comment]
Won't open in safari - seems better in Firefox

**Comment by markcmiller86** [comment]
> Won't open in safari - seems better in Firefox

I confirm that behavior also.

I am discovering many of the links off the GitHib project board do not work in safari directly.

However, I *do* find that right-clicking and pulling down to *Open link in new window* does work. Its a pain but it is a work-around for Safari.

**Comment by pagrubel** [comment]
This article has some good ideas for technical leads, both for the new tech lead and maybe in choosing someone with a good skill set to be a technical lead.

**Comment by rinkug** [comment]
@pagrubel will check if this is still valid.

**Comment by pagrubel** [comment]
@rinkug this is still relevant, it isn't that meaty but it does have a few good points for someone who is a tech lead, it is oriented more towards software development tech lead for agile but applicable to any software development tech lead. I'm wondering about the scientist that may find themselves as a tech lead. One of the points is that a tech lead should also code.

**Comment by rinkug** [comment]
This is published.
