### ISSUE TITLE
Articles related to "Testing" from old IDEAS site

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#400]
It would be good to add curated content articles for the three different articles:

* "What are Software Testing Practices?"
* "Definition and Categorization of Tests for CSE Software"
* "How to Add and Improve Testing in Your CSE Software Project"

at:

* https://ideas-productivity.org/resources/howtos/

We can mine the last one especially for PSIP tracking card templates for improving testing.

**Comment by bartlettroscoe** [comment]
Doing some more searches on the BSSw site I found:

* https://bssw.io/items/what-is-cse-software-testing
* https://bssw.io/items/how-to-improve-testing-for-cse-software

So looks like we are just missing a curated content article for:

* [Definition and Categorization of Tests for CSE Software](http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingWhatIsDefinitionandCategorizationofTestsforCSESoftware-V0.2.pdf)

**Comment by rinkug** [comment]
We need to figure out how to update this material (both refreshing it and making it native it to the site). This is present on the old IDEAS and we figure out how to bring it to the new one.

**Comment by rinkug** [comment]
This issue is addressed in #560 and can be closed.
