### ISSUE TITLE
Process: circumventing topic review

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#439]
I'm taking the higher-level discussion from PR #438 into a separate context.

> @markcmiller86
> 
> > I didn't add an issue.
> 
> Okay
> 
> > And, I am guessing it takes less time to do that and have others decide what to do with it than to first submit an issue, then wait for dialog and up or down votes, then wait for it move through to the ready-for-development state and then remember to write it.
> 
> If an EB member likes a piece of content (and is not just publishing their own work), then I don't see problem with this. Do we want less stuff on BSSw?
> 
> But we should likely get them to change to process to allow this shortcut workflow.

I have several thoughts about this...
1. Right now, we tend to spend a lot of time and energy  on the idea-vetting-issue stage of the workflow.  My hope and expectation is that over time, we'll solidify our own collective idea of what's appropriate for BSSw and this step will become merely a sanity check which is carried out very quickly.

2. I think we should expect that some enthusiastic people will skip the idea-vetting stage and simply give us a PR with the content.  I think we should embrace this, even if it is not our preferred approach.  In other words, I don't think we necessarily need to document a shortcut like this in our public workflow descriptions, but we should accept it and work with it when it happens.

3. When this happens (a PR without prior interaction), I think we should include a brief sanity check of the topic implicitly in the PR review process and move on.  In the spirit of where we want to eventually be with (1).

4. This has happened a few times with outside contributors.  And more often with internal contributors (e.g., me).  I think when it happens internally, it is mostly to coordinate with outside things where timing is important.  For me, it is mostly events.\, which for example, are being highlighted in other venues.  I've been intentionally putting cc ideas through the vetting process so that we can have those discussions.

**Comment by bartlettroscoe** [comment]
But once the PR with the proposed content is created, it needs to be subjected to certain quality and sensitivity criteria.  We don't want to allow stuff that we can't all be proud of getting on to the site.

**Comment by bernhold** [comment]
> But once the PR with the proposed content is created, it needs to be subjected to certain quality and sensitivity criteria. We don't want to allow stuff that we can't all be proud of getting on to the site.

Agreed. This is what I intended in item 3 in my original list.  If there is any question about the topic, it should be scrutinized more closely.

**Comment by markcmiller86** [comment]
> 2\. I think we should expect that some enthusiastic people will skip the idea-vetting stage and simply give us a PR with the content.  I think we should embrace this

That is certainly the spirit in which I jumped on this particular item


> But once the PR with the proposed content is created, it needs to be subjected to certain quality and sensitivity criteria. We don't want to allow stuff that we can't all be proud of getting on to the site.

So, I was on the fence about *how* to ensure that. On the one hand, I had what I thought was an almost ready to publish CC contribution. On the other hand, it hadn't even gone through topic review. So, I put in the *ready-to-publish* (with two thumbs up but only one from EB members which was my own :smile:) expecting that would provide the opportunity for others to review prior to going live.

**Comment by pagrubel** [comment]
>So, I put in the ready-to-publish (with two thumbs up but only one from EB members which was my own 😄) expecting that would provide the opportunity for others to review prior to going live."

I can't keep track of all that is going on and the CC contribution that started this issue, just looked like it was ready for publishing and had already been reviewed, so how would we know to review it?

**Comment by markcmiller86** [comment]
Minimally...at our weekly meeting. We'll see it there and can comment. Sooner if you want to go look at the PR anytime prior to that meeting.

**Comment by rinkug** [comment]
What do you think about closing this issue?

**Comment by rinkug** [comment]
Closing it - EB is experienced enough to judge content. We dont have more bandwidth for this now.
