### ISSUE TITLE
Addressing the Detrimental Effects of Context Switching with DevOps

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#444]
Author: Pat
EB member: Ross

This was suggested by Will Mclendon at SNL:

* [Addressing the Detrimental Effects of Context Switching with DevOps](https://insights.sei.cmu.edu/devops/2015/03/addressing-the-detrimental-effects-of-context-switching-with-devops.html)

The problem with context switching is addressed by Kanban and is also well described in the book:

* [Poppendieck, Mary and Tom. Implementing Lean Software Development. Addison Wesley, 2007](https://bartlettroscoe.github.io/reading-list/#implementing_lean_software_development_2007)

**Comment by pagrubel** [comment]
This is a great topic. 
@bartlettroscoe Are you suggesting that the article point to the article and some portions of the Poppendieck book?

**Comment by bartlettroscoe** [comment]
> Are you suggesting that the article point to the article and some portions of the Poppendieck book?

Yes, I would use that book as an example reference for the impact of task switching and degrading productivity.

**Comment by pagrubel** [comment]
Closing this issue see PR #573
