### ISSUE TITLE
Thought Leader Blog Roll

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#474]
Author: David
EB member: Rinku

This proposal replaces #272 and is based on a comment there.

There are a number of people who frequently blog on topics of interest to BSSw.  I think they are worth following, and I think it is worth letting the community know that I/we think they're worth following.

The criteria should be
- The _majority_ of postings are on BSSw-relevant topics
- Postings generally contain useful information and/or are thought-provoking
- They're generally not promoting products or services

My initial list includes:
- https://danielskatzblog.wordpress.com/
- http://blog.martinig.ch/ (This is general software engineering, but every month they put out a fairly long list of SWE-relevant resources, and there's always a number of things that are interesting.)
- http://blog.khinsen.net/

Maybe also
- http://ivory.idyll.org/blog/ (probably not enough on software engineering as opposed to his research)
- https://www.michaelagreiler.com/ (I'm not sure she's got enough content for CSE people)

**Comment by rinkug** [comment]
Only concern is whether it comes across as if we (BSSw) is endorsing the folks writing the blogs?

**Comment by markcmiller86** [comment]
I wonder if following the recent dicussion regarding [this article](http://blog.khinsen.net/posts/2020/05/18/an-open-letter-to-software-engineers-criticizing-neil-ferguson-s-epidemics-simulation-code/?utm_source=all&utm_medium=Atom), we might have revised our thinking here.

**Comment by bernhold** [comment]
I stand by the list I proposed, including Hinsen.  I don't think we should expect to agree with every single thing a blogger might write.
