### ISSUE TITLE
possible curated content item: Making Software: What Really Works, and Why We Believe It

### ISSUE THREAD

**Issue by curfman** [betterscientificsoftware/bssw.io#475]
Possible curated content item:  book

Making Software: What Really Works, and Why We Believe It
by Andy Oram and Greg Wilson

http://shop.oreilly.com/product/9780596808303.do 

Description:
Many claims are made about how certain tools, technologies, and practices improve software development. But which claims are verifiable, and which are merely wishful thinking? In this book, leading thinkers such as Steve McConnell, Barry Boehm, and Barbara Kitchenham offer essays that uncover the truth and unmask myths commonly held among the software development community. Their insights may surprise you.
Are some programmers really ten times more productive than others?
Does writing tests first help you develop better code faster?
Can code metrics predict the number of bugs in a piece of software?
Do design patterns actually make better software?
What effect does personality have on pair programming?
What matters more: how far apart people are geographically, or how far apart they are in the org chart?

**Comment by rinkug** [comment]
Paul is looking at this book

**Comment by rinkug** [comment]
@prwolfe : are you considering being an authors for this?

**Comment by prwolfe** [comment]
> @prwolfe : are you considering being an author for this?

I would like that. I have not quite finished the book and will start in as soon as I do.

**Comment by prwolfe** [comment]
From working session on 11/5/2020 - got further into the draft than I expected and am placing here so I don't lose it.

Outline for issue #475

Title: "Making Software: What Really Works, and Why We Believe It" - 2010

Type: Curated content

Overview
  People
    Andy Oram - Editor
    Greg Wilson - Project lead at Software Carpentry
      Many academic researchers - one per subject mostly
  Techniques
    Actual mesurements whenever possible
    Mixed modes in almost all cases
  Answers to the central question (scattered)

Each of us will wonder if we are useing the right SE pratctices at many points
in each project. Greg Wilson has accumulated studies on many of the trends and 
methods in use today and attempted to gain insight into the usefulness of each.
To that end he has elisted a number of researchers in Computer Science to
collect data about which techniques work, which ones hurt, and which are
inconclusive. The book has two sections, onethe first on how data was gathered
and evaluated, and a second on individual SE practices. Each chapter takes a
specific area and dives into the studies done and the evaluation of incompatible
results. An attempt is then made to come to a conclusion as to the effectiveness
of the practice overall.

I belive that there are several usefull results in the book, but despite the title
there are a significant number of inconclusive results. Those cases are well
documented and if there is a lot of grey area in such a nascent field it is no
surprise. Remember that we are talking about < 60 years of commercial, large
scale software efforts and that the Computer Science Teachers Association (CSTA)
was founded in 2005.

**Comment by rinkug** [comment]
Please refer to PR #679.
