### ISSUE TITLE
HowTo on bringing a project to conclusion

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#482]
All too often, when projects end, a lot of the assets fall into disrepair or are lost entirely. There are important actions to take when ending projects to prevent this from happening. For example, web sites or custom domains expire. We need a HowTo on best practices for bringing a project to conclusion. Maybe identify some key things sponsoring organizations (ASCR or NNSA) can do to provide minimal (life support) to ensure concluded projects can be put into stasis effectively.

**Comment by rinkug** [comment]
I absolutely agree on a need for this.

**Comment by bernhold** [comment]
Neil Chue Hong's Halloween blog is relevant to this topic.  Probably worth mentioning, and perhaps making some stronger connections.

https://bssw.io/blog_posts/bloodsuckers-banshees-and-brains-a-bestiary-of-scary-software-projects-and-how-to-banish-them

**Comment by bernhold** [comment]
This is labeled as a potential blog article, but Mark's description refers to it as a HowTo.  Can we decide what is most appropriate?

**Comment by markcmiller86** [comment]
Here are some more resources...
* http://www.enterpriseunifiedprocess.com/essays/retirementPhase.html
* http://www.dba-oracle.com/t_project_mothballing_reactivated_failure.htm
* verbiage: decomissioning, retiring, sunsetting, retiring
* end-of-life vs. end-of-funding

**Comment by rinkug** [comment]
PR #601 has been opened for this
