### ISSUE TITLE
Software and workflow development practices 

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#506]
This blog post by C. Titus Brown might make a useful cc article.  Relatively simple.  Targeted at people who run a lot of data through scripts and tools more than people developing software per se.

<http://ivory.idyll.org/blog/2020-software-and-workflow-dev-practices.html>

**Comment by markcmiller86** [comment]
I gave it a thumbs up. However, I didn't come away from it with a feeling of data-centric focus. Only one of the practices focused specifically on data. The majority of practices seem to focus on *testing*. One practice I *really* liked...**Put everything in issues**.

**Comment by rinkug** [comment]
PR #602 has been created
