### ISSUE TITLE
Updating older curated content articles

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#511]
Some of our curated content article need updating. Out of 120, most revised; but 4 articles will need some more work with regards to enhancing write up, formatting, deck text, table text etc. The remaining 8 articles are not published..

Here is a list of such articles: From the below list, we need to update 4,8,10,12 as these are published right now on bssw.io

1.DELETED: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/ACMTransactionsOnMathematicalSoftware.md (publish = no)

2.DELETED: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/ACMTransactionsOnMathematicalSoftware.md (publish = no)

3.DELETED: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/ArchiveOfNumericalSoftware.md (publish = no)

4.**COMPLETED: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/CseCollaborationThroughSoftwareImprovingProductivityAndSustainability.SIAM-CSE17.md (publish = YES)**

5.** NEEDS REVISION** https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/DebuggingCseSwUNPUB.md  (publish = no)

6.DELETED: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/JournalOfOpenSourceSoftware.md (publish = no)

7.DELETED:https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/JournalOfStatisticalSoftware.md  (publish = no)

8.**COMPLETED: https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/LearningStudies.md (publish = YES)**

9.DELETED:https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/MobileTest.md (publish = no)

10.**COMPLETED NEEDS MORE REVISION :** https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/RequirementsAndRequirementsEngineeringREVISE.md (publish = YES)

11.DELETED:https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/SoftwareX.md (publish = no)

12.**COMPLETED: **https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/SwProductivityAndSustainabilityForCseAndDataScience.SIAM-CSE17.md (publish = YES)**

**Comment by pagrubel** [comment]
I'll work on 4. CSE ...

**Comment by rinkug** [comment]
Tagging Kasha (@karbarz) for assistance in getting these articles done

**Comment by rinkug** [comment]
The following cc need work:

- https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/WritingRequirements.md 

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/UnderstandingRequirementsEngineering.md

https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/UnderstandingRequirements.md

Q. Is this a short article series by Reed?

- https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/WorkingEffectivelyWithLegacyCode.md
Q. References in table?

- https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/WhatPerfPortabilityToolsAreCompatible.md

- https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/UserStories.md

Q. Is this short article?

- https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/TransmediaLearningFrameworks.md

Q. Incomplete?

**Comment by rinkug** [comment]
Need to have plan in place to make progress on this

**Comment by rinkug** [comment]
> @rinkug These are all completed, but #10 is a dead link:
> 
> https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/blob/master/CuratedContent/RequirementsAndRequirementsEngineeringREVISE.md
> 
> I believe this issue can be closed.

This became a short article and was published here: https://bssw.io/items/overview-of-requirements-and-requirements-engineering

**Comment by rinkug** [comment]
This issue can now be closed.
