### ISSUE TITLE
Why collaboration and competition are critical to scientific objectivity

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#518]
Found these two articles both interesting and highly relevant to current challenges in digesting science-based information. When you combine the ideas from these articles with the goals of *simulation science*, I think it makes for a useful article and reminder for our community.

* [Article 1](https://blogs.scientificamerican.com/doing-good-science/httpblogsscientificamericancomdoing-good-science20110720the-objectivity-thing-or-why-science-is-a-team-sport/)
* [Article 2](https://blogs.scientificamerican.com/doing-good-science/httpblogsscientificamericancomdoing-good-science20110721objectivity-requires-teamwork-but-teamwork-is-hard/)

**Comment by pagrubel** [comment]
If the curated article can relate this to the goals of simulation software I think this would be appropriate.

**Comment by markcmiller86** [comment]
If @bernhold is planning on an article based on the several slides he used in ATPESC on the *quality* of scientific software, then the above references may be good to cite or link to.

**Comment by bernhold** [comment]
I gave it a 😕 because these don't really seem to connect back to software in any particular way, which is where we want BSSw to be.  Maybe there's more content in the article Mark envisions that would make that connection.  But for just a CC pointing to these two, I'm not convinced.

**Comment by markcmiller86** [comment]
I agree, connection to *software* is not at all strong. Maybe even wholly absent. Perhaps more valuable as a connection to *team science* which...IMHO...is kinda what HPC/CSE software is all about. So, its a *meta* connection.

**Comment by markcmiller86** [comment]
Further, I think these two articles help to amplify a key theme in BSSw tutorial...the impact of software quality on *science* derived from that software.

**Comment by bernhold** [comment]
Does anyone know why this issue is on the BSSw Internal board?  It is closed, and I don't see anything in the thread suggesting an intent to move it here. I propose we remove it from this board unless someone speaks up.

**Comment by rinkug** [comment]
Added by mistake on this board.
