### ISSUE TITLE
HowTo and WhatIs documents: scope, review workflow,  style guide.

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#519]
We have had how-to/what-is documents in the past. They contain a lot of useful information. We need to decide on the future of these docs?
1. Scope going forward 
2. Format and style guide
3. Workflow
4. Migration of old how-tos/what-is

**Comment by rinkug** [comment]
Following is a list of the old documents:
https://ideas-productivity.org/resources/howtos/

Some of them have been converted to native format here: https://github.com/rinkug/ideas-rinku-personal/tree/master/How-tos

**Comment by rinkug** [comment]
**Productivity:**

1. What is CSE Software Productivity?
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-ProductivityWhatIsCSESWProductivity-V0.2.pdf
**Native:** TBD
**Assigned:**


**Software Configuration:**

2. What is Software Configuration?
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-ConfigurationWhatIsSoftwareConfiguration-V0.2.pdf
**Native:** TBD
**Assigned:**

3. How to Configure Software
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-ConfigurationHowToConfigureSoftware-V0.2.pdf
**Native:** https://github.com/rinkug/ideas-rinku-personal/blob/master/How-tos/NATIVE-HowToConfigureSw.md
**Assigned:**

**Performance Portability:**

4. What is Performance Portability for CSE Applications?
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-PerformanceWhatIsPerformancePortability-V0.2.pdf
**Native:** TBD
**Assigned:**

5. How to Enable Performance Portability for CSE Applications
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-PerformanceHowToEnablePerformancePortability-V0.2.pdf
**Native:** https://github.com/rinkug/ideas-rinku-personal/blob/master/How-tos/Native-IDEAS-PerformanceHowToEnablePerformancePortability.md
**Assigned:**

**Testing:**

6. What are Software Testing Practices?
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingWhatAreSoftwareTestingPractices-V0.2.pdf
**Native:** TBD
**Assigned:**

7. Definition and Categorization of Tests for CSE Software
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingWhatIsDefinitionandCategorizationofTestsforCSESoftware-V0.2.pdf
**Native:** TBD
**Assigned:**

8. How to Add and Improve Testing in Your CSE Software Project
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject-V0.2.pdf
**Native:** https://github.com/rinkug/ideas-rinku-personal/blob/master/How-tos/Native-IDEAS-TestingHowtoAddImproveTestinginyourCSESoftwareProject.md
**Assigned:**

**Documentation:**

9. What is Good Documentation?
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationWhatIsGoodDocumentation-V0.1.pdf
**Native:** TBD
**Assigned:**

10. How to Write Good Documentation
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-DocumentationHowToWriteGoodDocumentation-V0.1.pdf
**Native:** https://github.com/rinkug/ideas-rinku-personal/blob/master/How-tos/Native-DocumentationHowToWriteGoodDocumentation.md
**Assigned:**

**Software Libraries:**

11. What are Interoperable Software Libraries?
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-InteroperabilityWhatAreInteroperableSoftwareLibraries-V0.2.pdf
**Native:** TBD
**Assigned:**

**Version Control:**

12. What is Version Control?
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/04/IDEAS-VCWhatIsVersionControl-V0.1.pdf
**Native:** TBD
**Assigned:**

13. How to Do Version Control with Git in Your CSE Project
**Original:** http://ideas-productivity.org/wordpress/wp-content/uploads/2016/12/IDEAS-VCHowToVersionControlwithGit-V0.2.pdf
**Native:** https://github.com/rinkug/ideas-rinku-personal/blob/master/How-tos/Native-HowToVersionControlwithGit.md
**Assigned:**

14. Git Tutorial and Reference Collection
**Original:** http://ideas-productivity.org/resources/howtos/git-tutorial-and-reference-collection/
**Native:** TBD
**Assigned:**

**Comment by bernhold** [comment]
How is this related to #560 ?

**Comment by rinkug** [comment]
Note that this topic is discussed with action plan in #560. I am closing this older issue.
