### ISSUE TITLE
Missing content from a WhatIs doc?

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#535]
[This WhatIs article](https://bssw.io/items/what-are-strategies-for-more-effective-teams) is about *strategies* for more effective teams. In particular, it concludes with...

> We provide information to help foster teamwork in teams of all sizes, leveraging people's diverse skills in pursuit of a common goal.

But does not either go on to provide such information or have any links that might take a reader to such information.

Is something missing here?

**Comment by rinkug** [comment]
Since this is a what-is document, what it really meant was that: We (the BSSw.io portal) provide information. It should be rephrased..

**Comment by rinkug** [comment]
This needs to be closed.
