### ISSUE TITLE
Recent article surveying methodologies in parallel programming for modern HPC systems

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#543]
Author: @rinkug 
EB member: @markcmiller86 

Ran across [this paper](https://www.hindawi.com/journals/sp/2020/4176794/). Unfortunately, the on-line article's tables do not render well. It would be good to find a properly formatted pdf. 

But, the article is quite detailed and treats a wide variety of parallel programming methodologies. The reference list alone is cites 95 papers.

**Comment by rinkug** [comment]
This is a good article. Tables are fine if you expand them.

**Comment by bartlettroscoe** [comment]
Seems like a good article for for newbies to HPC.

**Comment by bernhold** [comment]
I suspect a lot of our audience will probably be familiar with much of this.  It might connect to performance portability content somewhat.  I'm ambivalent about it.

**Comment by bernhold** [comment]
I'm still ambivalent, but feeling a bit more generous: I think I agree with @bartlettroscoe that this might be useful for someone who comes to the site with some experience in scientific computing, but not necessarily in HPC/parallel.  Maybe it could be the anchor of a CC on "introductory resources for parallel and high-performance computing" or some such (though that could become huge).
