### ISSUE TITLE
Style guide for references

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#552]
References in articles are not systematic nor consistent. We need to narrow down rules on how to write end-of-articles references.

**Comment by bernhold** [comment]
Just as an example of an alternative approach we used in one blog article:
* https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/Blog/CommunityOfPracticeAroundPeerReview.md
* https://bssw.io/blog_posts/a-community-of-practice-around-peer-review-for-long-term-research-software-sustainability

Summary:
* Journal paper has (Author, date) style references
* Same format was used in the blog, based on the paper's reference list
* The blog merely links to the full paper and asks readers to look there for details of references

This is not always going to make sense, but may on occasion be useful.

**Comment by rinkug** [comment]
This needs to come higher up on our radar.

**Comment by markcmiller86** [comment]
I feel like we've completed this [here](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#citationsreferences) and so should close this. Any objections?

**Comment by bartlettroscoe** [comment]
> I feel like we've completed this [here](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html#citationsreferences) and so should close this. Any objections?

No objections from me.  I think we have that covered now.
