### ISSUE TITLE
One year old article with in-depth comparison of GPUs for deep learning tasks

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#557]
Again, didn't read in detail. A lot of data here and the 

https://timdettmers.com/2019/04/03/which-gpu-for-deep-learning/

I assume AI/ML content fits our scope.

**Comment by pagrubel** [comment]
There is some useful information in this article about using gpu's for deep learning including using multiple gpu's, but the emphasis is on what to get. I'm not sure the gist of the article is very valuable for bssw. Is there something else out there that helps those who plan to include deep learning in their scientific software on HPC systems.

**Comment by markcmiller86** [comment]
@pagrubel and @bartlettroscoe what does the :eyes: emoji mean in your reactions here? I don't think we've seen that before whereas we've seen 👍 , 👎  and 😕 and we all generally know what those mean. I would suggest we stick with those reactions only.

**Comment by bartlettroscoe** [comment]
Changed mine to 😕.  Did not realize there was a standard

**Comment by pagrubel** [comment]
Okay I'll try to remember to behave in the future
