### ISSUE TITLE
Working Group: How to update the How-tos/What is

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#560]
Working group established as of Feb 11. 
Members: @rinkug, @pagrubel 

This issue has details on how to update existing articles.

1. The HowTo pdfs have been merged into master at https://github.com/betterscientificsoftware/bssw.io/tree/master/Articles/HowTos

2. Please  create a PR when you are done 
* Updating/reviewing the contents
  * Please ensure that the content is up-to-date
  * Replace links, version numbers etc. with the latest links; delete and rephrase outdated links
  *  Articles will be published with a new publish date; so please keep that in mind and ensure content is valid for current times.
* Adding metadata with publish=preview option

The style for HowTos is still under discussion; so for now please focus on updating the content. 
The (read only) excel sheet with the assignments is located [here](https://docs.google.com/spreadsheets/d/1ntxRava3zT3m3XJV86TiT5FU-VpRkl87o0xOGLaCZCE/edit?usp=sharing).

Any suggestions/issues can be made on this issue page or via an email to the EB mailing list.

**Comment by bernhold** [comment]
@rinkug I'm trying to clarify whether this is really started (i.e. "in progress") or not so that I can categorize it correctly on the project board.  Please let me know.  Thanks

**Comment by rinkug** [comment]
Please refer to the internal excel sheet to get your writing assignments on this. I have moved this back to read-to-write since this has several authors.

**Comment by bernhold** [comment]
How is this related to #519 ?

**Comment by rinkug** [comment]
This is completed
