### ISSUE TITLE
Glean curated content from Collegeville work (CW20)

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#566]
Finalize list of potential curated content from CW20. Please create a list of articles in the comments: https://collegeville.github.io/CW20/

**Comment by bernhold** [comment]
FYI, I'm working with Pat and Mark (initially) on looking for candidates for *blogs*.  I'll include CC as an option in our evaluations.

**Comment by bernhold** [comment]
I would argue that this ticket should never been in Ready to Write.  Rather individual items that come from mining CW20 should each have their own issues.  This issue is a placeholder to remind us to look at CW20 and should be closed when we think we've done what we can with it.

**Comment by bernhold** [comment]
I don't think it is ready for Topic Review either.  I think we can only vote on specific topics.

**Comment by bernhold** [comment]
Is there really anything more to do with CW20?

**Comment by rinkug** [comment]
Not really. This should be closed
