### ISSUE TITLE
Kanban and Scrum - Making the Most of Both

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#576]
Author: @bartlettroscoe 
EB Member: @rinkug 

The mini-book ["Kanban and Scrum - Making the Most of Both" by Henrik Kniberg and Marttias Skarin](https://www.infoq.com/minibooks/kanban-scrum-minibook/) is an excellent introduction to Scrum and Kanban and it shows how these methods provide a set of tools that projects can pick and choose from to develop the best processes for their particular project.  A very good short book in my opinion.

I read this book back in 2010 at the beginning of the CASL project (https://casl.gov) and it was extremely influential in the structuring of that project and especially the CASL Physics Integration (PHI) focus area.  In fact, the post-CASL entity 10 years later is still using this Kanban process that I helped set up for the project.

**Comment by pagrubel** [comment]
I downloaded the free pdf and skimmed it. It looks good. I hope to read it thoroughly soon and perhaps help organize a small project I'm on. We started Kanban but use it very lightly. Looks good to me and helps to know that Ross actually applied the methods over a long time period successfully.

**Comment by bartlettroscoe** [comment]
With this being deferred till next month, I will move back into "Ready to Write" and instead focus on getting #503 completed first (which I am already working on).

**Comment by bartlettroscoe** [comment]
I am going to go ahead and write this CC article.  I have not looked at this mini-book for many years so I will scan it and write up my review and post a PR with the new `*.md` file.

**Comment by rinkug** [comment]
Further discussion on Pr #783

**Comment by rinkug** [comment]
Please continue discussion on PR #788
