### ISSUE TITLE
Net Negative Producing Programmer

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#577]
The concept of a "net negative producing programmer" (NNPP) has been around for a while.  A good overview article on this is:

* http://www.software-thoughts.com/2009/08/net-negative-producing-programer.html

which gives references to to other discussions on this idea.

Personally, I think I have observed a few individuals in a few projects that have been an NNPP for that project for some period of time.  Typically, the person leaves the project at some point or is reassigned in their role to address the issue.

An interesting concept that is not yet discussed on bssw.io.

**Comment by bartlettroscoe** [comment]
@markcmiller86, @bernhold, @rmmilewi, ever heard of the NNPP idea?

**Comment by markcmiller86** [comment]
Not sure but if you're talking about a programmer that more often than not successfully finds ways to remove, rather than add code to a project whilst still meeting requirements, that seems like a really useful function :wink:

**Comment by bartlettroscoe** [comment]
> Not sure but if you're talking about a programmer that more often than not successfully finds ways to remove, rather than add code to a project whilst still meeting requirements, that seems like a really useful function

@markcmiller86, no, that is not it at all.  Someone who refactors and removes code without sacrificing needed functionality is a hero to the project and boosts overall long-term productivity.

An NNNP is a people who's involvement in a project reduces overall productivity of the project.  For a real NNPP, the project goes faster if that person leaves the project or goes on an extended vacation.  This can happen in many different ways.  There are some nice items listed in:

* http://www.software-thoughts.com/2009/08/net-negative-producing-programer.html

And I have one or two of my own items I could add to this list too but that mostly covers it.

Do any of those sound familiar?  If not, then you have lived a blessed life as a programmer :-)

**Comment by markcmiller86** [comment]
Yes, some of those do sound familiar. However, in my experience, I feel like _all_ of us typically manifest one or two of the behavior patterns mentioned. Its never as clear-cut as a single individual that manifests all of them or even the majority of them. Maybe I've encountered one or two in a 25+ career. More often than not, I am overwhelmed by the tremendous skill, expertise and productivity I see in those around me and want to try to emulate them in some way. I want to get into their lives and understand how they operate to hopefully step up my own game :wink:

I too could add a few items to the list. In situations like the article describes, I do think there is room to ask what is going on *around* the NNPP to have created the situation. I think most people want to be valued and to contribute positively to a project and so when there is an NNPP, it may have a lot to do with the surrounding situation, the management, how the person has been treated by their peers, etc. In fact, I was going to ask how often inclusivity issues may contribute to the creation of an NNPP? I suspect more often than we'd all like to consider. Sometimes, the very same NNPP in one project can be come a leader in another project that is better aligned with their strengths and needs. IMHO, it is a _failure_ of management to identify those cases and move people around to address them.

I do not mean to come across as though I am saying I believe all programmers are inherently good and when that is not true, the programmer in question doesn't have individual responsibility for their outcomes. They do. But, I guess am inclined to believe anyone demonstrating true NNPP behavior is more likely a call for help disguised as a *bad attitude* and that with more consideration, the situation can be greatly improved without having to resort to extreme measures like probation or firing.

**Comment by bartlettroscoe** [comment]
@markcmiller86, I agree with almost everything you have said [above](https://github.com/betterscientificsoftware/bssw.io/issues/577#issuecomment-697766773).  I too in my 20 year career have only interacted with perhaps 2 to 4 NNPP's and that may have only been for a period of time (a year or so).  But I think the concept of an NNPP and the traits and warning signs should be recognized if for no other reason than to motivate some needed action (where removal from the project or termination are the last actions to taken).  There were maybe two three individuals that I can think of over my 20 year career that really just needed to be moved to a different project or career path (and they were not NNPPs in those efforts from what I know).

Is the idea of an NNPP too negative for a CC article on bssw.io?  If so, give this a thumbs down.  If not, give it a thumbs up.

**Comment by markcmiller86** [comment]
I gave :-1: but not because I think the concept is bad. I think the implementation (e.g. this particular article) is not the one I'd like to see BSSw.io curate on this topic. Is there another, maybe better, alternative? Am interested though what others think too :smile:

**Comment by bartlettroscoe** [comment]
@markcmiller86, well, here is the original article on NNPPs:

* http://www.pyxisinc.com/NNPP_Article.pdf

but that is not much more positive and it overestimates the percentage of NNPPs on an average project, IMHO.

I mention this because the concept of an NNPP was presented to me in the [10x course by Construx](https://www.construx.com/courses/10x-software-development-teams/) that was given at SNL years ago and it stuck with me.  It seems like anything thought in that course (which was an excellent course that everyone can value from taking in my opinion) should be acceptable to put on a site like bssw.io.

**Comment by maherou** [comment]
Steve McConnell’s discussion of 10X programming was focused on a positive spin, pointing out that the _best_ programmers are substantially better than average.  The problem I have with the articles you mention is the negative spin.  The are focused on a person, rather than specific behaviors, basically a personal attack.

Beyond the tone of the article, the indicators listed are fairly short term and focused on development.   Some of the most destructive NNPP behavior I have seen over the years is the development of large volumes of code that are produced quickly, have tests, documentation, etc., but are poorly designed, not modular, and difficult to maintain and extend, especially for the next developers who come along.

This kind of NNPP behavior is very destructive for products like scientific software, which need to live a long time.  It’s much harder to detect.  In fact, it might not be noticed for many years.

**Comment by bartlettroscoe** [comment]
Here is an interesting and more balanced discussion of NNPP:

* https://wiki.c2.com/?NetNegativeProducingProgrammer

> Beyond the tone of the article, the indicators listed are fairly short term and focused on development. Some of the most destructive NNPP behavior I have seen over the years is the development of large volumes of code that are produced quickly, have tests, documentation, etc., but are poorly designed, not modular, and difficult to maintain and extend, especially for the next developers who come along.

What code is that that?  What level of testing?  Almost any code that is well tested and performs its intended function correctly is more maintainable than just about any code that has no tests or poor tests. It really does not matter what the design is, because if the tests are good, you can refactor it to meet new needs without breaking existing functionality and users.  The issue might be the the developers don't have refactoring skills?  The #1 key to sustainability is high quality tests.  Everything else is secondary.

**Comment by markcmiller86** [comment]
@bartlettroscoe I've read the new article you've suggested and :-1: it for CC as well. Boy, I guess I sound pretty negative. I think true NNPP is *rare*, perhaps too rare to devote much time to hosting content about it here. While the alternative article is more balanced, it is also a set of resplies to the original post and doesn't make for the easiest, must useful reading.

**Comment by bartlettroscoe** [comment]
Thanks, I will go ahead and close this as "WONTDO".

**Comment by bartlettroscoe** [comment]
Close as "WONTFIX"

**Comment by maherou** [comment]
> Here is an interesting and more balanced discussion of NNPP:
> 
> * https://wiki.c2.com/?NetNegativeProducingProgrammer
> 
> > Beyond the tone of the article, the indicators listed are fairly short term and focused on development. Some of the most destructive NNPP behavior I have seen over the years is the development of large volumes of code that are produced quickly, have tests, documentation, etc., but are poorly designed, not modular, and difficult to maintain and extend, especially for the next developers who come along.
> 
> What code is that that? What level of testing? Almost any code that is well tested and performs its intended function correctly is more maintainable than just about any code that has no tests or poor tests. It really does not matter what the design is, because if the tests are good, you can refactor it to meet new needs without breaking existing functionality and users. The issue might be the the developers don't have refactoring skills? The #1 key to sustainability is high quality tests. Everything else is secondary.

Bob Martin would disagree vigorously with your statement of sustainability.  He says that code that works but is not understandable by someone else is useless, whereas code that does not work but is understandable can be fixed.  Stroustrup says more specifically what is behind Bob’s comment: Good code has a single purpose.  Both of these statements emphasize the importance of design.  All the testing in the world cannot make up for poor design.

Here is a clip from Uncle Bob: https://youtu.be/7EmboKQH8lM?t=2243

**Comment by bartlettroscoe** [comment]
> Bob Martin would disagree vigorously with your statement of sustainability.

Clean code and well tested code are both important, obviously, but strong tests are more important than clean code.  Opinions will differ, but if given the choice of:

* **option-1:** Very clean code with bad tests
* **option-2:** Code that is a little messy but has very strong tests

you should choose 'option-2' every time as per:

> Code without tests is bad code.  It doesn't matter how well it is written it is; it doesn't matter how pretty or object-oriented or well-encapsulated it is.  With tests, we can change the behavior of our code quickly and verifiably.  Without them, we really don't know if our code is getting better or worse. - Micheal Feathers, "Working Effectively with Legacy Code".

For a small piece of code, none of this is really all that important.  But for a large piece of software, the behavior of the code is never all that obvious, no matter how clean someone might think it is.  That is why tests are more important.

Also, note that Bob's Clean Code course (that SNL purchased) is massively dominated by TDD compared to any other subject (including, ironically, "clean code').  Why is that?

Also "pretty code" and "understandable code" are subjective standards.  For example, if a developer uses Design Patterns that the rest of the team does not understand, does that make the code not understandable?  But another developer that does know Design Patterns may find that same very understandable.  "Understandability" is in the eye of the beholder (but there are obviously some heuristics for properties that make code more or less understandable).

To a large degree strong tests are not subjective.  If you break some important feature of the code (on purpose for example) and no tests fail, then those are bad tests.
