### ISSUE TITLE
Proposal to restrict write access to bssw.io (and images) repositories

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#581]
Following up on my email to bssw-editorial, in order to start moving towards the "preview" workflow we've discussed, I would like to close down write access to the repo, limiting it to the editorial board and the support time.  The idea is that we want everyone (including ourselves) to operate via pull requests, and the EB members and support time will be serving as the "maintainers" who must approve and merge PRs.

Please use the reactions to record your vote, and check off your name here:
- [x] David
- [x] Lois
- [x] Mike
- [x] Mark
- [x] Pat
- [x] Paul
- [x] Ross
- [x] Rinku
- [x] Jean
- [x] Greg

**Comment by bartlettroscoe** [comment]
FYI: This is a follow on from #330.

**Comment by bernhold** [comment]
I kicked my secondary account off of the repo as an experiment and I did not get any messages about it.  So I think we can put this restriction in place without having to explain why people are losing access.

If anyone has had a different experience w.r.t. notifications of repo access changes, please let me know!

**Comment by markcmiller86** [comment]
Will we ever stop handling the images as a sep. repository and simply move them into a folder in our main repo? Having them separate creates a ton of extra work, which is then exacerbated by always doing things via PRs.

**Comment by bartlettroscoe** [comment]
I vote "yes", let's restrict pushes to 'master' to just the editorial team and then only through PRs.

**Comment by markcmiller86** [comment]
FYI...I'd bet the *only* people who have ever pushed to master anyways *are* EB members anyways 😄

**Comment by rinkug** [comment]
> Will we ever stop handling the images as a sep. repository and simply move them into a folder in our main repo? Having them separate creates a ton of extra work, which is then exacerbated by always doing things via PRs.

Mark: yes, we have been delaying this since we have to re-edit all content. But, if this is a pain point, then we can make progress on this, once the preview branch is done.

**Comment by bartlettroscoe** [comment]
> Will we ever stop handling the images as a sep. repository and simply move them into a folder in our main repo? Having them separate creates a ton of extra work, which is then exacerbated by always doing things via PRs.

I am for moving images into the main bsswo.io repo, but then we should be using Git LFS for those, IMHO.  But the 'images' repo is only 217M currently.

**Comment by markcmiller86** [comment]
> but then we should be using Git LFS for those

Maybe. Git LFS adds complexity especially for the less git-inclined. I routinely see seasoned git users trip up over LFS'd content. The benefit needs to be worth it. At 217M after 3+ years of doing business, I don't think that qualifies as being *worth* it. Now, if BSSw.io traffic increases such that we start hitting GitHub monthly bandwidth quotas then may we could consider. OTOH, we could also just pay a little more for some extra data packs.

**Comment by bartlettroscoe** [comment]
> Maybe. Git LFS adds complexity especially for the less git-inclined. I routinely see seasoned git users trip up over LFS'd content. The benefit needs to be worth it.

@markcmiller86, what is nice about about using Git LFS just for images is that most people will never need to bother looking at it or messing with it.  If they don't have the git-lfs executable installed locally, it is basically just a dummy file.

But with the currently small amount of data, I agree Git LFS is not a big win at this point.  But if it does become a real issue in the future, then someone will need to filter the repo to break off the image files as LFS files and then rewrite the branches.

**Comment by bartlettroscoe** [comment]
But currently, the `betterscientificsoftware/images` repo is just a dumb data directory and if you use it like that it does not really damage the PR or the 'preview' branch process too much, IMHO.

**Comment by markcmiller86** [comment]
> Now, if BSSw.io traffic increases such that we start hitting GitHub monthly bandwidth quotas then may we could consider. OTOH, we could also just pay a little more for some extra data packs.

Actually, what I wrote here is true only if we're serving bssw.io off of GitHub servers. I don't think we are, are we? I mean, that site is built and then served from some other resources.

Given there are paths to revert to an LFS-based workflow *later*, I would recommend we put that decision off to later when its clear we really need it.

**Comment by bartlettroscoe** [comment]
> Given there are paths to revert to an LFS-based workflow later, I would recommend we put that decision off to later when its clear we really need it.

@markcmiller86, right, as long as people are willing to filter the repo branches later to convert over the Git LFS if the decision is made to do so.

But given the nature of bssw.io, I don't think there are going to be a lot of outstanding branches sitting around that will get messed up if we filter and rewrite the 'master' branch (for example).  (About everything with bssw.io git version control is simpler than with your average software project managed with git.)

**Comment by bernhold** [comment]
Changes made:
* Created a team structure for the various components (EB and others on BSSw.io team)
* Get appropriate teams access to bsswio, imagery, and bssw-blog-tracking repos.
* Remove individual account access to all three repos.
