### ISSUE TITLE
Interesting article on software forks

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#589]
* https://hal.inria.fr/hal-01519079/document

> Our investigation shows, among other results, that forks occur in every software domain, that they have become more frequent in recent years, and that very few forks merge with the original project.

**Comment by pagrubel** [comment]
After reading through this I'm not sure how it helps with Scientific Software.

**Comment by rinkug** [comment]
No interest from BSSw.io ed team
