### ISSUE TITLE
Minor bug fix needed in content

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#604]
https://bssw.io/items/producing-a-webinar-series has Contributor information that is being displayed as part of the article, but is not being picked up as metadata (there it shows the generic BSSw Community as the contributor). This should be fixed.

**Comment by karbarz** [comment]
PR has been created to fix this issue.

**Comment by rinkug** [comment]
This change was implemented as PR a while ago. Closing issue.
