### ISSUE TITLE
CC: Weapons of Math Destruction w/inventory a bunch of related articles for bias in software

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#607]
Author:?
EB member: ?

New plan: Have a cc on Weapons of Math Destruction w/inventory a bunch of related articles for bias in software

Old summary: I've run across a few articles on racial biases in software...

- [Kidney care](https://www.wired.com/story/how-algorithm-blocked-kidney-transplants-black-patients/)
- [Breast Cancer](https://qz.com/1781123/googles-ai-for-mammograms-doesnt-account-for-race/)
- [Juror Selection](https://karmaimpact.com/jury-selection-software-raises-new-concerns-of-ai-racial-discrimination/)
- [Health Care AI](https://www.nature.com/articles/d41586-019-03228-6)
- [Law Enforcement](https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing)
- [A general reference](https://www.brookings.edu/research/algorithmic-bias-detection-and-mitigation-best-practices-and-policies-to-reduce-consumer-harms/)
- [Bias in letters of rec](https://www.tandfonline.com/doi/abs/10.1080/0309877x.2017.1301410?forwardService=showFullText&tokenAccess=RrI34YuWUFU6vdZvIk2i&tokenDomain=eprints&doi=10.1080%2F0309877x.2017.1301410&doi=10.1080%2F0309877x.2017.1301410&journalCode=cjfh20)
- [Automated Underwriting - 2002](https://fcic-static.law.stanford.edu/cdn_media/fcic-docs/2001-06-29%20Rosner%20Housing%20in%20the%20New%20Millenium.pdf)

All of the examples above IMHO involve development and use of *scientific* software whether it is statistical modeling to tease out favorable trends or something more than that. 

These are all racial/ethnic bias examples. I didn't even start searching for examples of gender bias issues.

This is a problem I don't think our community may be very aware of (either the breadth or depth), may be interested to know more about and I think it is a very pertinent DE&I topic that could serve as a foundation upon which to address other DE&I topics.

**Comment by bernhold** [comment]
@markcmiller86 I'm not certain what you mean by "role".   Did you mean "blog roll", the term that I used in #474?  I don't think that's appropriate for this case.  But I don't think that really matters.

I think the topic is interesting.  Given that few of these are arguably "science", I think it is on the edge of our space, and we should perhaps think about it from that perspective.

Also, I'm adding this to the content management board.

**Comment by markcmiller86** [comment]
> Given that few of these are arguably "science"

I agree a conversation about appropriatness is appropriate. That said, I do think some of the outcome does depend on how we would opt to introduce, explain, host the content. I do think there is some fundamental aspects of both software development processes and "science" (even if basic statistics or lack thereof) we can find in these and similar articles to connect those dots in a manner similar to the way I tried to connect things to current HPC/CSE trends in the AGC articles.

**Comment by pagrubel** [comment]
Definitely interesting but also concerned about the appropriateness to the site.

**Comment by rinkug** [comment]
I like the topic. We need to spend some time understanding how to frame it in the context of our site. Will a blog article be more appropriate?

**Comment by rinkug** [comment]
Topic to be discussed during our BSSw.io call

**Comment by rinkug** [comment]
Some articles that I encountered
1. [The Hidden Biases in Big Data](https://hbr.org/2013/04/the-hidden-biases-in-big-data)
2. https://www.technologyreview.com/2019/02/04/137602/this-is-how-ai-bias-really-happensand-why-its-so-hard-to-fix/
3. https://www.sciencedaily.com/releases/2017/05/170501094343.htm (references a non peer-reviewed article: https://peerj.com/preprints/1733v1/)

**Comment by markcmiller86** [comment]
FWIW...its my impression in we've made an informal policy change to go ahead and have the HPC Workforce Retention and Development team be the place of choice for *general* inclusivity content. So, I think we can close this.

That said, the closer a given article comes to the fusion of nitty gritty HPC/CSE software and inclusivity topics, the more naturally I think it can fit here too and would, for those cases, be the preferred place for it.

Not all of the bullets in the original post here are of that ilk. So, what we could do here is a general CC article (maybe for the book "Weapons of Math Destruction") simply touching on all the ways bias in software is already known to manifest. That would basically capture the bulleted lists from above in just list form as a sort of "did you know..." kind of thing.

**Comment by markcmiller86** [comment]
I added an issue in hpc-wdr repo, https://github.com/HPC-Workforce-Development-and-Retention/hpc-wdr/issues/91

Am closing here.
