### ISSUE TITLE
Possible images for PSIP4HDF5

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#610]
![Leigh-Orf-tornado1](https://user-images.githubusercontent.com/5720676/98290104-0bc85f80-1f5e-11eb-837c-cdf28eafb08c.jpg)

![image](https://user-images.githubusercontent.com/5720676/98290570-b3459200-1f5e-11eb-9419-1f71ce5e6481.jpeg)

![image](https://user-images.githubusercontent.com/5720676/98290741-eab43e80-1f5e-11eb-9d09-afa17733c474.jpeg)

![image](https://user-images.githubusercontent.com/5720676/98290901-2a7b2600-1f5f-11eb-92da-960088e52c08.jpeg)

**Comment by markcmiller86** [comment]
Better image of black hole merger...

![image](https://user-images.githubusercontent.com/5720676/98294045-21d91e80-1f64-11eb-991d-68e4c87de079.png)

**Comment by markcmiller86** [comment]
Another example of tornado data...

![image](https://user-images.githubusercontent.com/5720676/98300266-e6dbe880-1f6d-11eb-96a4-095c0753cef8.png)

**Comment by markcmiller86** [comment]
From some earthquake simulation data...

![ECP2020McCallenFinal](https://user-images.githubusercontent.com/5720676/98423471-89b26680-2043-11eb-92ea-7d38a72fb76f.jpg)

**Comment by markcmiller86** [comment]
Images for the 3 PTCs...

# Documentation (IG1)
![Screen Shot 2020-11-11 at 8 12 43 PM](https://user-images.githubusercontent.com/5720676/98894723-43ea0980-245a-11eb-8866-80b2bdd28463.png)

# GitHub Migration (IG2)
![Screen Shot 2020-11-11 at 8 12 13 PM](https://user-images.githubusercontent.com/5720676/98894706-3765b100-245a-11eb-8374-d5179b143eb3.png)

# Coding Standards (IG3)
![Screen Shot 2020-11-11 at 8 11 33 PM](https://user-images.githubusercontent.com/5720676/98894665-1b620f80-245a-11eb-97b0-78dae861bf30.png)

**Comment by markcmiller86** [comment]
Here is the *full* pdf report of the project. We should host it here or on PSIP pages and link to from this article.

[IM-1025629-3.pdf](https://github.com/betterscientificsoftware/bssw.io/files/5532283/IM-1025629-3.pdf)

**Comment by bsswimagery** [comment]
Here are 4 options for PSIP page crops for the article. I'm seeing it as the larger the image, the more disruptive it will be to the page. 

![PSIP_Card_Large](https://user-images.githubusercontent.com/29778170/99086092-a93f1700-258e-11eb-8a7b-42135df6d46e.png)
![PSIP_Card_Med](https://user-images.githubusercontent.com/29778170/99086095-aa704400-258e-11eb-8064-1fceeb95e685.png)
![PSIP_Card_SmA](https://user-images.githubusercontent.com/29778170/99086099-ab08da80-258e-11eb-8022-3577c2fc81a6.png)
![PSIP_Card_SmB](https://user-images.githubusercontent.com/29778170/99086102-aba17100-258e-11eb-8fbf-55746453698d.png)

**Comment by markcmiller86** [comment]
Article is now [published](https://bssw.io/blog_posts/recent-successes-with-psip-on-hdf5)
