### ISSUE TITLE
Draft of Dubey Performance Portability blog article

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#625]
@karbarz, would you mind getting this draft into a PR for the site?  I've asked Anshu to add a bio as well.

https://docs.google.com/document/d/19rDrJTJYxlDLEznpRY7nIm3wPKJUvH04cLC7OEdB3vA/edit

Thanks

**Comment by karbarz** [comment]
PR #626 created for this issue.

**Comment by rinkug** [comment]
Please follow PR #627
