### ISSUE TITLE
Can backend generate anchors for h1..h3 headers?

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#633]
I wanted to link to the middle of a blog article on bssw.io and discovered it is not possible becuase none of the page's headings have the `id=` or `name=` attribute using the same autogeneration logic as GFM. Its a simple thing to add and is yet another difference in GFM as handled directly on GitHub or in a GFM compatible browser (with extension) vs. the rendered bssw.io site and is why @rinkug had to manually add them all over the place in the [Telecom Tools](https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/ShortArticles/TelecomToolsForRemoteWork.md) article.

**Comment by bernhold** [comment]
We now have this capability.
