### ISSUE TITLE
Inclusive Terminology in Software

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#652]
As a results of Inclusive Minute and other discussions within IDEAS, we have a growing list of resources associated with "inclusive naming".  I think we should put them together into a curated content article so that others can more easily find them too.

* https://inclusivenaming.org/
* https://github.com/conscious-lang/conscious-lang-docs
* https://sddiproject.org/
* https://www.theopensourceway.org/ (?)
* https://tools.ietf.org/id/draft-knodel-terminology-00.html
* https://developers.google.com/style/inclusive-documentation

**Comment by bernhold** [comment]
Also: https://github.com/kubernetes/community/tree/master/wg-naming

(From #608)

**Comment by rinkug** [comment]
@karbarz :  Please convert to table format
