### ISSUE TITLE
Rubber Duck Debugging

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#654]
I think a lot of people don't know about this technique (and maybe not by this name).  Seems like it might be worth a CC article.

This was inspired by this blog post: https://www.hanselman.com/blog/the-art-of-rubber-ducking-or-rubber-duck-debugging
It is probably worth a bit of googling to see if there are better resources to refer to.

**Comment by bernhold** [comment]
Yes, that's exactly it!  What you really need is to think through it carefully for yourself.  The act of trying to explain it to someone else causes you to do that.  But the other person is just a prop, and you might as well explain it to your favorite bath toy, your cat, or your Dancing Storm Trooper doll.  You just have to really think/explain, not simply go through the motions.

**Comment by markcmiller86** [comment]
![200w](https://user-images.githubusercontent.com/5720676/103719997-385d1f80-4f7f-11eb-87e5-f4fd7aa05209.gif)

**Comment by bernhold** [comment]
The Wikipedia article https://en.wikipedia.org/wiki/Rubber_duck_debugging provides an origin story: apparently the first known reference is in The Pragmatic Programmer.
