### ISSUE TITLE
Software versioning

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#662]
We should have a CC (or original article) for resources related to software versioning. That is the *identification* of unique states of a piece of software (e.g., releases), not version control.

https://en.wikipedia.org/wiki/Software_versioning appears to provide a pretty good description of the general principles and approaches.  Usefully, it points out that some communities have their own ways of identifying versions.

https://semver.org/ is a widely used definition for Semantic Versioning.
https://calver.org/  describes approaches to Calendar Versioning.

**Comment by bernhold** [comment]
@bartlettroscoe In the PR I tagged this issue as being resolved by the PR.  My understanding is that with that link, GitHub will automatically close the issue when the PR is merged.  Maybe a bit later than we'd like, but automatic.  I like cleaning things up promptly, but I wonder if it is worth the extra effort to manually close the issue rather than waiting for the automation?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe In the PR I tagged this issue as being resolved by the PR. My understanding is that with that link, GitHub will automatically close the issue when the PR is merged. Maybe a bit later than we'd like, but automatic. I like cleaning things up promptly, but I wonder if it is worth the extra effort to manually close the issue rather than waiting for the automation?

@bernhold, as per:

* https://betterscientificsoftware.github.io/bssw.io/bssw_curatedworkflow.html

> 6. Issues in In Progress are handled as follows: 
> * ...
> * Authors submit Pull Requests (PR) for completed work
>   * ...
>   * Close the associated Issue, add comment that continued discussion will occur in the PR `#<pr-id>`, and remove the issue from the “Content Development” board. (Unless a PR was created from the start instead of an Issue, see note below.)

**Comment by bernhold** [comment]
Yeah, that's what it says.  The question is whether its worth the extra step?  I guess I'm proposing we change our workflow (in a small way).

**Comment by bartlettroscoe** [comment]
> Yeah, that's what it says. The question is whether its worth the extra step? I guess I'm proposing we change our workflow (in a small way).

@bernhold, changing the workflow is fine by me.  I was just following what was documented and what we previously agreed upon as a group.  Makes sense to me to keep the issue open until it is resolved (which it is not until the PR is merged).

**Comment by bernhold** [comment]
@bartlettroscoe I created #1072 to capture the proposal for discussion with the EB.  If you have further comments about the workflow, let's move there.
