### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#664]
https://reproducible-builds.org/

**Comment by pagrubel** [comment]
Definitely a good topic but the site is lacking

**Comment by bartlettroscoe** [comment]
An important topic but the I would need to read through this site much more thoroughly to know if we should recommend this or not.   I think the Wikipedia article:

* https://en.wikipedia.org/wiki/Reproducible_builds

does a better job of defining "Reproducible builds" and is very short.  And that article actually links to https://reproducible-builds.org/.  So if Wikipedia has a nice "Reproducible builds" article that links to https://reproducible-builds.org/, why bother creating a bssw.io CC article?

On a side-node, I wonder if CMake/NInja and CMake/Makefiles satisfies this criteria (i.e. reproducible binary bit-for-bit)?  (I would hope it does but we should ask.)

For now, I will vote to abstain for this particular site https://reproducible-builds.org/

**Comment by bartlettroscoe** [comment]
FYI: This site reproducible-builds.org is specifically mentioned in the CII Best Practice [[build_repeatable](https://bestpractices.coreinfrastructure.org/en/criteria?details=true&rationale=true#1.build_repeatable)] (see https://github.com/betterscientificsoftware/bssw.io/issues/807#issuecomment-867195084).

**Comment by bernhold** [comment]
@bartlettroscoe interesting.  As far as I can tell, it is important to packagers (think RPMs, etc.) and others who worry about supply-chain verification. I know for example, that LLNL worries about some such things (I don't know specifically about reproducible builds) for their systems.  The Open MPI project has a mode where it can generate reproducible builds.  It is not the default because it requires you to turn off a bunch of things that are considered useful (sorry, I don't remember the details).

I still think this is probably beyond what most scientific software developers need to worry about, but I don't think it would be out of line to have a CC for it. (I know the issue is closed, but we could reopen.)

**Comment by bartlettroscoe** [comment]
@bernhold, turns out that GCC and Clang by default don't provide for bit-for-bit reproducible builds, unless you set a special flag (i.e. [-frandom-seed](https://blog.conan.io/2019/09/02/Deterministic-builds-with-C-C++.html)).  So it turns out that it can be pretty hard to do in practice with just the raw compilers and linkers.

**Comment by bartlettroscoe** [comment]
@bernhold, the point that I was making was that to receive the silver CII Best Practices, your project MUST provide for a reproducible build.  Therefore, if we sell the CII Best Practices Badge program, this the issue of reproducible builds should take care of itself.
