### ISSUE TITLE
Balancing Scientific Progress with Sustainability

### ISSUE THREAD

**Issue by frobnitzem** [betterscientificsoftware/bssw.io#668]
## Potential Blog Article

* title: Balancing Scientific Progress with Sustainability
* author: David M. Rogers (@frobnitzem)
* category: Planning/Software Process Improvement

## abstract

As a specialist in GPU programming and design of scientific software, I get to interact with many different kinds of software teams.  Among the most interesting ones I work with are medium-sized teams (2 to 10-developers) working directly toward high-profile science goals.  This article describes a strategy for successful multi-year engagements with such teams: understanding both the project's scientific/feature goals as well as its reproducibility and sustainability enough to balance the two.

**Comment by bernhold** [comment]
Added this suggestion to the blog planning board.

**Comment by bartlettroscoe** [comment]
Closing since https://github.com/betterscientificsoftware/bssw-blog-planning/issues/65 was created and we deal with blog articles there.
