### ISSUE TITLE
Mine SSI guides for curated content

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#675]
author: @pagrubel 
EB member: @bartlettroscoe 

The UK Software Sustainability Institute has a collection of "guides" they've produced over the years.  Think of them as roughly equivalent to our original articles.

I think it would be a good idea for BSSw to point to many/all of them.  Not sure how to package them (one cc, multiple ccs for groups, or individual ccs).

https://www.software.ac.uk/resources/guides

**Comment by rinkug** [comment]
Maybe 1 cc for the entire page? Alternatively 4 CCs for managers, developers (i.e each category) etc. with some brief explanation of each?

**Comment by pagrubel** [comment]
I think we should have one cc for the entire page. If someone reviews the site for the CC and they see something of more importance they could submit another issue for that.

**Comment by pagrubel** [comment]
PR# 1060 will satisfy this issue
