### ISSUE TITLE
Update software citation resource

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#697]
https://bssw.io/items/introducing-the-force11-software-citation-implementation-working-group

Should probably add these two papers which are specific products of the WG:
https://doi.org/10.7717/peerj-cs.86
https://doi.org/10.12688/f1000research.26932.2

**Comment by rinkug** [comment]
@karbarz :  Please convert to table format

**Comment by karbarz** [comment]
PR #1060 created for this issue
