### ISSUE TITLE
Do we need file naming conventions?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#705]
This came up in #703 but maybe should be considered more broadly (text content files as well as images).

In working with @karbarz we have developed some preliminary conventions, but I'm not sure they've been written down anywhere.  And they certainly haven't been applied retroactively.

**Comment by karbarz** [comment]
https://betterscientificsoftware.github.io/bssw.io/bssw_file_naming.html

@bernhold  - This is what we have so far on the EB Docs site.

**Comment by rinkug** [comment]
Established working group with David, Rinku and Kasia to drive this to completion.

**Comment by rinkug** [comment]
@bernhold : can we close this?
