### ISSUE TITLE
Institute automated quality control checks on content

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#707]
Issue #334 questions how these should be implemented but we should start doing quality control checks on the content.

Consider:
1. Check for title collisions across repository. The way the backed for the site works requires that every article have a unique title. Collisions cause a lot of problems and are hard to debug when they occur. (Most common cases is testing a variant of a document and not changing the title.) We need to check for this and not allow such problems to be committed to the repository.
2. Validate metadata in each article. (We have an old script, but it is quite out of date. See #136 )
3. Link checking. (This seems pretty clear-cut and can probably be implemented with an existing automation.)
4. Spell checking of content. (This seems pretty clear-cut, and can probably be implemented with an existing automation.)
5. A custom "linter" for the content.  These are Markdown documents, but there are specific structural and content requirements imposed by the backend.
6. Grammar checking of content. I am not aware that there is any good basis on which to build a GH automation around this -- most of the grammar checkers I'm aware of are web services designed for human interaction, or built into interactive tools like MS Word.  So this may be a non-starter.

**Comment by bernhold** [comment]
@bernhold is working on getting help from the ORNL RSE team on these.

**Comment by markcmiller86** [comment]
Ok, I've got something closer to doing what we want in a test repo, here...

https://github.com/markcmiller86/ghactions-test/blob/main/.github/workflows/foo.yml

**Comment by bernhold** [comment]
This has been overtaken by #1163
