### ISSUE TITLE
Give EB access to the preview site

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#709]
This is somewhat related to, but distinct from the preview *workflow* we're in the process of implementing.

We need to give the EB
1. Login credentials for the preview site
2. A demonstration of how to rebuild the site, and related considerations

**Comment by rinkug** [comment]
This was done in early March. If you missed it, please contact me.

**Comment by bernhold** [comment]
@rinkug did you actually distribute the login and give a demo?  That's what I think we need to do, but *I* haven't done it yet.

**Comment by bernhold** [comment]
Rinku says she did demo, on a call that I missed.  So we can re-close
