### ISSUE TITLE
Remove "categories" metadata tag

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#712]
The "categories" tag in metadata is a remnant from previous versions of the BSSw website. It is no longer used. The "topic" tag in metadata is used to display the corresponding categories that they belong to. 

@karbarz : Please create one PR for:
- [x] Remove the section on categories from the[ EB docs metadata page](https://betterscientificsoftware.github.io/bssw.io/bssw_content_metadata.html)
- [x] Remove the word "categories" from other locations where it is not needed. [This page](https://betterscientificsoftware.github.io/bssw.io/bssw_content_publishing.html) is one such example.

@karbarz : Please create another single PR for:
- [x] There are content examples files mentioned on the EBdocs website in several places. These example files can be found on the [cc](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_curated.html), [original content](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_originalarticles.html), [events](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_event.html) pages, mostly. We need to remove the categories metadata from each of the files that serve as an example. 
Following is an example of what the metadata looks like
< !---
Publish: yes
Pinned: no
**Categories: skills, development** <-- THIS LINE NEEDS TO BE REMOVED
Topics: revision control, development tools
RSS update: 2021-02-16
--->

**Comment by karbarz** [comment]
PR #713 has been created for the first requested portion of edits, focusing on removing reference to the categories tag on the EB Docs site-specific pages.

An additional PR will be created for removing the categories from the metadata of examples listed on the EB docs site.

**Comment by karbarz** [comment]
PR #714 has been created for the second requested portion of edits, focusing on removing the categories tag in the metadata of examples. 

This issue should now be completed. 
@rinkug @curfman
