### ISSUE TITLE
Taking control over About and similar content

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#717]
Changes to the About section of the site seem to be highly dependent on action by SBX/PC.  (I am not even sure if that content is even in our repo.)  It would be a nice (but not urgent) goal to get those into the repo and under our control.

**Comment by bernhold** [comment]
<https://bssw.io/pages/meet-our-fellows> is another page that's not under our control.

**Comment by bernhold** [comment]
@curfman we had a discussion with PC and SBX in Basecamp a while ago about this.  Did we conclude that we now have control over what is reasonable for us to control?  Or are there still action items on this topic? (My memory is, of course, terrible, so I'm hoping you can help us close this out.)

**Comment by bernhold** [comment]
I just stumbled on the discussion we had in Basecamp with SBX and PC on this subject. The thread there is titled "Managing *all* content through the repo (long-term)" and the last message was 2021-07-16. (Not providing link to private content.)

The conclusion is that what we can easily control (straightforward Markdown) is already under our control.  The one further step we *might* want to take at some point would be to example some of the erb files in the front-end code base, particularly for the Team and BSSwF sections.  An alternative strategy would be to propose PRs in the front-end repo.

**Comment by rinkug** [comment]
@bernhold will take a look

**Comment by bernhold** [comment]
Done what we can
