### ISSUE TITLE
Refining the rules for Topic Review?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#733]
I'm working with an RSE to get some automated help for managing the Topic Review step on our Content Board.  I want to get some input on this.

Our current rule is simply an excess of two more positive reactions than negative reactions.

Should we call the voting done the instant this is achieved?  Should we keep the voting open for a minimum or maximum amount of time?  Should we require a minimum total number of votes? (For example, should we require that at least half of the EB members vote before we close the vote?)

**Comment by bernhold** [comment]
My proposal is that we require at least 50% of EB members to vote, and when we reach that point if the net reaction is +2 or more, the proposal is approved.  Anything less than +2 the proposal is closed with no interest.

The thinking is that the purpose of Topic Review is to get the EB consensus as to whether the topic of a proposed article is in scope for BSSw. It would be best if that determination represented a reasonable portion of the EB membership.  If we leave it with just an excess of 2, we could have as few as 2 EB members deciding these questions.

The disadvantage is that we need to get people to actually vote (though my hope is that automations can help us increase the awareness of where votes are needed) and also a concern that it could promote a higher level of discussion around this stage of review than I, personally, believe we should be spending.

But comments on this as well as alternative proposals are welcome.

**Comment by prwolfe** [comment]
A 50% quorum seems good to me and it's not that large a number in this group.

**Comment by bernhold** [comment]
@prwolfe officially, we have 10 EB members, though at present, only 8 are actively participating.  So the quorum would be 4-5, depending on how we decide to handle that.

**Comment by markcmiller86** [comment]
Is this topic review rule *only* for CC or for *all* proposed content?

I am in favor and have indicated so by a 👍 to orig. comment.

This firms up *how* voting will be conducted but I wonder if the biggest hurdle to ensuring people vote remains the time we feel we need to take to fully underestand or otherwise assess the proposed material?

Does it make sense to also define *what* a vote means (and maybe what it doesn't mean) too? 

A possible proposal for that...

> A *vote* is your initial reaction (gut feel) to whether the material is likely a *good fit* for bssw. Remember, even after voting, we have a editorial review before anything goes live. Deciding a vote shouldn't take more than a few mins. It shouldn't require any in-depth reading or cross-checking of source material, etc. And, if you vote something down, you are not required to explain or defend your vote. Just vote and move on.

**Comment by bartlettroscoe** [comment]
Experience seems to show that the a larger problem is getting approved items worked and turned into a bssw.io contribution (and I am a guilty of this as anyone).  The board is already full of plenty of approved items to work.

Related to my epic SEPW-211

**Comment by bernhold** [comment]
@markcmiller86 in principle Topic Review could be any type of content.  In practice, we've applied it almost entirely to CC and original articles.  Events have always seemed (to me, at least) pretty straightforward.  Blogs we've been handling differently.

In this ticket, I'm mainly thinking about how to facilitate the Topic Review process with automation.  But your point about the decision rubric is something that we've discussed a number of times in EB meetings.  Your proposal for that sounds about right to me.

**Comment by bernhold** [comment]
@bartlettroscoe very true, but I can't automate the writing of content. :-(  I find the mechanics of the TR voting process very cumbersome so I'm trying to create some automations that make it easier to know which issues need attention and which are ready to graduate (or die).

**Comment by markcmiller86** [comment]
> but I can't automate the writing of content. :-(

I think all you may need to do is improve your ML/AI skills 😋

**Comment by rinkug** [comment]
I am in favor of 50% quorum and 2+ positive votes. The "vote" definiton by Mark also sounds reasonable. 

1. How long do we keep the item open for votes?
2. Is there any easy way to remind people of pending items to vote after X time has passed?
3. Can the label "no-interest" (or something other label) be assigned to the items if they are being auto closed by the automation tool? This would be good to have - so that we can eyeball items that are being closed by automation and ensure that they are functioning correctly etc.

**Comment by bernhold** [comment]
> > but I can't automate the writing of content. :-(
> 
> I think all you may need to do is improve your ML/AI skills 😋

Yes, I suppose if AIs can write papers that pass peer review, they actually might be able to generate BSSw content :-)

**Comment by bernhold** [comment]
> 1. How long do we keep the item open for votes?

One way would be to hold it open until we reach the quorum. I think that's what I'd propose.  But we could add a time limit if we felt it was useful.

> 2. Is there any easy way to remind people of pending items to vote after X time has passed?

My plan is for the automation to add a label like "needs votes" to anything short of our defined quorum.

> 3. Can the label "no-interest" (or something other label) be assigned to the items if they are being auto closed by the automation tool? This would be good to have - so that we can eyeball items that are being closed by automation and ensure that they are functioning correctly etc.

Yes, that's what I was thinking.

**Comment by bartlettroscoe** [comment]
> My plan is for the automation to add a label like "needs votes" to anything short of our defined quorum.

Technically, every new issue "needs votes", no?

**Comment by bernhold** [comment]
> Technically, every new issue "needs votes", no?

Only those in the Topic Review column

**Comment by markcmiller86** [comment]
> One way would be to hold it open until we reach the quorum. I think that's what I'd propose. But we could add a time limit if we felt it was useful.

That is in fact the way I read @bernhold's initial proposal...that it stays open until quorum is reached (e.g. it has 4 or 5 votes). At which point it is closed if the count of :+1: minus the count of :-1: is less than 2. But, we have had several occasions where various of us have voted something other than either :+1: or :-1:. If we agree that the only acceptable votes are :+1: or :-1:, we can ignore anything else from *counting* but nonetheless use it for determining quorum.

**Comment by markcmiller86** [comment]
This might suggest that the *final* vote, the one just prior to quorum, may in those cases where opinions are highly varied, carry the biggest weight (which is fine I think).

Also, maybe whoever casts the quorum-producing vote then also be responsible for closing when appropriate.

**Comment by markcmiller86** [comment]
> If we agree that the only acceptable votes are 👍 or 👎, we can ignore anything else from _counting_ but nonetheless use it for determining quorum.

Thinking more, using votes other than :+1: and :-1: to count towards quorum be a useful way to reach quorum without skewing results. In other words, when you vote, you are welcome to vote something other than :+1: or :-1: with the understanding that your vote does accelerate the issue to closure (e.g. quorum) but does not impact the final recommendation. It is a way of saying, I've looked at this too and am on the fence so am happy to let others with stronger opinions decide.

**Comment by bartlettroscoe** [comment]
> Thinking more, using votes other than 👍 and 👎 to count towards quorum be a useful way to reach quorum without skewing results.

I agree with that.  Sometimes a person may not feel strongly one way or the other and it would be good to allow that type of "abstain" or "present" vote.  I think the right reaction icon for that would be 😕 or  👀.

**Comment by bartlettroscoe** [comment]
> This might suggest that the final vote, the one just prior to quorum, may in those cases where opinions are highly varied, carry the biggest weight (which is fine I think).

That is a good point.  Then perhaps having a set time limit for voting is needed and when that time is up, the votes are tallied.  That solves that problem.

**Comment by bernhold** [comment]
I agree that we need to have a concept of neutral votes and count them towards quorum.

While it is possible to game a simple system, I hope that we can trust this group not to do that.  We're not voting for president, after all.

I don't object to a time limit if we find it hard to achieve a quorum in a time frame we consider reasonable.  But this is not a major issue until we're dealing with more outside submissions and want to make sure we give them prompt service.

I propose we focus on the simple quorum until we see that's insufficient.

**Comment by pagrubel** [comment]
I haven't ignored this, just not much to add to the discussion. I agree that votes other than 👍  or 👎  should count towards quorum. I will be more careful using them, although when I had used them at least I knew I had reviewed that submission. Time limits should somehow be taken into consideration.

**Comment by bernhold** [comment]
Summary of where I think we are:
1) A quorum of 50% of the EB membership is required to close a vote
2) All reaction votes count towards quorum
3) Only 👍 and 👎 count for the outcome of the vote
4) To proceed to development the requirement is two more positive votes than negative.

**Comment by bernhold** [comment]
Agreed in 2021-04-08 EB meeting.

Followups:
1) David is working with ORNL RSEs to implement a GitHub Action to help us manage voting
2) We probably need to revise the EB documentation to reflect these changes.

**Comment by bernhold** [comment]
2021-05-13 EB meeting: we need to close this out.  Propose to discuss at next EB meeting.

Summary of proposed new rules is:
 
> 1. A quorum of 50% of the EB membership is required to close a vote
> 2. All reaction votes count towards quorum
> 3. Only 👍 and 👎 count for the outcome of the vote
> 4. To proceed to development the requirement is two more positive votes than negative.

The remaining open question is whether to set time limits for the vote.  Do we want to keep it open until we reach 50% quorum, however long that takes?  Or do we want to give up after a while if we can't even muster a quorum?

@betterscientificsoftware/bssw-editorial-board please comment so we can close this out.

**Comment by markcmiller86** [comment]
Actually, item 1 does specify the time limit...until 50% of EB membership has weighed in ;)

Can we just add to that *or 30 days have passed since submission* and use GitHub action to close the vote when...
* 50% of EB membership has weighed in (e.g. number of reactions divided by number of members >= 0.5)
or
* 30 days have elapsed

The action to take (carry forward or close the issue) depends on the vote outcome.

**Comment by bernhold** [comment]
Mark, I think this is a practical strategy.  It does depend on us being diligent in getting issues on the board and voting for them in a timely fashion.  But I think this is a reasonable expectation to set for EB members. (If we were getting significant outside content ideas, I'd want to reduce the time frame so that we would be more responsive to them -- maybe 1-2 weeks.  But that's not where we are right now.)

It does also suggest that maybe new issues should go straight into the Topic Review column (i.e. voting starts immediately) and then graduate to a backlog, which is effectively what Ready to Write is anyway.  The one thing with this is what to do with issues that are not sufficiently defined to actually judge their appropriateness?  Maybe we just vote those down?

**Comment by markcmiller86** [comment]
Actually, my proposed logic (e.g. the `or` operator) would have the unintended effect that moment the 50% of EB members threshold has been exceeded, whatever the vote count is at that moment would determine the disposition of the issue. We don't want that either.

Half+1 of the EB members could all weigh in on the day it is submitted with a 2 more :+1: than :-1: vote and the remaining members wouldn't get a chance to vote. Our policy is to not close a vote until at least half EB members have weighed in. But, that doesn't mean we should indeed also close *every* vote at that moment, does it? Everyone needs sufficient time to weigh in.

So, I think it just needs to be time based and we need to come to agreement on that time cut-off. I proposed 30 days but maybe that isn't sufficiently long enough. I'd be fine with more time. But, I think we need to have a cut-off and a GitHub action to automate this maybe with warning email a week prior to closure..."voting on these items will be closing soon".

**Comment by bernhold** [comment]
Mark, in principle, your idea makes sense.  In practice, it adds a lot of complexity.  Also, I think we need to establish rules that support responsiveness (to outside contributors) and set the expectation that EB members will respond timely rather than rules that favor waiting for every last voice on the EB to be heard at the expense of responsiveness.

You can view closing when the quorum is reached as a motivation to get your vote in sooner rather than later.  

I propose that we close votes after a quorum is reached or 30 days has elapsed, whichever comes first. (I'd really like to get it down to 2 weeks.)

**Comment by rinkug** [comment]
Do we still want to discuss this?

**Comment by rinkug** [comment]
Right now, we dont have a very effective process for this. But we dont have the bandwidth to formalize something new.
