### ISSUE TITLE
"Debunking the Myth" article

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#734]
Author: @rinkug 
EB member: @curfman 

Possible curated content (suggested by @curfman , to be authored by @adubey64 potentially?):

S. Smith, M. Srinivasan and S. Shankar, "Debunking the Myth That Upfront Requirements Are Infeasible for Scientific Computing Software," 2019 IEEE/ACM 14th International Workshop on Software Engineering for Science (SE4Science), Montreal, QC, Canada, 2019, pp. 33-40, doi: 10.1109/SE4Science.2019.00011.
 
https://ieeexplore.ieee.org/abstract/document/8823765/authors#authors

**Comment by bernhold** [comment]
Perhaps even a blog article?

**Comment by markcmiller86** [comment]
I don't have the full PDF (I *was* genuinely curious) but the abstract alone may actually contradict the title and suggests that the paper goes into all the tools and technologies of *agile* methodologies to help deal with the fact that up-front requirements are either not known correctly or not known at all.
