### ISSUE TITLE
Develop and give a tutorial on the PR process and the preview workflow

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#743]
Many folks on the BSSw team are not comfortable with how to properly utilize the preview workflow, and some are not familiar/comfortable with the pull request process that underpins it.  We need to develop a small tutorial and deliver it to the team, including SBX and PC.

While this could be powerpoint-ware, it might be more useful if it were something we could easily incorporate into the docs tree.

**Comment by bartlettroscoe** [comment]
Beyond [this description](https://github.com/betterscientificsoftware/bssw.io/blob/master/docs/pages/bssw/bssw_pr_preview_branch.md) and a basic understanding of Git and GitHub, what else is needed?  This is nothing more that the usage of 'next' branch (which we call 'preview') described in the standard [gitworkflows](https://git-scm.com/docs/gitworkflows) documentation.

**Comment by bernhold** [comment]
@bartlettroscoe IMHO, that's way too complicated.  We don't *want* people to have to understand all of that to contribute.  It should be very straightforward from the contributor perspective, and we need to provide documentation from that perspective on the EB docs and present it to our team to vet it.

**Comment by bartlettroscoe** [comment]
>  We don't want people to have to understand all of that to contribute.

Right, only EB members should have understand the 'preview' branch and preview.bssw.io updating and viewing process.  Authors should just have to:

* Create a new branch off of 'master' with updated `*.md` and image files (created using a template `*.md` file to take care of the details)
* Post a PR against 'mater' for their new branch
* Respond to feedback from reviewers in the PR for any suggestions for changes to **content** and push new commits for revisions to **content**

An author should never have to worry about merge conflicts from their PR to 'preview'.  The EB member should take care of all of that if occurs.  (And merge conflicts will occur much less if we adopt PR #765 and only selectively merge PRs to 'preview' when needed.)

But at the same time, if authors are curious about how the 'preview' branch workflow works, then they should be able to see this explained (if nothing else to serve as an example to use Git in their own projects that may have similar challenges).

**Comment by bartlettroscoe** [comment]
@bernhold, is this still needed?  It seems things have been running smoothly in the last few months with the preview branch workflow.

**Comment by bernhold** [comment]
I'm inclined to think we can close this.

**Comment by rinkug** [comment]
Yes, I will go ahead and close this.
