### ISSUE TITLE
CC Article on GitHub Actions

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#746]
Various of us here have learned a bit about GitHub Actions and found some useful refs. We should at least mine that experience to craft a short CC. Here are some resources to include in one...

* https://itnext.io/getting-started-with-github-actions-fe94167dbc6d
* https://gist.github.com/br3ndonland/f9c753eb27381f97336aa21b8d932be6

**Comment by rinkug** [comment]
Please see #764 for further discussion
