### ISSUE TITLE
IDEAS events at Community BOF

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#748]
Please create
* 1 event for IDEAS events OR
* Individual events for each IDEAs event

**Comment by bernhold** [comment]
Rinku, we already have an event for the Community BOFs.  Maybe I misunderstand, but I don't think it is appropriate to add more just for ours.  If that's what we wanted, we should have done it that way initially.

**Comment by bernhold** [comment]
I think we decided not to pursue this.
