### ISSUE TITLE
Remove old tests/ directory in bssw.io repo?

### ISSUE THREAD

**Issue by bartlettroscoe** [betterscientificsoftware/bssw.io#751]
@betterscientificsoftware/bssw-editorial-board, @jwillenbring, @william76 

Was just looking at the bssw.io repo as part of #703 and #738 and I noticed the directory `bssw.io/tests/`.  Looking at the git log:

```
$ git log-short test/
3f39735f "adding in test designed to fail the checker (#268)"
Author: William <william76@users.noreply.github.com>
Date:   Thu Mar 15 16:24:51 2018 -0600 (3 years ago)

266a4794 "Updating tests (#266)"
Author: William <william76@users.noreply.github.com>
Date:   Thu Mar 15 16:15:16 2018 -0600 (3 years ago)

aaf3d326 "Testing / validation merge (#223)"
Author: William <william76@users.noreply.github.com>
Date:   Thu Sep 7 12:37:56 2017 -0600 (3 years, 7 months ago)
```

it appears this was some attempt 3 years ago to try to get the SNL auto-tester hooked up to the bssw.io repo?

Given that we are moving to using GitHub Actions to test PRs for the bssw.io repo (see #707, #746, #443), should we just remove this `tests/` directory and its contents?  It will still be in the git history so you could always get it back if you needed it again.

Related to my epic SEPW-211

**Comment by bartlettroscoe** [comment]
Unless there is an objection, I will put in a PR that removes this since this is not being used.

**Comment by JeanShuler** [comment]
No objection from me - thanks

Sent from my iPhone

On Mar 24, 2021, at 4:16 PM, Roscoe A. Bartlett ***@***.***> wrote:

﻿

Unless there is an objection, I will put in a PR that removes this since this is not being used.

**Comment by bartlettroscoe** [comment]
PR for this is #753.  Can someone approve and then I will merge?
