### ISSUE TITLE
Write a CC article for pre-recorded Parallel HDF5 tutorial video

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#762]
https://www.youtube.com/watch?v=0yRGSMxhxd8

**Comment by rinkug** [comment]
@markcmiller86 : Is this worth writing if he already have  https://ideas-productivity.org/events/hpc-best-practices-webinars/#webinar027. We mention this resource on bssw.io: https://bssw.io/items/best-practices-for-hpc-software-developers-webinar-series

If you think it is worth it, then I can write something up.

**Comment by markcmiller86** [comment]
@rinkug I agree with you. I don't think we need this given the other resource we already have. Lets close
