### ISSUE TITLE
References/Citation guidance  in docs directory

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#769]
@bernhold, @markcmiller86 and @bartlettroscoe 

As of now, we have new guidance on how to write citations/references listed on the [original articles/blog styling page](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_originalarticles.html#citationsreferences): 

* For the purpose of consistent organization of the docs content, we need to move this guidance to the [common styling page](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html).

* We dont expect to use references/citations for curated content or events. Therefore, put a guidance note discouraging the use of these elements in the [curated content styling page](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_curated.html) and [events styling page.](https://betterscientificsoftware.github.io/bssw.io/bssw_styling_event.html)

**Comment by bartlettroscoe** [comment]
@rinkug, just to be clear, you want me to move the section on citations/references from:

* https://betterscientificsoftware.github.io/bssw.io/bssw_styling_originalarticles.html

to

* https://betterscientificsoftware.github.io/bssw.io/bssw_styling_common.html

?

Also, add some short note about preferring not to use formal citations to:

* https://betterscientificsoftware.github.io/bssw.io/bssw_styling_curated.html
* https://betterscientificsoftware.github.io/bssw.io/bssw_styling_event.html

?

And then I guess we need to update all of the references that currently exist to the current location of the "Citations/References" section?

So we should merge all of the outstanding PRs before we do that to make sure these all get updated.

**Comment by bartlettroscoe** [comment]
@rinkug, this should be resolved in PR #778.  Can you please review and approve if you find no problems (and suggest changes if you find issues)?
