### ISSUE TITLE
Reference/Citations File cleanup in repo

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#770]
@bernhold, @markcmiller86  and @bartlettroscoe 

There are 4 "ReferencesInMarkdown*.md" files listed in the [blogs directory](https://github.com/betterscientificsoftware/bssw.io/tree/master/Articles/Blog). Questions are:

* Is this the right place for them? 
* Are all these 4 files related to teaching authors how to use references? If yes, the we should either
** Create another directory in the [main repo](https://github.com/betterscientificsoftware/bssw.io) to store these files. I am guessing [utils directory](https://github.com/betterscientificsoftware/bssw.io/tree/master/utils) is not the right place for them.
** Alternatively, we can put such files in the [docs directory](https://github.com/betterscientificsoftware/bssw.io/tree/master/docs). The [docs directory](https://github.com/betterscientificsoftware/bssw.io/tree/master/docs) is primarily used for the [EB docs website](https://betterscientificsoftware.github.io/bssw.io/index.html). But, there are files (for ex: preview-related), in there, that we dont display on the EB docs website, but are still kept for reference purposes for the editorial team. All files that are displayed on EB docs website come from [docs/pages](https://github.com/betterscientificsoftware/bssw.io/tree/master/docs/pages/bssw) directory. We can create a [docs/FOO directory] to store of these files, if we want to separate out published vs. non-published pages.

If we move "ReferencesInMarkdown*.md" files listed in the [blogs directory](https://github.com/betterscientificsoftware/bssw.io/tree/master/Articles/Blog), we will need to update links on some pages of EB docs site.

**Comment by bartlettroscoe** [comment]
Seems like the contents of the directories `Articles/`, `CuratedContent/`, `Events/` and `images/` should be restricted to items that will be displayed on the bssw.io production (and preview.bssw.io) site itself.  However, I think that the document [ReferencesInMarkdownHybridApproach-wikized.md](https://github.com/betterscientificsoftware/bssw.io/blob/master/Articles/Blog/ReferencesInMarkdownHybridApproach-wikized.md) is quite excellent and I think this should be published on the bssw.io site as an original short article.  Otherwise, example `*.md` files like this likely should be stored under the docs/ somewhere.

**Comment by bernhold** [comment]
`Site/` also has content that we'd want to include in the preview site.

**Comment by bartlettroscoe** [comment]
> `Site/` also has content that we'd want to include in the preview site.

Okay, I see those now:

```
$ find Site/ -name "*.md" -exec grep -nH Publish {} \; | grep yes
Site/Communities/ComputationalMolecular.md:30:Publish: yes
Site/Communities/EnvironmentalSystemScience.md:32:Publish: yes
Site/Communities/ExascaleComputing.md:44:Publish: yes
Site/Communities/ScientificLibraries.md:29:Publish: yes
Site/Communities/SoftwareEngineering.md:24:Publish: yes
Site/Communities/SupercomputerFacilities.md:35:Publish: yes
```

and I also see the following to-level files are published too:

```
$ find . -maxdepth 1 -name "*.md" -exec grep -l "Publish: yes" {} \; 
./QuestionsAboutContributing.md
./WhatToContribute.md
```

**Comment by bernhold** [comment]
Even stuff without the Publish metata needs to be included -- basically tthe whole directory, I think.

**Comment by bartlettroscoe** [comment]
> Even stuff without the Publish metata needs to be included -- basically tthe whole directory, I think.

@bernhold, what do you mean by "included"?

**Comment by bernhold** [comment]
Included in what gets merged into the preview branch when it appears in a PR

**Comment by rinkug** [comment]
@markcmiller86 : can you close this, if needed?

**Comment by bernhold** [comment]
I don't see these files any more.  I think this has been overtaken by events.  I am closing.

**Comment by markcmiller86** [comment]
@bernhold agree with you regading the *original* comment for this issue and `ReferencesInMarkdown*.md` files. That said, [another issue](https://github.com/betterscientificsoftware/bssw.io/issues/770#issuecomment-809650283) came up here regarding pages in `Site/Communities`. Is that issue also resolved? Should another ticket be opened for it? Finally, @bartlettroscoe seemed to also be suggesting that the whole idea of *references in markdown* deserves its own short article published on bssw.io. Is there already a ticket for that?

**Comment by bernhold** [comment]
@markcmiller86 I don't understand the subthread about Sites/Communities.  That has nothing to do with citations.

As to a BSSw article about our approach to dealing with references, I would strongly suggest a template instead, which lives alongside the content (but is not published).  This is in the spirit of #857
