### ISSUE TITLE
Poster and extended abstract (AMS 2019) demonstrating use of autotools with GPTL C/Fortran HPC science libraries

### ISSUE THREAD

**Issue by edwardhartnett** [betterscientificsoftware/bssw.io#775]
In this extended abstract and poster (from the 2019 annual AMS meeting), we demonstrate a simple but complete use of autotools (autoconf/automake/libtool) to build C/Fortran libraries for the General Purpose Timing Library (GPTL). A standard build system for GPTL increases portability, aids testing, and is an order of magnitude less complex (measured by lines of code).

This build system demonstrates several features important to the science community:
* Portability of C and Fortran codes, including on HPC systems.
* Use of multi-processor test codes.
* Use of compiler flags for optimizing performance.

The paper is here: https://www.researchgate.net/publication/330347049_USING_STANDARD_TOOLS_TO_PACKAGE_AND_DISTRIBUTE_SCIENTIFIC_SOFTWARE_C_AND_FORTRAN_LIBRARIES_A_DEMONSTRATION_WITH_THE_GENERAL_PURPOSE_TIMING_LIBRARY_GPTL

The poster is here: https://www.researchgate.net/publication/330347052_Using_Standard_Tools_to_Package_and_Distribute_Scientific_Software_C_and_Fortran_Libraries_a_Demonstration_with_the_General_Purpose_Timing_Library_GPTL_How_It_Was_Done

**Comment by pagrubel** [comment]
I think an article on our site would be better than a link to a poster.

**Comment by edwardhartnett** [comment]
There is an article and a poster. If you wish to put the article on the site, I have no objection.

**Comment by markcmiller86** [comment]
CMake has been gaining a lot in popularity in HPC/CSE in the past 10 years.

Given the mandate for many HPC/CSE projects to support *native* development on not only *nix variants but also Windows and macOS, its hard to get excited about hailing the virtues of autotools here.

**Comment by bartlettroscoe** [comment]
As per [above](https://github.com/betterscientificsoftware/bssw.io/issues/775#issuecomment-1047325064), closing.  Thanks for the suggestion
