### ISSUE TITLE
1st International Workshop on the Body of Knowledge for Software Sustainability (BoKSS’21)

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#781]
https://bokss.github.io/bokss2021/

**Comment by karbarz** [comment]
https://github.com/betterscientificsoftware/bssw.io/blob/master/Events/Workshop.BoKSS21.md

I made an event for this previously - does this need to be updated? Thanks!
@bernhold

**Comment by bernhold** [comment]
You're so good!

It looks like the dates have changed to 1-2 June 2021.  Other than that, looks okay.  Thanks!

**Comment by karbarz** [comment]
No worries, I'll update the dates right now! :)
