### ISSUE TITLE
Possible route to previewing PRs for docs

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#784]
It looks like the fortran-lang.org web site has developed an approach for their Jekyll-based site where they build versions of the site based on PRs and expose them in a subdirectory of the production site named `pr/<pr number>`.  When the PR is merged/closed, they clean up the preview.

For this to work, I think you have to manually build and deploy the production site too, which is not that hard.  This repo has an action for it, but I think there are probably canned actions from the Marketplace that will also do it.

Seems like it might be useful for the bssw.io/docs site.

https://github.com/fortran-lang/fortran-lang.org/tree/master/.github/workflows

**Comment by rinkug** [comment]
@bernhold : Does our preview site take care of this?

**Comment by bernhold** [comment]
No, it does not because the ebdocs utilize GH Pages, not the BSSw front-end.  The preview site is only the front-end.

I saw somewhere that GitHub is working on incorporating PR preview capabilities into their default jekyll site builder action, but I don't know when that might be released. If I can find that again, I'll post a link here.

If this is not a serious issue for us, we might just wait for that to show up.

**Comment by bernhold** [comment]
The official https://github.com/actions/deploy-pages action says it has some kind of preview capability, which is stated to be alpha maturity and not available to the public, but I've never tried.  I think there would have to be additional support required to remove PR previews when they're merged, abandoned, etc.

**Comment by markcmiller86** [comment]
IMHO, I wonder if we're updating the *internal* docs enough or the changes we are making are of such importance that it really requires the same level of preview functionality the actual hosted site does? And, if you have Jekyll toolling locally, you can preview your changes yourself.

**Comment by bernhold** [comment]
Yeah, that's a good point too.  I would like the ability to preview a PR to facilitate peer review -- someone else can easily see the new version.  But if we trust the author to check their work locally, then maybe it suffices to look at the source changes.

**Comment by markcmiller86** [comment]
Well, so I dunno if you've paid much attention to #1830 but I have kinda sorta created a *preview* of sort for the internal docs. I have just gone to **Settings**->**GH Pages** and adjusted the branch from which it generates them. Now, thats not quite a preview because its *live*. But, I think its kinda ok because its primarily for internal consumption anyways.

**Comment by rinkug** [comment]
> No, it does not because the ebdocs utilize GH Pages, not the BSSw front-end. The preview site is only the front-end.

Argh. I didnt realise you meant EB docs in title..

**Comment by rinkug** [comment]
I dont think we need to preview EB docs. Can we close?
