### ISSUE TITLE
Are we ready to drop the "preview" option for the Publish metadata tag?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#787]
We're making progress on universal utilization of the preview workflow.  Are we ready yet to drop the "preview" option from the Publish metadata tag?

The theory is that visibility on the preview *site* should be determined by presence on the preview *branch* combined with a simple yes/no for the publish metadata. (I think it is still useful to be able to mark things as not for publication, such as templates, etc.) 

That would mean that anything we want to appear on the preview site would have "Publish: yes".  And the risk that I can see is if that content is merged to main prematurely *and* the production site is rebuilt, we might end up with something visible to the public before we intend it to be.

How might such a scenario arise?
1) We "need" to merge prematurely to complete some operation on the content.  I think it is technically possible to do everything we would need to do in the publication process on PRs.  So I think this is an issue of education.
2) We accidentally merge prematurely.  It seems that we can reduce these risks through procedures (like the new PR checklist).  Small cleanups can always be made on main, before or after the production site has been rebuilt.  If larger cleanups are required, the piece could be unpublished and fixed.

I conclude that, overall, the risks of dropping the preview setting are manageable.  Other opinions welcome.

Once we make a decision, we need to inform SBX and PC.

**Comment by bernhold** [comment]
One case that we need to be careful about: We have some documents that are not meant to be published (e.g. templates, the kitchen-sink-TEST document, etc.).  The templates should be easily visible to contributors (to me meaning the need to live in main).  The test document would be fine only living on the preview branch. But under the "preview workflow" that we've discussed, we expect to be able to rebuild the preview branch as needed from main+pull requests, and if the test document lived only on preview, they'd get lost this way.

**Comment by bernhold** [comment]
Template documents are adequately handled by 'Publish: no`

Test documents seem to be a plausible case for `Publish: preview`

PC (Clara) wonders whether there could be confusion between:
1) `Publish: preview` metadata
2) The preview git branch
3) The preview site
and whether changing some of the names might help protect the innocent?  My feeling is that most of the confusion experienced around this so far has been because our current contributors are grappling with a *change*, whereas I think someone with no prior experience coming into the site (and provided with appropriate documentation) would not have a problem.  But this question is worth further consideration.

**Comment by bernhold** [comment]
An option for the test document(s) might be to store them in a separate directory that's ignored by the front-end.  (Maybe a subdirectory of `utils`?)  They could be copied in where and and when needed and then removed once the need is over.

If we accept this, then the question is whether there are other cases where we need the `preview` metadata option, specifically.  The safety net question of reducing the possibility of premature publication remains open too.

**Comment by bernhold** [comment]
Related to this, Clara (Parallactic) suggested a separate permanent branch for "testing" content.  Not clear how it gets switched in when we want to use it, etc.  But conceptually, this would go a long way towards my concerns about getting rid of the preview metadata.

**Comment by bartlettroscoe** [comment]
After our discussion today, I vote to remove `preview` as a value for `publish` for meta-data.  Then `*.md` files created on a branch that need to be previewed in a PR can be born with `Preview = on` right at the beginning.

**Comment by bernhold** [comment]
Discussed in EB meeting 2021-09-09.  Consensus is as follows:

1) We can eliminate the `preview` metdata option, but must keep `yes` and `no`.  Content should be "born" with `Publish: yes` and it will show up on the site for whichever branch it is on.  This will eliminate the (oft-forgotten) need to flip the metadata from `preview` to `yes` when content is ready to be published.
2) Retaining the `no` option is necessary to be able to provide article templates "next to" each type of content.  That will make them easiest for contributors to find and use.
3) If there is content we wanted to unpublish but retain long term, other than things like templates, we *could* create a new branch (`unpublished`?) to hold them.  We're not currently doing anything like this, and in the discussions there did not seem to be a feeling of need, but I wanted to document it for posterity.
4) Test content that we don't want to permanently live on either `main` or `preview` can be maintained in long-lived PRs which may never get merged by may get added/removed from preview as needed.  Such PRs should be marked as **Draft** and labeled with `type: test content` to be clear about their purpose.
5) David will notify PC that we're ready to remove `preview` option.  But I think we can stop using it already. It will work as intended without code changes.

**Comment by bernhold** [comment]
Informed PC of our decision.  Waiting for confirmation with point (5) above.

We'll need to update the checklist(s) and maybe EB docs.

**Comment by bartlettroscoe** [comment]
> David will notify PC that we're ready to remove `preview` option. But I think we can stop using it already. It will work as intended without code changes.

@bernhold, right, we an just update the EB docs and pretend the only valid values for `Publish` are `yes` and `no`.  Is there not a meta-data validator that we could not also update that would check for those values?

**Comment by bernhold** [comment]
There is a very old metadata validator, which we are not using for anything today.  I think it would need a lot of updates to be useful.  We should do that.  Sometime.  There's a very old ticket for this (#136) already.

**Comment by bernhold** [comment]
I had another thought about test content.  We could create another long-lived branch to hold test content (+ main probably).  Leave *that* around forever.  That would allow the PRs to come and go.  If we need to test, the procedure would be
1) Update test from main (I presume we'd want to do this from time to time)
2) Make a PR from test to main (which would be the test content)
3) Mark the test PR with the `preview` label to get it onto the preview branch
4) When done testing, we could close the PR without merging

This has more steps, but it means we don't always have to have the PR out there if we don't want to.  If we don't use the test content often, this might be preferable. If we do use it often, we might want to keep the PR, but I think it wouldn't hurt to have the test branch and make the PR from there anyway.

**Comment by bartlettroscoe** [comment]
@bernhold, we should go back to the basic requirements and have a short conversation about what exactly you are trying to accomplish here.

**Comment by bernhold** [comment]
I think the basic question now is: how do we manage test content?

And I think the basic requirements are:
1) We have a place where it can live indefinitely without being exposed to the public (unless we need it to be).
2) There is a straightforward mechanism to include when we need to use it
3) There is a straightforward mechanism to uninclude it when we don't.

I think the preferred solution space is things *we* can do in git and GitHub.  If necessary, we could ask Parallactic to add features to the front-end for us. (For example, we have discussed ideas about a new separate site and/or the ability to control the content branch used for the rebuild.)

Do folks agree with this baseline for the discussion?

**Comment by bernhold** [comment]
Consensus of 2021-09-23 EB discussions...

* PRs for test content are not a problem, though they may be untidy
* Long- and short-lived branches for test content, as needed, make sense
* Can move content in/out of preview as needed using git

**Comment by bernhold** [comment]
I think the final step here is for Parallactic to disable the preview metadata option.  But we can simply stop using preview on our own.  Everything will work as we want it to if we use just yes/no.

I'm going to keep this issue open until PC confirms that they've completed the code change on the front-end just to track this last step.

**Comment by bartlettroscoe** [comment]
@bernhold, we also need to update the PR template to tell people to set `Publish: yes` from the beginning.  Currently, it says to set `Publish: preview` then later to set `Publish: yes`.

**Comment by bernhold** [comment]
We dropped "preview" a long time ago.  This should have been closed then.
