### ISSUE TITLE
Document RSS Date metadata tag

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#792]
I am not aware that this is documented anywhere.  We probably need a comprehensive guide to the article metadata somewhere.

The BSSw.io site automatically generates an RSS feed.  Currently, it is capped at the 10 most recent items (this could be changed by Parallactic, if we want).  The rule is to use the *newer* of the Publication Date (within the article) or the RSS Date (in the article metadata).

If you edit an article and don't change the Publication Date or the RSS Date, the RSS feed will not change.  This what you'd typically want to do for minor updates, corrections, etc.

If you *want* the article to reappear in the RSS feed, as if it were newly published, set the RSS Date metadata tag to the current date (or an appropriate near-future date).

**Comment by rinkug** [comment]
This should be documented here: https://betterscientificsoftware.github.io/bssw.io/bssw_content_metadata.html

**Comment by rinkug** [comment]
Further discussion should be on PR #795
