### ISSUE TITLE
Spell checking needed

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#801]
We got the following through the contact form.  Unhelpfully, there is no info about where the misspelling is.

> Name: John Taylor
> Email: taylorfam44@gmail.com
> Message: 
> It looks like you've misspelled the word "acheive" on your website. I thought you would like to know :). Silly mistakes can ruin your site's credibility. I've used a tool called SpellScan.com in the past to keep mistakes off of my website.
> -John
>

**Comment by markcmiller86** [comment]
I worry this is just [spam/scam](https://nostalgicitalian.com/2020/02/01/scammer-spam-heads-up/).

I did the following and do find two hits for `acheive`...

```
miller86% pwd
/Users/miller86/ideas-ecp/bssw/betterscientificsoftware.github.io
miller86% find . -name '*.md' -exec grep 'acheive' {} \; -print
The PSIP process has been successfully used to help scientific software teams acheive incremental, sustainable process improvement, while still achieving their science goals. The *PSIP* repo is an excellent starting point in your endeavour to learn about the PSIP software process improvement methodology.
./CuratedContent/PlanningUsingPSIPs.md
```

**Comment by rinkug** [comment]
Done in PR #804
