### ISSUE TITLE
Event with two dates failing to build article

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#810]
This article: bssw.io/events/2021-us-rse-virtual-workshop, failed to build when we had May 24, 2021 and May 27, 2021 in the event date header field.

**Comment by bernhold** [comment]
A workaround would be to use March 24-27 and put the correct details in the body.

The new mechanism to handle dates in events (waiting for PC to implement) should handle this simply by having two distinct "Event Date" entries.  So in a short time, this won't matter.

Also, Internal board seems more appropriate for this.  Moving there.

**Comment by bernhold** [comment]
As of 2021-12-21 we have a new "multi-date" capability deployed on the site which addresses this issue.  I think the dates in the motivating example above could be entered in either of the following ways:

`- Date: May 24 2021; May 27 2021`
or
`- Event Day 1: May 24 2021`
`- Event Day 2: May 27 2021`
