### ISSUE TITLE
Proposed addition to "Transmedia Learning Framework for Python"

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#814]
Through the contact form, we received the following suggestion...

> Hi Elaine,
> 
> on https://bssw.io/items/transmedia-learning-framework-for-python you link to some resources for learning Python.
> 
> Our team has built a tool for learning Python on https://jobtensor.com/Python-Introduction
> 
> We created this tool because we have many tech users on our site who want to improve their programming skills.
> 
> Would you mind adding our link to your page?
> 
> Please note that the tool is completely free and contains no advertising or affiliate links.
> 
> Thanks,
> Jakob
> ________________________________________
> Dr. Jakob Sidoruk
> 
> jobtensor
> Science, IT and Engineering
> Swinemünder Str. 7
> 10435 Berlin
> T: 030 56839090
> H: https://jobtensor.com/
> E: support@jobtensor.com

**Comment by rinkug** [comment]
The tool seems useful; especially the portion where one could write short examples and execute them

**Comment by shuds13** [comment]
The content appears to be largely a mirror of https://www.learnpython.org/

**Comment by markcmiller86** [comment]
@shuds13 thanks for point that out!

I like the idea of adding a link for learnpython.org.

I would recommend we favor that over the jobtensor.com link.

**Comment by rinkug** [comment]
@bernhold : Please check PR #846 to fulfill this.
