### ISSUE TITLE
Updates to older articles

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#836]
The following older articles need to be formatted correctly.

- [x] 1. The article titled [Documenting Your Code](https://github.com/betterscientificsoftware/bssw.io/edit/master/CuratedContent/KlinvexATPESC2016REVISE.md) needs to be converted to curated content. Please update deck, table, description, metadata etc

- [x] 2. The article titled [Transmedia Learning Frameworks (TLF)](https://github.com/betterscientificsoftware/bssw.io/blob/master/CuratedContent/TransmediaLearningFrameworksREVISE.md) needs to be converted to curated content focussing on the the following [VIDEO]( https://ideas-productivity.org/events/hpc-best-practices-webinars/#webinar018). Please update deck, table, description, metadata etc. Remove subresources section. Add a link in the description to  on-demand learning blog post  located [HERE](https://bssw.io/blog_posts/on-demand-learning-for-better-scientific-software-how-to-use-resources-technology-to-optimize-your-productivity).

- [x] 3. The article titled [An Introduction to User Stories and How to Write Them
](https://github.com/betterscientificsoftware/bssw.io/blob/master/CuratedContent/UserStoriesREVISE.md) needs to be converted into an Original article.

- [x]  4. The article titled [Understanding Compatibility of Performance Portability Tools](https://github.com/betterscientificsoftware/bssw.io/blob/master/CuratedContent/WhatPerfPortabilityToolsAreCompatibleREVISE.md) needs to be converted into an Original article.

**Comment by rinkug** [comment]
@karbarz : Could you try to get started with the above 4 items?

**Comment by karbarz** [comment]
PR #844 created for this issue.

1st article has been updated.

**Comment by karbarz** [comment]
@rinkug 
Reviewed "An Introduction to User Stories and How to Write Them" - no changes were necessary and all links were active and correct.

**Comment by rinkug** [comment]
All articles have been updated
