### ISSUE TITLE
Software Quality Days Conference and Tools Fair (SWQD 2022) Event

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#867]
From @bernhold,

Software Quality Days Conference and Tools Fair (SWQD 2022)
January 18-20, 2022, Vienna, Auastria
www.software-quality-days.com (currently being updated)
 
https://listserv.acm.org/scripts/wa-acmlpx.exe?A2=SEWORLD;49ba1b4e.2105

**Comment by bernhold** [comment]
#872 has been published.  I think this is done.
