### ISSUE TITLE
Curated content has wrong github id

### ISSUE THREAD

**Issue by rinkug** [betterscientificsoftware/bssw.io#893]
The following article has a wrong github is for @bartlettroscoe 
https://bssw.io/items/critical-beginner-git-usage-tips

**Comment by bartlettroscoe** [comment]
Addressed by PR #894?

**Comment by bernhold** [comment]
This was addressed in PR #889. The site may not have been rebuilt since it was merged.

**Comment by bernhold** [comment]
Sorry, for whatever reason I see that #889 didn't get merged and has been overtaken by #894.  Sorry
