### ISSUE TITLE
Why three dashes instead of two for xml comments

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#912]
We appear to have [guidance for XML comments](https://betterscientificsoftware.github.io/bssw.io/bssw_content_metadata.html) that specifieds *three* dashes. But, XML standard is for two (`<!--My comment-->`). 

Is there any reason we are not following the standard?

**Comment by bernhold** [comment]
Mark, that's specifically for the metadata our front-end system uses.  Regular (two-dash) XML comments work fine as comments.
