### ISSUE TITLE
Experiment with Grammarly?

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#928]
I don't think we can automate this, but it might be interesting to explore <https://www.grammarly.com/> for BSSw content.  They have a fremium model.  The premium version is $12/mo.  I think we'd want to try both to compare.

I think we (EB members) should experiment initially, but in the long run, this might be something we ask our Editorial Assistant to handle.

For initial experiments, we might want to focus on just one type of content at a time.  I'm inclined to think it would be most useful on blog articles, but we shouldn't exclude other types.

**Comment by rinkug** [comment]
@karbarz looked at this and found free version limited. Plan to look at paid version?

**Comment by rinkug** [comment]
@karbarz : Pls update this ticket

**Comment by karbarz** [comment]
It was decided to forgo Grammarly - it doesn't seem to help us in the aspects necessary. 
We have purchased a month's subscription with spellingreport.com instead.
