### ISSUE TITLE
Organization of interest: ACM Emerging Interest Group on Reproducibility and Replicability

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#930]
Author: @rinkug 

https://reproducibility.acm.org/

It seems like one of the things people are seeking is like-minded communities.  Seems like this is one worth capturing.

**Comment by pagrubel** [comment]
Should this be combined with #864

**Comment by bernhold** [comment]
This group is still not very active, AFAICT.  But they are organizing a conference (REP23).  Maybe if we turn more people onto this, it will *become* more active?

I'm inclined to agree with Pat's suggestion above, that we combine with #864 and anything else we can find on the topic.  We can mention that it isn't very active yet.
