### ISSUE TITLE
CC for Git Detached HEAD

### ISSUE THREAD

**Issue by markcmiller86** [betterscientificsoftware/bssw.io#948]
Found this really useful ref regarding `Git Detached HEAD` state.

https://www.cloudbees.com/blog/git-detached-head

We should write a CC for it.

**Comment by bernhold** [comment]
This is not meant to be argumentative.  I'm just thinking out loud here...

This seems like a page you could categorize under "tips, tricks, and dark corners" of "important topic/tool X".  In this day and age, there are presumably lots of such resources out there for any given X.  

What's the BSSw value add for a resource like this?  

Is this something people would look up when they encounter it?  In which case, what benefit is there in us creating an additional page that links to the resource which I presume would be findable with Google?  Maybe we'd (ever so slightly) increase its ranking and make it more findable? In this case, I'm not sure its worth our effort.

Or is this a trick our users might find useful to know about beforehand?  How would our readers know that they should look at this page?  What if we instead created a "tips, tricks, and dark corners of Git" CC article and collected this and other useful resources there?  Would that be more valuable to our readers?  Would it make the information more easily findable on our site?

**Comment by markcmiller86** [comment]
> This seems like a page you could categorize under "tips, tricks, and dark corners" of "important topic/tool X". In this day and age, there are presumably lots of such resources out there for any given X.

I agree with this. And, I agree that the resource I mentioned here is of this ilk.

But, I think your remarks also might suggest a niche, value-added thing  bssw.io can do...to curate lists of such "tips, tricks and dark corners" almost like a cheat sheet of sorts, for tools we know already have high traction for our audience. I see other users at LLNL create cheat sheets for all sorts of things but usually for things like Lustre, GPFS, batch submission system, archival storage system, networks, ssh, etc. Such resources can be very helpful productivity tools.

Maybe the article I started on telecom tools is a bit like this...a long cheat sheet of sorts for telecom tool features, etc. I dunno?

**Comment by markcmiller86** [comment]
OTOH, maybe that is too much in the weeds. I could be convinced of that.

**Comment by pagrubel** [comment]
I would love curated tips but think it may be way too much for us to keep up with.
