### ISSUE TITLE
EPIC: Working Group: Search

### ISSUE THREAD

**Issue by bernhold** [betterscientificsoftware/bssw.io#996]
Current Working Group Members:

* @bartlettroscoe 
* @markcmiller86

Protected Google Docs Link [here](https://docs.google.com/document/d/13a15KBb5SRvh7dv96x9fep8DbUuYE4LMLA4IuW8v7XU/edit)

**Comment by bernhold** [comment]
Related:
* #556

**Comment by bernhold** [comment]
I'm not on the working group, but I'll offer my two cents anyway...

* We need to be clear about *what* is searchable. From my perspective, probably all of the content on the  site
* I think most people these days will expect treatment of search terms similarly to the way Google does it
  - Quoted strings denote phrases
  - Multiple word without quotes are treated with an implicit AND operator (I thin currently bssw.io treats them as OR)
* I think results should be returned by default by most recently published/updated
* It might be useful to be able to control the ordering/grouping of results
  - Publication date
  - Resource type
  - title
  - author

**Comment by bernhold** [comment]
A comment from David Moulton in an IDEAS-Leads meeting about the current BSSw.io search capabilities:

> The search gives a very flat and potentially long list of content.  So improving meta data, and possibly providing easier options for refining searches and presenting results seems like a good place to start.

**Comment by bernhold** [comment]
Noted by Matt Stone:

> Currently known search issue: García (a Fellow) won't come up in a search unless the accent is specifically requested. We definitely want to address this in the new search solution.

**Comment by markcmiller86** [comment]
> García (a Fellow) won't come up in a search unless the accent is specifically requested.

Thats almost certainly a unicode character issue.

Just like we probably want default to be case-insensitive search, we probably unicode-insensitive search, unless surrounded by quotes.

**Comment by bartlettroscoe** [comment]
Note, there was a lot of discussion on the topic of "Search" recently in #1346.

**Comment by rinkug** [comment]
This is also related to issue #437. This particular issue wants the following
1. Ppublish date to be displayed during sorting and filtering
2. Option for Grouping items by resource type during searching? or searching by resource type

**Comment by rinkug** [comment]
Progress in issue #1613

**Comment by bernhold** [comment]
Can we call this done?

**Comment by rinkug** [comment]
I think we will be stopping with phase1 implementation. Thus this can be closed.
